microsoft/kiota

src/Kiota.Builder/CodeDOM/CodeElement.cs, src/Kiota.Builder/CodeDOM/CodeType.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/CSharpRefiner.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Writers/CSharpWriter.cs, src/Kiota.Builder/Writers/JavaWriter.cs, src/Kiota.Builder/Writers/TypeScriptWriter.cs
- first draft to support inheritance
- fixes a bug where the parent would not be reset when moving child elements
- moves classes with the same name as one child namespace to the child namespace in CSHarp
- fixes an issue where classes properties would be missing
- adds inheritance support for typescript
- adds support for inheristance for java
- fixes multi-level inheritance
partial #1
=> adds support for inheritance (allof)

.github/workflows/sonarcloud.yml, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.IntegrationTests/Kiota.Builder.IntegrationTests.csproj, tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj
=> - adds test run so coverage information is included in sonarqube

src/Kiota.Builder/KiotaBuilder.cs
fixes #68 removes depdency on operation id
the good side effect of this is that it puts some of the models in the right namespace/folder ( they were previously at the wrong place)
```
Users/InferenceClassification/OverridesResponse.cs -> Users/InferenceClassification/Overrides/OverridesResponse.cs
Users/MailFolders/ChildFoldersResponse.cs -> Users/MailFolders/ChildFolders/ChildFoldersResponse.cs
Users/MailFoldersResponse.cs -> Users/MailFolders/MailFoldersResponse.cs
Users/MailFolders/MessageRulesResponse.cs -> Users/MailFolders/MessageRules/MessageRulesResponse.cs
Users/Messages/AttachmentsResponse.cs -> Users/MailFolders/Messages/Attachments/AttachmentsResponse.cs
Users/MailFolders/Messages/ExtensionsResponse.cs -> Users/MailFolders/Messages/Extensions/ExtensionsResponse.cs …
```
=> - fixes #68 removes depdency on operation id

.github/workflows/abstractions-java.yml, .github/workflows/core-java.yml, core/typescript/package-lock.json, core/typescript/package.json
- - bumps core patch version
- - another attempt at fixing upload path for java libs
=> maintenance smh

README.md
There were some typos in the file, they have been corrected now.
=> Corrected a few typos.

docs/corelibrary.md, docs/index.md, docs/kiotaabstractions.md, tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Addressed #131 #133 
Added codemodel tests to verify generation of operations that return collections of objects.  Test is currently failing.
=> Updated documentation and added a codemodel test for collections

.github/workflows/codeql-analysis.yml, .github/workflows/dotnet.yml, .github/workflows/sonarcloud.yml, authentication/typescript/azure/package-lock.json, http/typescript/fetch/package-lock.json, http/typescript/fetch/package.json, serialization/typescript/json/package-lock.json, serialization/typescript/json/package.json
=> udpates package locks for publishing

authentication/typescript/azure/package-lock.json, http/typescript/fetch/package-lock.json, serialization/typescript/json/package-lock.json
=> - updates typescript package locks for release

authentication/typescript/azure/package-lock.json, http/typescript/fetch/package-lock.json, serialization/typescript/json/package-lock.json
=> - update package locks for publication

src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, src/Kiota.Builder/Writers/TypeScript/CodeClassDeclarationWriter.cs, tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeClassDeclarationWriterTests.cs
=> moves relative import calculation into a refiner

.github/dependabot.yml
=> adds dependenabot configuration for ruby abstractions

.github/workflows/http-dotnet-httpclient.yml
=> - fixes a bug where the http client workflow would not trigger for dotnet

README.md
thanks @nikitauc for the feedback!
=> - fixes docker instructions to replace the login when authenticating

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
- fixes #428 a bug where inline double defintion would make dom generation fail
No generation changes for the msgraph-mail sample
=> - fixes #428 a bug where inline double defintion would make dom generation fail

serialization/dotnet/json/.editorconfig, serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.sln, serialization/dotnet/json/README.md, serialization/dotnet/json/src/JsonParseNode.cs, serialization/dotnet/json/src/JsonParseNodeFactory.cs, serialization/dotnet/json/src/JsonSerializationWriter.cs, serialization/dotnet/json/src/JsonSerializationWriterFactory.cs, serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
This PR is purely cosmetic and does not alter any functionality in the code. It involves the following changes :-
- Adds any missing XML documentation for public methods/properties
- Adds the `<GenerateDocumentationFile>true</GenerateDocumentationFile>` attribute to the csproj file so that compiler warnings may be generated in the event the first condition above is not met.
- Adds a `.editorconfig` to the solution to help with consistent code styling
- Whitespace changes to move opening curly braces to new lines.
Related to https://github.com/microsoft/kiota/issues/358
=> Add doc comments for Serialization project for dotnet

authentication/dotnet/azure/.editorconfig, authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.sln, authentication/dotnet/azure/README.md, authentication/dotnet/azure/src/AzureIdentityAuthenticationProvider.cs, authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
This PR is purely cosmetic and does not alter any functionality in the code. It involves the following changes :-
- Adds any missing XML documentation for public methods/properties
- Adds the  `<GenerateDocumentationFile>true</GenerateDocumentationFile>`  attribute to the csproj file so that compiler warnings may be generated in the event the first condition above is not met.
- Adds a .editorconfig to the solution to help with consistent code styling
- Whitespace changes to move opening curly braces to new lines.
Related to #358
=> Add doc comments for Authentication project for dotnet 

abstractions/dotnet/src/NativeResponseWrapper.cs, abstractions/java/lib/src/main/java/com/microsoft/kiota/NativeResponseWrapper.java, abstractions/java/lib/src/main/java/com/microsoft/kiota/PentaFunction.java, abstractions/java/lib/src/main/java/com/microsoft/kiota/TriFunction.java, abstractions/typescript/src/nativeResponseWrapper.ts
fixes #521
no generation changes
related to #330
=> adds options support for native response handlers

CHANGELOG.md, src/kiota/kiota.csproj
Signed-off-by: GitHub <noreply@github.com>
=> - updates changelog for 008 release

docs/requiredtools/dotnet.md, docs/requiredtools/go.md, docs/requiredtools/java.md, docs/requiredtools/ruby.md, docs/requiredtools/typescript.md
This PR involves no code changes.
It fixes broken links in some of the documentation in `docs/requiredtools` folder most likely brough about by moving around some files)
=> Fixes broken links in required tools docs

http/ruby/nethttp/microsoft_kiota_nethttplibrary/lib/microsoft_kiota_nethttplibrary.rb, http/ruby/nethttp/microsoft_kiota_nethttplibrary/microsoft_kiota_nethttplibrary.gemspec, http/ruby/nethttp/microsoft_kiota_nethttplibrary/spec/microsoft_kiota_nethttp_spec.rb
Signed-off-by: GitHub <noreply@github.com>
=> - multiple fixes on the ruby http lib after rename preventing publish

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
https://github.com/microsoft/kiota-samples/pull/384
=> go scalar collections deserialization

CHANGELOG.md, serialization/go/json/json_parse_node.go, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- fixes a bug where json deserialization would fail in go
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/9
https://github.com/microsoft/kiota-samples/pull/392
=> fixes json deserialization for go

abstractions/go/api_client_builder.go, abstractions/go/authentication/anonymous_authentication_provider.go, abstractions/go/authentication/authentication_provider.go, abstractions/go/authentication/base_bearer_token_authentication_provider.go, abstractions/go/http_method.go, abstractions/go/request_adapter.go, abstractions/go/request_information.go, abstractions/go/request_option.go, abstractions/go/response_handler.go, abstractions/go/serialization/parsable.go, abstractions/go/serialization/parse_node.go, abstractions/go/serialization/parse_node_factory.go, abstractions/go/serialization/parse_node_factory_registry.go, abstractions/go/serialization/serialization_writer.go, abstractions/go/serialization/serialization_writer_factory.go, abstractions/go/serialization/serialization_writer_factory_registry.go, http/go/nethttp/nethttp_request_adapter.go
partial #792
I'm only doing the abstractions at that time to double check we're getting the expected results on pkg.go.dev
=> aligns go doc comments for abstractions

http/typescript/fetch/README.md
=> Update README.md for typescript fetch library

abstractions/go/request_information.go, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-go/issues/20
https://github.com/microsoft/kiota-samples/pull/403
=> - fixes a bug where query parameters would be missing in go

src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #836
no impact on our samples
=> bugfix: inherited properties would be missing inheritance information

CHANGELOG.md, authentication/go/azure/azure_identity_authentication_provider.go, http/go/nethttp/kiota_client_factory.go, http/go/nethttp/middleware.go, http/go/nethttp/nethttp_request_adapter.go, http/go/nethttp/pipeline.go, http/go/nethttp/redirect_handler.go, http/go/nethttp/retry_handler.go, serialization/go/json/json_parse_node.go, serialization/go/json/json_parse_node_factory.go, serialization/go/json/json_serialization_writer.go, serialization/go/json/json_serialization_writer_factory.go, src/Kiota.Builder/Writers/Go/CodeClassDeclarationWriter.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
- fixes doc comments for http library
- fixes doc comments for authentication library
- fixes doc comments for serialization library
- udpate go generation to align doc comments
fixes #792
https://github.com/microsoft/kiota-samples/pull/404
=> aligns doc comments for generation and core packages

.vscode/settings.json, docs/_config.yml, docs/designoverview.md, docs/experience.md, docs/extending/authentication.md, docs/extending/corelibrary.md, docs/extending/index.md, docs/extending/kiotaabstractions.md, docs/extending/models.md, docs/extending/requestbuilders.md, docs/generator/binaries.md, docs/generator/build.md, docs/generator/docker.md, docs/generator/index.md, docs/generator/tool.md, docs/getstarted.md, docs/index.md, docs/microsoftgraph.md, docs/odata.md, docs/requiredtools/dotnet.md, docs/requiredtools/go.md, docs/requiredtools/index.md, docs/requiredtools/java.md, docs/requiredtools/kiota.md, docs/requiredtools/ruby.md, docs/requiredtools/typescript.md, docs/using.md
Moved docs into subfolders and created a TOC hierarchy.
=> Docs reorganization

docs/experience.md, docs/extending/authentication.md, docs/extending/kiotaabstractions.md, docs/extending/models.md, docs/extending/requestbuilders.md, docs/extending/serialization.md, docs/odata.md, docs/requiredtools/dotnet.md
- fixes #129 and adds conceptual documentation for the request builders
- renames core by request adapter
- fixes #130 adds documentation for models
fixes #132
=> additional concepts documentation

src/Kiota.Builder/Writers/Go/CodeClassDeclarationWriter.cs
Related https://github.com/microsoftgraph/msgraph-sdk-go/pull/27
No changelog entry as we already have one from the previous fix
https://github.com/microsoft/kiota-samples/pull/417
=> fixes a casing issue with go doc comments

.github/dependabot.yml, .github/workflows/abstractions-php.yml, abstractions/php/composer.json, abstractions/php/phpunit.xml, abstractions/php/src/RequestInformation.php, abstractions/php/src/Store/InMemoryBackingStore.php, abstractions/php/tests/Microsoft/Kiota/Tests/SampleTest.php
- Adds running of unit tests on the PHP abstractions.
- Adds static analysis support for PHP abstractions.
- Adds dependabot for abstractions.
=> Add checks for changes in PHP abstractions.

CHANGELOG.md, serialization/go/json/json_serialization_writer.go
=> - Fixes a bug in Go where empty collections would not be serialized

CHANGELOG.md, abstractions/go/request_information.go
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/31
=> Fixes a bug where OData select query parameter would not be normalized

CHANGELOG.md, src/Kiota.Builder/Refiners/CSharpRefiner.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
=> - fixes a bug where generation would fail because of empty usings

CHANGELOG.md, abstractions/go/api_client_builder.go, abstractions/go/api_client_builder_test.go
fixes https://github.com/microsoftgraph/msgraph-sdk-go/issues/54
=> race condition go client fix

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
fixes #1069
https://github.com/microsoft/kiota-samples/pull/480
=> go array serialization update

abstractions/php/src/Authentication/AccessTokenProvider.php, abstractions/php/src/Authentication/AllowedHostsValidator.php, abstractions/php/src/Authentication/AuthenticationProvider.php, abstractions/php/src/Authentication/BaseBearerTokenAuthenticationProvider.php, abstractions/php/src/RequestInformation.php, abstractions/php/tests/Authentication/AllowedHostsValidatorTest.php
=> Split Authentication interfaces for PHP

.github/workflows/abstractions-java.yml, .github/workflows/authentication-java-azure.yml, .github/workflows/http-java-okhttp.yml, .github/workflows/serialization-java-json.yml, abstractions/java/gradle/wrapper/gradle-wrapper.properties, authentication/java/azure/gradle/wrapper/gradle-wrapper.properties, http/java/okhttp/gradle/wrapper/gradle-wrapper.properties, serialization/java/json/gradle/wrapper/gradle-wrapper.properties
- bumps java version to 17 in pipelines
- upgrades gradle wrappers
=> updates gradle wrapper

abstractions/go/go.mod, abstractions/go/go.sum, abstractions/go/serialization/iso_duration.go, abstractions/go/serialization/iso_duration_test.go
=> - updates reference to go duration and fixes related bugs

http/go/nethttp/compression_handler.go, http/go/nethttp/compression_handler_test.go, http/go/nethttp/kiota_client_factory.go, http/go/nethttp/pipeline.go
Adds compression handler
Fixes [#14](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/14)
=> Ft compression handler #14

authentication/typescript/azure/package-lock.json, authentication/typescript/azure/package.json
=> - fixes blocked dependabot PR

.github/dependabot.yml, .gitmodules, README.md
related https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/47
=> - adds a link to the samples repo in the readme

cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/FormatterType.cs, cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFilter.cs, cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatter.cs, cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatterFactory.cs, cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
A JMESPath output filter will be implemented in the graph core library
=> Add output filter contract

CHANGELOG.md, http/go/nethttp/kiota_client_factory.go
fixes https://github.com/microsoftgraph/msgraph-sdk-go/issues/91
=> fixes a leaky go http client configuration

CHANGELOG.md, abstractions/go/authentication/anonymous_authentication_provider.go, abstractions/go/authentication/authentication_provider.go, abstractions/go/authentication/base_bearer_token_authentication_provider.go, abstractions/go/request_adapter.go, abstractions/go/request_information_test.go, http/go/nethttp/nethttp_request_adapter.go, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/67#issuecomment-1055762790
=> - Fixed a bug in Go generator where temporary url template parameters would not be used preventing the use of raw urls

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #1272 empty error schema generation fail
=> - fixes #1272 empty error schema generation fail

CHANGELOG.md, abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj, abstractions/dotnet/src/serialization/IParseNode.cs, abstractions/dotnet/src/serialization/ISerializationWriter.cs, abstractions/go/serialization/parse_node.go, abstractions/go/serialization/serialization_writer.go, abstractions/java/lib/build.gradle, abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/ParseNode.java, abstractions/java/lib/src/main/java/com/microsoft/kiota/serialization/SerializationWriter.java, serialization/dotnet/json/src/JsonParseNode.cs, serialization/dotnet/json/src/JsonSerializationWriter.cs, serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj, serialization/go/json/json_parse_node.go, serialization/go/json/json_serialization_writer.go, serialization/java/json/lib/build.gradle, serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonParseNode.java, serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonSerializationWriter.java, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/JavaRefiner.cs, src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs, src/Kiota.Builder/Writers/Go/GoConventionService.cs, src/Kiota.Builder/Writers/Java/JavaConventionService.cs, src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
=> adds missing type mappings

CHANGELOG.md, docs/using.md, src/Kiota.Builder/GenerationConfiguration.cs, src/Kiota.Builder/KiotaBuilder.cs, src/kiota/KiotaHost.cs
=> - adds a clean ouput argument

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes #1273 a bug where unnecessary namespaces would be added to models generation

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Go/GoConventionService.cs
=> - fixes a bug for go byt arrays

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes #990 a bug where the generator would introduce unnecessary union types for nullables

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes #1270 a bug where missing schema title would make union types fail

CHANGELOG.md, abstractions/go/serialization/parsable.go, serialization/go/json/json_serialization_writer.go, src/Kiota.Builder/CodeDOM/CodeMethod.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
partial #1404
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/111
https://github.com/microsoft/kiota-samples/pull/567
=> go nil check serialization fix

CHANGELOG.md, abstractions/typescript/package-lock.json, abstractions/typescript/package.json, abstractions/typescript/src/apiError.ts, serialization/typescript/json/package-lock.json, serialization/typescript/json/package.json, serialization/typescript/json/src/jsonParseNode.ts, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
=> - fixes a bug where service errors would not deserialize properly for typescript

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> multiple schema type generation fixes

CHANGELOG.md, http/go/nethttp/nethttp_request_adapter.go, http/java/okhttp/lib/build.gradle, http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> add support for 204

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs
fixes #1380
generation diff https://github.com/microsoft/kiota-samples/pull/583
=> renames request parameters

CHANGELOG.md, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
fixes #1443
Generation diff https://github.com/microsoft/kiota-samples/pull/582
=> - fixes #1443 a bug where the client would reset the base url if previously set

CHANGELOG.md, src/kiota/kiota.csproj
=> - 21 release

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #1483
no generation diff as a change in the conversion library is required
=> - fixes #1483 a bug with models namespace generation

src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs, src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs, tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs, tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs, tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Closes microsoftgraph/msgraph-cli#98
=> Fix parameters assignment in handler methods

CHANGELOG.md, src/Kiota.Builder/Refiners/GoRefiner.cs, tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
generation diff https://github.com/microsoft/kiota-samples/pull/662
=> - fixes a bug in the go overloads generation

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeElement.cs, src/Kiota.Builder/CodeDOM/CodeEnum.cs, src/Kiota.Builder/CodeDOM/CodeEnumOption.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/OpenApiExtensions/OpenApiEnumValuesDescriptionExtension.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs, src/Kiota.Builder/Writers/Go/CodeEnumWriter.cs, src/Kiota.Builder/Writers/Java/CodeEnumWriter.cs, src/Kiota.Builder/Writers/Java/JavaConventionService.cs, src/Kiota.Builder/Writers/Php/CodeEnumWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeEnumWriter.cs, src/Kiota.Builder/Writers/Swift/CodeEnumWriter.cs, src/Kiota.Builder/Writers/TypeScript/CodeEnumWriter.cs, src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs, tests/Kiota.Builder.Tests/CodeDOM/CodeEnumTests.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiEnumValuesDescriptionExtensionTests.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeEnumWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeEnumWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeEnumWriterTests.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeEnumWriterTests.cs
fixes #90
https://github.com/microsoft/kiota-samples/pull/666
=> adds support for enum descriptions

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
fixes #1578, no diff in our samples
=> - adds support for enums responses in Go

CHANGELOG.md, src/kiota/KiotaHost.cs
=> - fixes a bug where log entries would be missing

.azure-pipelines/ci-build.yml, src/Kiota.Builder/Kiota.Builder.csproj, src/Microsoft.OpenApi.Kiota.ApiDescription.Client/Microsoft.OpenApi.Kiota.ApiDescription.Client.nuspec
=> builder as package

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
=> - adds an explicit error message for external references

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs
=> - fixes an issue where some critical errors would not return a failed exit code

CHANGELOG.md, src/Kiota.Builder/Refiners/PhpRefiner.cs
PHP doesn't support nested classses.
Generation diff: https://github.com/microsoft/kiota-samples/pull/731/files
closes #1536
closes #1538
=> Move nested request config classes to separate files

CHANGELOG.md, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Php/PhpConventionService.cs
Closes #1616 
Generation diff.
[microsoft/kiota-samples/pull/751](https://github.com/microsoft/kiota-samples/pull/751)
=> Add accept header PHP

CHANGELOG.md, docs/get-started/php.md
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/890
closes https://github.com/microsoft/kiota/issues/1635
=> Add PHP Getting Started docs

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs
=> - fixes a bug where additional data and backing store properties would be duplicated

.azure-pipelines/ci-build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/codeql-required-workaround.yml, .github/workflows/dotnet-required-workaround.yml, .github/workflows/dotnet.yml, .github/workflows/http-python-requests.yml, .github/workflows/serialization-python-json.yml, .github/workflows/sonarcloud.yml
- - fixes typo in python workflows definition
- - fixes typos in path ignore - adds a workflow for required validation when paths are ignored
- - fixes typo in paths ignore
=> multiple workflows fixes

abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/authentication/allowed_hosts_validator.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/authentication/base_bearer_token_authentication_provider.rb
=> Implemented AllowedHostsValidator class

.github/workflows/http-ruby-nethttp.yml, .github/workflows/serialization-ruby-json.yml
=> - fixes jruby-head CI

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
samples update https://github.com/microsoft/kiota-samples/pull/796
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/205
=> - fixes a bug where go binary would not map properly

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeClass.cs, src/Kiota.Builder/CodeDOM/CodeMethod.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs, tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
=> - fixes a bug where discriminator mappings across namespaces could create circular dependencies in Go

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where query parameters types would ignore the format

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - bumps version for 0.3.0 release

src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where unused types would be generated

src/Kiota.Builder/CodeDOM/CodeClass.cs, src/Kiota.Builder/CodeDOM/CodeProperty.cs, src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/212
=> - fixes a bug where odata type serialization name would be truncated

abstractions/ruby/microsoft_kiota_abstractions/README.md, serialization/ruby/json/microsoft_kiota_serialization/Gemfile
Updating the version of abstractions
=> Updating Abstractions version

CHANGELOG.md, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Resolves https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/26
=> Decrease verbose code generated in go

CHANGELOG.md, abstractions/ruby/microsoft_kiota_abstractions/Rakefile, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/authentication/allowed_hosts_validator.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/authentication/base_bearer_token_authentication_provider.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/request_information.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/serialization/parse_node_factory.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb, abstractions/ruby/microsoft_kiota_abstractions/spec/microsoft_kiota_abstractions_spec.rb, authentication/ruby/oauth/microsoft_kiota_authentication_oauth/lib/microsoft_kiota_authentication_oauth/oauth_access_token_provider.rb, authentication/ruby/oauth/microsoft_kiota_authentication_oauth/lib/microsoft_kiota_authentication_oauth/version.rb, authentication/ruby/oauth/microsoft_kiota_authentication_oauth/microsoft_kiota_authentication_oauth.gemspec, http/ruby/nethttp/microsoft_kiota_nethttplibrary/Gemfile, http/ruby/nethttp/microsoft_kiota_nethttplibrary/lib/microsoft_kiota_nethttplibrary/net_http_request_adapter.rb, http/ruby/nethttp/microsoft_kiota_nethttplibrary/lib/microsoft_kiota_nethttplibrary/version.rb, serialization/ruby/json/microsoft_kiota_serialization/lib/microsoft_kiota_serialization/json_parse_node_factory.rb, serialization/ruby/json/microsoft_kiota_serialization/lib/microsoft_kiota_serialization/version.rb, serialization/ruby/json/microsoft_kiota_serialization/spec/microsoft_kiota_serialization_spec.rb
PR to address miscellaneous issues with ruby sdk
=> Address miscellaneous issues with Ruby Nethttp and Abstractions

docs/get-started/ruby.md
I hadn't committed the formatting changes when I drafted the last PR, sorry about that!
=> Formatting Changes

CHANGELOG.md, docs/extending/statuscodes.md, src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> adds support for range responses

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - bumps versions and updates changelog for o five release

CHANGELOG.md, docs/using.md, src/Kiota.Builder/GenerationConfiguration.cs, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Builder/KiotaBuilder.cs, src/kiota/KiotaCommandHandler.cs, src/kiota/KiotaHost.cs, tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
- - adds support for glob patterns filtering of path items
- - documents the path filtering arguments
=> adds support for filtering paths items during generation

docs/experience.md, docs/extending/index.md, docs/get-started/ruby.md
=> fix typos in docs

src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
=> - fixes sonarcloud reported issues

CHANGELOG.md, src/kiota/Handlers/BaseKiotaCommandHandler.cs, src/kiota/Handlers/KiotaDownloadCommandHandler.cs, src/kiota/Handlers/KiotaGenerationCommandHandler.cs, src/kiota/Handlers/KiotaInfoCommandHandler.cs, src/kiota/Handlers/KiotaSeachBasedCommandHandler.cs, src/kiota/Handlers/KiotaSearchCommandHandler.cs
=> - fixes #1895 adds a colours scheme for console messages

src/kiota/Handlers/KiotaInfoCommandHandler.cs
=> - fixes #1912 a bug where the info command would not format strings properly

README.md
Changed the intro paragraph to use the consumer focused pitch.  Also added a link to the KiotaApp sample
=> Updated wording in the readme

src/Kiota.Builder/CodeRenderers/CodeRenderer.cs, src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs, src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs, src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs, src/kiota/Handlers/KiotaDownloadCommandHandler.cs, tests/Kiota.Builder.Tests/Caching/DocumentCachingProviderTests.cs, tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
A continuation of #1915 which replaces instances of `using` statements with `await using` statements where possible in order to prevent the disposing to be blocking.
=> Async dispose and minor performance improvements.

src/Kiota.Web/ComponentWithCancellationToken.cs, src/Kiota.Web/Shared/MainLayout.razor, src/Kiota.Web/Shared/MainLayout.razor.css
=> code linting for app.kiota.dev

CHANGELOG.md, abstractions/swift/Source/MicrosoftKiotaAbstractions/RequestInformation.swift, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
=> - Fixes a bug where collections request bodies would not serialize single elements properly

src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs, src/Kiota.Web/Pages/Generate.razor, src/Kiota.Web/Pages/Index.fr.resx, src/Kiota.Web/Pages/Index.razor, src/Kiota.Web/Pages/Index.resx, src/Kiota.Web/Pages/Show.fr.resx, src/Kiota.Web/Pages/Show.razor, src/Kiota.Web/Pages/Show.resx, src/Kiota.Web/wwwroot/appsettings.json, src/kiota/appsettings.json
-  - fixes a bug where duplicate entries in the index file would make the search command fail
- - orders search results
- - adds a no results indicator
- - adds on enter submission for search
- - shortens label for generate button
- - measures actions durations - fixes missing language in event data
- - adds "caching" to the show page
- - fixes document caching for show page
=> minor fixes for app.kiota.dev

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - bumps version for 0.7.0 release

.azure-pipelines/ci-build.yml, .github/workflows/create-release.yml, CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - fixes publishing workflows to unblock release

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
=> - fixes array buffer nullability for TS

.github/workflows/sonarcloud.yml, CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Web/Kiota.Web.csproj, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where path parameter would be missing if no operation was present at the segment level

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - bumps version for 0.8.0 release

.github/workflows/create-release.yml
=> - adds missing workloads restore for kiota web deployment

src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/PathSegmenters/GoPathSegmenter.cs, src/Kiota.Builder/Refiners/GoRefiner.cs
- - code linting
- - implements file names shorting using hashing
=> fixes go file name shortening

src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/PathSegmenters/GoPathSegmenter.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
This PR refactor Go generation to  reduce number of generated packages. This should help improve compilation time for Go SDK
Introduced changes are:
1. Flatten go structure
2. Remove use of generic helper methods
=> Feature: Flatten Go Packages 

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Builder/SearchProviders/GitHub/GitHubSearchProvider.cs, src/Kiota.Builder/SearchProviders/GitHub/Index/IndexRoot.cs, src/Kiota.Web/wwwroot/appsettings.json, src/kiota/appsettings.json, src/kiota/kiota.csproj
=> - bumps version numbers for 0.9.0 release

CHANGELOG.md, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
=> checks base url before setting it in ruby

CHANGELOG.md, src/Kiota.Builder/SearchProviders/GitHub/GitHubClient/Models/RepoSearchResultItem.cs, src/Kiota.Builder/SearchProviders/GitHub/GitHubSearchProvider.cs
=> - fixes #2095 a bug where a missing base url would make search fail

CHANGELOG.md, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/request_information.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb, abstractions/ruby/microsoft_kiota_abstractions/spec/query_parameters_mock.rb, abstractions/ruby/microsoft_kiota_abstractions/spec/request_information_spec.rb, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/CodePropertyWriter.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodePropertyWriterTests.cs
=> - adds support for query parameters names aliasing in Ruby

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/CodePropertyWriter.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
=> - adds support for default properties values in Ruby

CHANGELOG.md, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/request_adapter.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/serialization/parse_node.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb, authentication/ruby/oauth/microsoft_kiota_authentication_oauth/microsoft_kiota_authentication_oauth.gemspec, http/ruby/faraday/microsoft_kiota_faraday/lib/microsoft_kiota_faraday/faraday_request_adapter.rb, http/ruby/faraday/microsoft_kiota_faraday/lib/microsoft_kiota_faraday/version.rb, http/ruby/faraday/microsoft_kiota_faraday/microsoft_kiota_faraday.gemspec, serialization/ruby/json/microsoft_kiota_serialization/lib/microsoft_kiota_serialization/json_parse_node.rb, serialization/ruby/json/microsoft_kiota_serialization/lib/microsoft_kiota_serialization/version.rb, serialization/ruby/json/microsoft_kiota_serialization/microsoft_kiota_serialization.gemspec, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/RubyConventionService.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
=> - adds support for discriminator in ruby

CHANGELOG.md, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/api_error.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/request_adapter.rb, abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb, authentication/ruby/oauth/microsoft_kiota_authentication_oauth/microsoft_kiota_authentication_oauth.gemspec, http/ruby/faraday/microsoft_kiota_faraday/lib/microsoft_kiota_faraday/faraday_request_adapter.rb, http/ruby/faraday/microsoft_kiota_faraday/lib/microsoft_kiota_faraday/version.rb, http/ruby/faraday/microsoft_kiota_faraday/microsoft_kiota_faraday.gemspec, serialization/ruby/json/microsoft_kiota_serialization/microsoft_kiota_serialization.gemspec, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Writers/Ruby/CodeClassDeclarationWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/RubyConventionService.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeClassEndWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
=>  - adds support for error mapping in Ruby

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Web/wwwroot/appsettings.json, src/kiota/appsettings.json, src/kiota/kiota.csproj
=> - bumps version to 0.10.0 for release

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeMethod.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where CLI query/header/path parameters would not be deduplicated

CHANGELOG.md, src/Kiota.Builder/CodeRenderers/CodeRenderer.cs, src/Kiota.Builder/PathSegmenters/CommonPathSegmenter.cs, src/Kiota.Builder/PathSegmenters/IPathSegmenter.cs, src/Kiota.Builder/PathSegmenters/RubyPathSegmenter.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Writers/NamespaceClassNamesProvider.cs, src/Kiota.Builder/Writers/RelativeImportManager.cs, src/Kiota.Builder/Writers/Ruby/CodeClassDeclarationWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Ruby/CodeNamespaceWriter.cs, src/Kiota.Builder/Writers/Ruby/RubyWriter.cs, src/Kiota.Builder/Writers/TypeScript/CodeNameSpaceWriter.cs, tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeClassDeclarationWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeNamespaceWriterTests.cs
fixes https://github.com/microsoftgraph/msgraph-sdk-ruby-core/issues/2
=> - fixes a bug in ruby where file names or paths could be too long to be packaged

CHANGELOG.md, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Closes https://github.com/microsoft/kiota/issues/2129
=> [PHP] Add baseUrl in path Parameters from request adapter baseUrl

src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
=> - fixes #2157

CHANGELOG.md, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- Fix minor typo in adding Accept Header PHP.
=> Fix typo in adding accept header PHP.

CHANGELOG.md, src/Kiota.Builder/Refiners/PhpRefiner.cs, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
part of https://github.com/microsoft/kiota/issues/1856
=> PHP - Remove response handler parameter from request executor methods

.github/workflows/dotnet.yml
Following up on this comment:
https://github.com/microsoft/kiota/pull/2184#issuecomment-1405641324
cc. @baywet
=> Check the embedded defaults in release in CI

src/Kiota.Builder/CodeDOM/ProprietableBlock.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fix go serialize additional data
=> Fix go serialize additional data

CHANGELOG.md, src/Kiota.Builder/Refiners/JavaRefiner.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Seems like the regression happened here:
https://github.com/microsoft/kiota/commit/e681a4e960dcb7d16341a19bf0b1c09051ac6f0e
Ref: https://github.com/microsoft/kiota/pull/2202#discussion_r1090906802
=> Don't prefix with an underscore Java fields

src/Kiota.Builder/Refiners/JavaReservedNamesProvider.cs
=> Add more Java keywords

CHANGELOG.md, docs/extending/models.md, src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/Refiners/CSharpRefiner.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Refiners/JavaRefiner.cs, src/Kiota.Builder/Refiners/PhpRefiner.cs, src/Kiota.Builder/Refiners/PythonRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs, tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
Fix #2198
This proposal is to mangle the properties and accessors' names with an opinionated pattern depending on the language.
I will be happy to receive feedback from the languages experts.
=> [Proposal] Per language name mangling of properties and accessors

src/Kiota.Generated/KiotaAppSettingsGenerator.cs, src/Kiota.Generated/KiotaGenerated.csproj, src/Kiota.Generated/KiotaVersionGenerator.cs, src/Kiota.Generated/PathHelper.cs
=> - fixes a bug where vs debugging would fail for project

src/Kiota.Web/Kiota.Web.csproj, src/Kiota.Web/Program.cs
this reduces the number of icons from 19k to 5k, and consequently reduces the size of the assets service worker by a great deal too.
=> - attempt at reducing the number of icons being produced

.github/workflows/abstractions-swift.yml
=> - bumps swift version to fix gpg failure

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Web/wwwroot/appsettings.json, src/kiota/appsettings.json, src/kiota/kiota.csproj
=> - bumps version to 0.11.0 for release

docs/support.md
=> - adds precisions regarding the release schedule

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where descriptions with a path segment matching an HTTP verb would fail to generate

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Builder/SearchProviders/GitHub/GitHubClient/Models/RepoSearchResultItem.cs, src/kiota/kiota.csproj
=> - fixes a bug where search would fail because of a parsing issue

src/Kiota.Web/Kiota.Web.csproj, src/Kiota.Web/Program.cs, src/Kiota.Web/Shared/NavMenu.razor
=> - fixes configuration with fast fluent changes

CHANGELOG.md, src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs, tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
part of improve request configuration pattern · Issue #952 · microsoftgraph/msgraph-sdk-php
=> PHP - Change request options type in PHPDoc from map to array

CHANGELOG.md, src/Kiota.Builder/Caching/DocumentCachingProvider.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Lock/ILockManagementService.cs, src/Kiota.Builder/Lock/LockManagementService.cs
=> - adds restoration of the kiota-lock when the generation fails with clean output

src/Kiota.Builder/CodeDOM/CodeFile.cs, src/Kiota.Builder/CodeDOM/CodeNamespace.cs, src/Kiota.Builder/CodeRenderers/CodeRenderer.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Writers/Go/CodeFileBlockEndWriter.cs, src/Kiota.Builder/Writers/Go/CodeFileDeclarationWriter.cs, src/Kiota.Builder/Writers/Go/GoConventionService.cs, src/Kiota.Builder/Writers/Go/GoWriter.cs, src/Kiota.Builder/Writers/Go/StringExtensions.cs, src/Kiota.Builder/Writers/LanguageWriter.cs, tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Introduces code files in namespaces to allow grouping multiple CodeElements to the same file. This offers some improvements in compilation of Go.
Resolves https://github.com/microsoftgraph/msgraph-sdk-go/issues/373
=> Adds Code Files

docs/get-started/cli.md
@calebkiage please add the kiota commands to generate the SDK
=> Add the CLI read me file

src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
=> Revert go Enum serialization.

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, tests/Kiota.Builder.IntegrationTests/NoUnderscoresInModel.yaml
=> [Java] Normalize Enums

CHANGELOG.md, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Php/PhpConventionService.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Generation diff: https://github.com/microsoft/kiota-samples/pull/1730
=> PHP - Fix request configuration constructor PHPDoc

docs/get-started/python.md
Fixing https://github.com/microsoft/kiota/issues/2326
=> Updates to Python docs

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/JavaRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
Fix #2374 
Added a unit test for Java (as I forgot it in the last PR).
Should we proactively check all the languages or is it fine to fix them as soon as a relevant issue is opened?
=> Ruby - Normalize enum names

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/kiota/kiota.csproj, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where float64 would not be mapped in Java

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
=> Java - Normalize Method's Parameters Types

CHANGELOG.md, it/csharp/dotnet.csproj, src/Kiota.Builder/Refiners/CSharpRefiner.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
=> CSharp - Fix inherited constructor name

.github/workflows/integration-tests.yml
A couple of minor leftovers, we should also check if the merged fixes are now effective.
=> Minor IT tests leftovers

it/exec-cmd.ps1
Fix: https://github.com/microsoft/kiota/pull/2408#issuecomment-1466882656
@baywet if I'm missing anything else feel free to open issues and assign them to me, I'll catch up tomorrow morning
=> Minor IT leftover on CSharp

CHANGELOG.md, src/Kiota.Builder/SearchProviders/GitHub/GitHubSearchProvider.cs
=> - adds support for search forks in github

.azure-pipelines/ci-build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/dotnet.yml, .github/workflows/integration-tests.yml, .github/workflows/sonarcloud.yml, CHANGELOG.md, it/config.json, it/exec-cmd.ps1, it/generate-code.ps1, it/ruby/client.rb, src/Kiota.Builder/Extensions/StringExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/GoRefiner.cs, src/Kiota.Builder/Writers/Java/CodeEnumWriter.cs, tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeEnumWriterTests.cs
Ending up trying to fix the IT test failures, and found a few inconsistencies in the enum encoding etc. etc.
I'm using those changes to improve the feedback loop cycle in development.
Fix #2352
it also fix #2362 another missing normalization
=> Add a built-in dev mode to generate-code script

CHANGELOG.md, docs/using.md, src/Kiota.Builder/GlobComparer.cs, src/Kiota.Builder/KiotaBuilder.cs, src/kiota/KiotaHost.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=>  - adds the ability to filter on an operation

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Noticed the problem while working on #2442 , and this is an easy fix 🙂
=> Normalize Inherits and Implements type names

CHANGELOG.md, src/kiota/Handlers/KiotaDownloadCommandHandler.cs
=> - fixes the extension of downloaded files when using the default path

src/Kiota.Builder/Refiners/ShellRefiner.cs, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
DLL size reduction in a sample:
5139kb -> 4616kb
=> Update: Use base request builder

CHANGELOG.md, src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
=> - fixes a bug where requests with bodies would fail in Ruby

src/Kiota.Builder/SearchProviders/GitHub/GitHubSearchProvider.cs
=> - fixes a bug in kiota web caused by trimming

it/config.json
Cannot reproduce #2353 locally, it should have been fixed meanwhile.
Closes #2373
=> chore - re-enable a Go IT test

CHANGELOG.md, it/config.json, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug for inline type sanitazation

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Web/wwwroot/appsettings.json, src/kiota/appsettings.json, src/kiota/kiota.csproj, vscode/microsoft-kiota/package.json
- - bumps version for 1.1.0 release
- - updates extension description
- - updates kiota dependencies list
=> release 1.1.0

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/OpenApiServerComparer.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - maps base url to https instead of http when multiple

CHANGELOG.md, vscode/microsoft-kiota/src/steps.ts
=> - fixes navback count for vs code

src/Kiota.Builder/CodeDOM/CodeClass.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where code trimming would be too aggressive

src/Kiota.Builder/Kiota.Builder.csproj
Use non pre-release packages to unblock kiota release
=> Use non pre-release packages

src/Kiota.Builder/KiotaBuilder.cs
=> - adds a warning when no paths are returned

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> - adds icon, license, and readme to packages defintions

src/kiota/Rpc/Server.cs
=> - moves vs code operations first

CONTRIBUTING.md
This PR adds content to the CONTRIBUTING.md to describe the mechanics of building and testing the project.
=> Add content to CONTRIBUTING.md to guide new contributors

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
fixes #1855
related https://github.com/microsoft/kiota-typescript/pull/734
=> - removes response handler generation in typescript

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs
=> - fixed a bug where types trimming would be too aggressive and would trim parent types of properties

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
fixes a bug where inheriting error definitions would missing the API error parent in typescript
=> - fixes a bug where TypeScript errors would loose inheritance to base error definition

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, src/kiota/Rpc/Server.cs, src/kiota/Rpc/ShowResult.cs, vscode/microsoft-kiota/debugging.md, vscode/microsoft-kiota/src/kiotaInterop.ts, vscode/microsoft-kiota/src/openApiTreeProvider.ts
=> - adds api title in vscode treeview

src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
Fix Sonar warning: https://sonarcloud.io/project/issues?resolved=false&types=BUG&id=microsoft_kiota&open=AYj9V-BHlYLZgCFva__p&tab=code
=> fix Sonar warning

it/python/pyproject.toml
=> - fixes invalid toml for python integration tests

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeBlock.cs, src/Kiota.Builder/CodeDOM/CodeClass.cs, src/Kiota.Builder/CodeDOM/CodeInterface.cs, src/Kiota.Builder/CodeDOM/CodeProperty.cs, src/Kiota.Builder/CodeDOM/IAlternativeName.cs, src/Kiota.Builder/CodeDOM/ProprietableBlock.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/ModelClassBuildLifecycle.cs, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs, tests/Kiota.Builder.Tests/TestHelper.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
This is the new pull request for #2869. At the moment it contains the old code plus the code from #2855. I'll continue to work on making this change work in a multi threaded setup on this branch.
=> Resolve property name conflicts second attempt

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, src/Kiota.Builder/Writers/TypeScript/CodeUsingWriter.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeUsingWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/2994
partial #2959
=> add import type statement for the model interface

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
hold for merge until #3091 is merged and released
=> Revert "- changes version to patch in csproj"

it/java/basic/pom.xml, it/java/pom.xml
This should fix the IT tests of Java
=> Fix the Java IT tests after the jakarta move

CHANGELOG.md, src/Kiota.Builder/Refiners/PhpRefiner.cs
https://github.com/microsoftgraph/msgraph-beta-sdk-php/pull/197
is failing due to the issue above.
=> Fix issue naming classes and uses when there is alias.

tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - adds a unit test to check for intermediate types

CHANGELOG.md, src/kiota/Rpc/IServer.cs, src/kiota/Rpc/Server.cs, vscode/microsoft-kiota/src/dependenciesViewProvider.ts, vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/getLanguageInformation.ts
=> - fixes an issue where dependencies would not show up for any other language than CSharp in the vscode extension

intellij/src/main/java/services/GenerateClientHandler.java, intellij/src/main/java/services/KiotaLoggedResult.java, intellij/src/main/java/services/KiotaSearchResult.java, intellij/src/main/java/services/LanguageDependency.java, intellij/src/main/java/services/LanguageInfoHandler.java, intellij/src/main/java/services/LanguageInformation.java, intellij/src/main/java/services/LanguagesInformation.java, intellij/src/main/java/services/MaturityLevel.java, intellij/src/main/java/services/VersionHandler.java, intellij/src/main/java/toolWindow/Kiota.java, intellij/src/main/java/toolWindow/LanguageInfoPopup.java, intellij/src/main/java/toolWindow/MyToolWindow.java, intellij/src/main/java/toolWindow/SearchResultsDialog.java
After the generation process, a dialog window will appear displaying the language-specific dependencies along with the installation commands.
=> Added a feature to show language dependencies

.azure-pipelines/ci-build.yml, .github/workflows/docker.yml, scripts/get-release-notes.ps1
=> - fixes workflow so we only release preview images when we find entries in release notes so it's aligned with ADO

CHANGELOG.md
=> - adds a changelog entry for python tracing

.github/workflows/idempotency-tests.yml, .gitignore, it/compare-generation.ps1
Partial fix for #3339 
At least the upload of the artifacts is fixed now.
I split the workflow as the uploaded artifacts and visualization were too much confused IMHO ...
=> Fix idempotency test results upload

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, src/kiota/Handlers/BaseKiotaCommandHandler.cs, src/kiota/Handlers/KiotaGenerationCommandHandler.cs, src/kiota/Handlers/KiotaShowCommandHandler.cs, src/kiota/Rpc/Server.cs
=> - fixes a bug where the hints would miss quotes for paths and always use the API manifest

it/python/requirements-dev.txt
=> Revert "Bump astroid from 2.15.7 to 3.0.0 in /it/python"

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> fixes edge case for inheritance description

it/config.json
=> Remove Java from suppression list for Dev.PipeDrive Integration test 

CHANGELOG.md, src/Kiota.Builder/Writers/CLI/CliCodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/CLI/CliCodeMethodWriterTests.cs
=> Log a message on skipped requests.

CHANGELOG.md, src/Kiota.Builder/Writers/CLI/CliCodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/CLI/CliCodeMethodWriterTests.cs
Remove required restriction in output format.
=> Remove json-no-indent option.

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
closes https://github.com/microsoft/kiota/issues/2964
=> Rename composed type wrapper when another class with similar name exists in namespace

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeProperty.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs, tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Fixes https://github.com/microsoft/kiota-serialization-json-dotnet/issues/131
=> Remove WireName lowercasing

CHANGELOG.md, src/Kiota.Builder/Extensions/StringExtensions.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
Closes https://github.com/microsoft/kiota/issues/3426
Fixes symbol cleanup with single quote character.
=> Fixes symbol cleanup with single quote character

CHANGELOG.md, src/Kiota.Builder/Configuration/GenerationConfiguration.cs, src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug with reserved models namespace name

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
Fixes https://github.com/microsoft/kiota/issues/3190
=> Resolve all lint errors related to import type usage in typescript

CHANGELOG.md, src/Kiota.Builder/Writers/Java/JavaConventionService.cs
Similar to https://github.com/microsoft/kiota/pull/3471
Is causing failure here: https://github.com/microsoftgraph/msgraph-sdk-java/actions/runs/6545825424/job/17775075637?pr=1580
=> "Decimal" should be translated to BigDecimal

vscode/microsoft-kiota/package.json
=> - aligns vscode version with types

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs, src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
This PR contains changes to restore the backing store feature for typescript
=> Restore backing store feature for typescript

src/kiota/KiotaHost.cs
Does this need a changelog entry too?
=> Fix the description of json output

it/exec-cmd.ps1, it/python/basic/test_sample.py, it/python/requirements-dev.txt
=> Add a basic MockServer integration test for Python

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiDeprecationExtensionExtensions.cs, tests/Kiota.Builder.Tests/Extensions/OpenApiDeprecationExtensionExtensionsTests.cs
=> Add null check for instances

CHANGELOG.md, src/Kiota.Builder/Validation/UrlFormEncodedComplex.cs, tests/Kiota.Builder.Tests/Validation/UrlFormEncodedComplexTests.cs
fixes #3569, related https://github.com/microsoft/OpenAPI.NET/pull/1444
=> - fixes an issue where the validation rule would warn for arrays in forms

CHANGELOG.md, src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
=> - fixes a serialization bug in typescript

src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
Missed adding the necessary param to crawl tree method call in #3737
=> Missed Crawl Tree Param

src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
related https://github.com/microsoft/kiota-typescript/pull/943
=> - updates headers set in typescript

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeBlock.cs, src/Kiota.Builder/KiotaBuilder.cs
=> - fixes constructor properties - fixes path segmentation

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug with path items deduplication

CHANGELOG.md, src/Kiota.Builder/CodeDOM/CodeParameter.cs, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Writers/CLI/CliCodeMethodWriter.cs, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, tests/Kiota.Builder.Tests/Writers/CLI/CliCodeMethodWriterTests.cs
Add content-type option to CLI command for requests with multiple allowed content types.
=> Add content-type option to CLI command

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Adds support for AnyOf arrays as described in
fixes #3786
=> Array support for AnyOf

CHANGELOG.md, src/kiota/Handlers/BaseKiotaCommandHandler.cs, src/kiota/Handlers/KiotaInfoCommandHandler.cs
=> - fixes missing dependency version in the info command

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs, tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
every day I strive to make @MaximRouiller happy
=> the max patch

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, src/Kiota.Builder/Refiners/JavaRefiner.cs, src/Kiota.Builder/Refiners/RubyRefiner.cs, tests/Kiota.Builder.IntegrationTests/GenerateSample.cs, tests/Kiota.Builder.IntegrationTests/NoUnderscoresInModel.yaml
I finally found the time to get to this 😅 
Fixes #3824
=> [Java] Fix generation of models with underscores

.github/workflows/load-tests.yml
=> - fixes description urls for load tests

CHANGELOG.md, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> - fixes a bug where scalar error mappings would be generated even though it's not supported by the http request adapter

.github/workflows/sonarcloud.yml
more information https://docs.opensource.microsoft.com/github/apps/permission-changes/
=>  - adds permissions to workflows

src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
=> - fixes minor typo in typescript generation

specs/cli/client-add.md, specs/cli/client-edit.md, specs/cli/client-generate.md, specs/cli/client-remove.md, specs/cli/config-migrate.md, specs/scenarios/kiota-config.md
It appears there was missing details in our latest merge. Just adding them here to ensure we have the full picture in the specs.
=> Updates to the kiota-config spec

it/exec-cmd.ps1
Noticed that the Mock Server Integration test where not being executed in CI 😢
=> Fix the Mock Server Integration Tests execution

specs/cli/client-add.md, specs/cli/client-edit.md, specs/cli/client-generate.md, specs/cli/client-remove.md, specs/cli/config-migrate.md, specs/cli/download.md, specs/cli/index.md, specs/cli/info.md, specs/cli/login.md, specs/cli/logout.md, specs/cli/search.md, specs/cli/show.md, specs/index.md, specs/scenarios/telemetry.md
This PR is aimed at starting the discussion about anonymous telemetry in kiota to offer a similar telemetry experience to the `dotnet` CLI. Goal is to ensure that this is fully privacy compliant and collects information only required for future investments.
=> specs: Telemetry in kiota

vscode/microsoft-kiota/l10n/bundle.l10n.ja.json
Support https://github.com/microsoft/kiota/pull/4359#issuecomment-2009713015
=> Add Japanese translation for #4359

CHANGELOG.md, src/kiota/appsettings.json
=> - switches typescript language maturity to preview

vscode/microsoft-kiota/l10n/bundle.l10n.zh-cn.json
=> - adds chinese translation to the vscode extension download changes

src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeConstantWriterTests.cs
Fixes: https://github.com/microsoft/kiota/issues/4405
=> remove quotes around enum object Type

CHANGELOG.md, src/kiota/appsettings.json
=> Bumps version for release 1.13.0

CHANGELOG.md, src/Kiota.Builder/Refiners/JavaReservedNamesProvider.cs, src/Kiota.Builder/Refiners/PhpReservedNamesProvider.cs
Fixes #4467
Adds ``object`` to the list of reserved names for Java and php reserved names provider class.
=> Adds ``object`` to the list of reserved names

.azure-pipelines/ci-build.yml
=> - migrates to AAD tokens from PATs for extension publishing due to ADO requirements

CHANGELOG.md, src/Kiota.Builder/Configuration/GenerationConfiguration.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Configuration/GenerationConfigurationTests.cs
=> Excluded kiota hash in generated plugin.

.github/dependabot.yml
=> - adds a new eslint group for typescript integration tests

.azure-pipelines/ci-build.yml
This reverts commit ed2fee44b61af520a01edd9545dc9e3004b9fd28.
=> Reapply "- migrates to AAD tokens from PATs for extension publishing due to ADO requirements"

CHANGELOG.md, src/kiota/KiotaHost.cs, src/kiota/Rpc/IServer.cs, src/kiota/Rpc/Server.cs
Isolates RPC server changes in #4500 to respect the `KIOTA_CONFIG_PREVIEW` 
This should ideally not affect the extension as it would need to pass the flag for it generate a workspace/plugins.
=> Updates the RPC server to respect the `KIOTA_CONFIG_PREVIEW` flag.

.github/workflows/dotnet.yml, vscode/microsoft-kiota/debugging.md
=> - adds side loading instructions for the vscode extension

.github/workflows/sonarcloud.yml
=> - replaces sonar login by token

.github/workflows/project-auto-add.yml
=> - fixes variable in issues automation script

src/Kiota.Builder/Writers/Go/CodeEnumWriter.cs, tests/Kiota.Builder.Tests/Writers/Go/CodeEnumWriterTests.cs
=> Refactor Go code to improve import handling in CodeEnumWriter

CHANGELOG.md, src/Kiota.Builder/Writers/CSharp/CodeClassDeclarationWriter.cs, src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs, src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs, src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
=> Change C# code generation to follow the usual C# code style

.github/workflows/project-auto-add.yml
Fixes https://github.com/microsoft/kiota/issues/4689
=> chore: Only run track issue if PR is not from a forked context

.vscode/launch.json, CHANGELOG.md, src/Kiota.Builder/PluginType.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Fixes https://github.com/microsoft/kiota/issues/4713
=> Renames `name_to_be_defined` plugin type to `apiplugin`

vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/kiotaInterop.ts, vscode/microsoft-kiota/src/steps.ts
Integrates changes in https://github.com/microsoft/kiota/pull/4777 to the VS code extension
=> [VsCode] Renames name_to_be_defined plugin type to apiplugin 

CHANGELOG.md, src/Kiota.Builder/Writers/TypeScript/TypeScriptRelativeImportManager.cs, tests/Kiota.Builder.Tests/Writers/TypeScriptRelativeImportManagerTests.cs
=> fix: TS imports are now es6 imports

scripts/update-versions.ps1, src/kiota/appsettings.json
Also updates settings file to be checked in with update.
Closes https://github.com/microsoft/kiota/issues/4825
=> Fixes release script

CHANGELOG.md, src/Kiota.Builder/Writers/CSharp/CodeClassDeclarationWriter.cs, tests/Kiota.Builder.Tests/Writers/CSharp/CodeClassDeclarationWriterTests.cs
=> Implemented partial class model declarations.

src/kiota/Rpc/Server.cs
Fixes https://github.com/microsoft/kiota/issues/4869
=> Fixes unselected paths where no children operations exists

vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/workspaceTreeProvider.ts
=> fix: fixes workspace loading when vscode does not have a folder open

CHANGELOG.md, src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs
Fixes https://github.com/microsoft/kiota/issues/4957
=> Generates attribute after comment in enums

src/kiota/Rpc/IServer.cs, src/kiota/Rpc/Server.cs, vscode/microsoft-kiota/src/migrateFromLockFile.ts
Related to https://github.com/microsoft/kiota/issues/4548
=> Adds RPC server functionality for lockfile migration

CHANGELOG.md, src/Kiota.Builder/Plugins/Models/AppManifestModel.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
fixes #4974
follow up to #4937
=> fix: empty declarative copilots node

vscode/microsoft-kiota/src/openApiTreeProvider.ts
Fixes https://github.com/microsoft/kiota/issues/4830
=> Fix path matching when filtering in extension

vscode/microsoft-kiota/src/extension.ts
Closes https://github.com/microsoft/kiota/issues/4982
=> Fixes plugin generation check

CHANGELOG.md, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Fixes https://github.com/microsoft/kiota/issues/5019
=> Fixes file name and namespace sanitization

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiSettingsExtensions.cs, src/Kiota.Builder/OpenApiDocumentDownloadService.cs, src/Kiota.Builder/Plugins/OpenApiPluginWalker.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Fixes https://github.com/microsoft/kiota/issues/4962
=> Exclude the `x-openai-isConsequential` extension from plugin cleanup

.azure-pipelines/ci-build.yml
=> fix(ci): vscode release preparation cant find the files

tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
=> Validates #5083

.azure-pipelines/ci-build.yml
=> ci: upgrades esrp release configuration

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj
=> chore: release version bump

CHANGELOG.md, src/Kiota.Builder/Plugins/OpenApiPluginWalker.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Closes https://github.com/microsoft/kiota/issues/4945
=> Reverts response trimming.

src/Kiota.Builder/KiotaBuilder.cs
=> feat: adds additional information to logging for allOf errors

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> chore: bumps preview release number

.vscode/settings.json, CHANGELOG.md
=> doc: fixes multiple typos in the changelog

tests/Kiota.Tests/Kiota.Tests.csproj, tests/Kiota.Tests/KiotaHostTests.cs
=> fix: mock console output so it stops spamming the test results fix: missing asserts

CHANGELOG.md, src/kiota/KiotaClientCommands.cs
=> fix: shorthand for refresh option

vscode/microsoft-kiota/src/dependenciesViewProvider.ts, vscode/microsoft-kiota/src/enums.ts, vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/extensionSettings.ts, vscode/microsoft-kiota/src/generateClient.ts, vscode/microsoft-kiota/src/generatePlugin.ts, vscode/microsoft-kiota/src/kiotaInterop.ts, vscode/microsoft-kiota/src/steps.ts, vscode/microsoft-kiota/src/util.ts
Fixes https://github.com/microsoft/kiota/issues/5112
Closing https://github.com/microsoft/kiota/pull/5203 in favor of this.
=> skip predefined q&a when deeplinking

CHANGELOG.md
Add changelog entry for typescript composed types
=> fix: Add changelog entry for typescript composed types

CHANGELOG.md, src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs, tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
=> fix: names normalization collision

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> fix: wrong dependency for tasks analysis

src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
=> Add conversation starters to plugin manifest

CHANGELOG.md, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, src/kiota/Handlers/Plugin/AddHandler.cs, src/kiota/Handlers/Plugin/EditHandler.cs, src/kiota/Handlers/Plugin/GenerateHandler.cs, src/kiota/Rpc/Server.cs, tests/Kiota.Builder.Tests/KiotaBuilderTests.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs, vscode/microsoft-kiota/src/openApiTreeProvider.ts
Fixes  https://github.com/microsoft/kiota/issues/5300
=> path filtering validation

it/typescript/src/config/config.dev.ts, it/typescript/src/config/config.ts, src/Kiota.Builder/Configuration/StructuredMimeTypesCollection.cs, src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs, src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs, vscode/microsoft-kiota/src/steps.ts
=> chore: linting sonarcloud code defects

CHANGELOG.md, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
=> Fix: remove encoding from human name

CHANGELOG.md, vscode/microsoft-kiota/package.json
=> feat: vscode extension out of preview

vscode/microsoft-kiota/src/steps.ts, vscode/microsoft-kiota/src/util.ts, vscode/microsoft-kiota/src/utilities/temporary-folder.ts
Fixes #5387
Fixes #5401
Fixes #5217
Demo available here [FixRemoteUrlPastingSearch](https://microsoft.sharepoint-df.com/:v:/t/GraphTooling/EbdSVnpoVN9HklyIQcGsXdIB3mrXBWgINjaMvt55V9hJtg?e=gmvoR4)
=> Fix pasting remote url in search

vscode/microsoft-kiota/l10n/bundle.l10n.cs.json, vscode/microsoft-kiota/l10n/bundle.l10n.it.json, vscode/microsoft-kiota/l10n/bundle.l10n.pl.json, vscode/microsoft-kiota/l10n/bundle.l10n.sw.json, vscode/microsoft-kiota/l10n/bundle.l10n.zh-cn.json, vscode/microsoft-kiota/src/extension.ts
=> Change display message when plugin generation completes successfuly

src/Kiota.Builder/Kiota.Builder.csproj
created as draft as we're expecting another relase
=> chore: ugprades manifest dep

vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/openApiTreeProvider.ts
=> Task: Notify user of next step after loading an Open Api Description

vscode/microsoft-kiota/README.md
=> fix pointer to readme images to point to main blob

CHANGELOG.md, src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
fixes https://github.com/microsoft/kiota-typescript/issues/1381
=> fix: untype node erasable in typescript

src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Fixes https://github.com/microsoft/kiota/issues/5469
=> Fix odata.type key already exists error for MSgraph OAD

vscode/microsoft-kiota/src/commands/Command.ts
=> Task: create base command class

vscode/microsoft-kiota/src/commands/open-api-tree-view/addAllToSelectedEndpointsCommand.ts, vscode/microsoft-kiota/src/commands/open-api-tree-view/addToSelectedEndpointsCommand.ts, vscode/microsoft-kiota/src/commands/open-api-tree-view/removeAllFromSelectedEndpointsCommand.ts, vscode/microsoft-kiota/src/commands/open-api-tree-view/removeFromSelectedEndpointsCommand.ts, vscode/microsoft-kiota/src/extension.ts
Creates selection commands for the treeview. Operations supported in this PR:
- select all
- select one
- remove one
- remove all
=> Task: create tree view endpoint selection commands

vscode/microsoft-kiota/src/commands/open-api-tree-view/filterDescriptionCommand.ts, vscode/microsoft-kiota/src/extension.ts
Follows the new pattern to make a command
=> Task: create filter description command

vscode/microsoft-kiota/src/commands/open-api-tree-view/openDocumentationPageCommand.ts, vscode/microsoft-kiota/src/extension.ts
=> Task: create open documentation page command

CHANGELOG.md, vscode/microsoft-kiota/CHANGELOG.md
- bumps version for release 1.19.0
=> bumps version for release 1.19.0

vscode/microsoft-kiota/src/commands/openApidescription/searchOrOpenApiDescriptionCommand.ts, vscode/microsoft-kiota/src/providers/openApiTreeProvider.ts
=> Task: remove unnecessary select message

it/java/basic/pom.xml, it/java/gh/pom.xml, it/java/query-params/pom.xml
=> ci: upgrades java dependencies for integration tests

src/kiota/appsettings.json
related https://github.com/microsoft/kiota-python/pull/396
=> feat: adds bundle in dependencies entry

src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
=> chore: reduces allocs for path parameters sanitation

vscode/microsoft-kiota/src/providers/codelensProvider.ts
=> Task: rename Edit Paths to Select

src/kiota/kiota.csproj
related https://github.com/microsoft/vs-streamjsonrpc/issues/1093#issuecomment-2483289832
=> security: forces dependency version for message pack

vscode/microsoft-kiota/src/commands/closeDescriptionCommand.ts
=> Task: change close description to close from remove

.azure-pipelines/ci-build.yml
=> fix: removes download none instructions

.azure-pipelines/ci-build.yml
=> fix: wrong path to changelog

.azure-pipelines/ci-build.yml
=> ci: fixes paths for vscode publish

vscode/microsoft-kiota/src/commands/editPathsCommand.ts, vscode/microsoft-kiota/src/commands/openApidescription/searchOrOpenApiDescriptionCommand.ts, vscode/microsoft-kiota/src/providers/openApiTreeProvider.ts
=> Fix: enable correct buttons

.github/workflows/integration-tests.yml, it/go/basic/go.mod, it/go/go.mod
=> ci: bumps go install version due to outdated core packages

CHANGELOG.md
bumps version for release of 1.22.0
=>  bumps version for release of 1.22.0

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
bumps version for prerelease of 1.23.0
=> bumps version for prerelease of 1.23.0

vscode/microsoft-kiota/CHANGELOG.md, vscode/microsoft-kiota/package.json, vscode/microsoft-kiota/src/kiotaInterop/index.ts, vscode/microsoft-kiota/src/test/suite/commands/generateClientCommand.test.ts, vscode/microsoft-kiota/src/types/enums.ts, vscode/microsoft-kiota/src/types/extensionSettings.ts, vscode/microsoft-kiota/src/util.ts
=> feat: adds dart generation to extension

CHANGELOG.md
=> chore: adds missing changelog entry for net9 support

.azure-pipelines/ci-build.yml
=> ci: update subscription secrets location

src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs, tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
=> fix: missing parenthesis for byte array deserialization in TS

CHANGELOG.md, src/kiota/appsettings.json
closes https://github.com/microsoft/kiota-php/issues/21
part of https://github.com/microsoft/kiota/issues/4636
=> chore: Add PHP Bundle package to dependencies output

src/kiota/appsettings.json
=> Fix CLI default log level

tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
=> chore: update KiotaBuilderTests.cs

CHANGELOG.md, src/Kiota.Builder/Validation/InconsistentTypeFormatPair.cs, tests/Kiota.Builder.Tests/Validation/InconsistentTypeFormatPairTests.cs
=> fix: a bug where type and format pairs would show as unmatched with nullable

.github/workflows/build-vscode-extension.yml
We need to provide binaries for testing especially when the changes to the server are ahead of what is in production
=> Chore: bundle binaries

src/kiota/Rpc/AdaptiveCardInfo.cs, src/kiota/Rpc/AdaptiveCardMapper.cs, src/kiota/Rpc/PathItem.cs, src/kiota/Rpc/Server.cs, vscode/npm-package/integration_tests/integrationGetKiotaTree.spec.ts, vscode/npm-package/types.ts
Closes #6301 
Adds the Adaptive Card Information from the document
=> Task: add adaptivecard info

vscode/microsoft-kiota/src/kiotaInterop/connect.ts
Close stdin channel for graceful kill of child process
=> Close stdin channel for RPC in extension

src/Kiota.Builder/Configuration/GenerationConfiguration.cs, src/Kiota.Builder/OpenApiDocumentDownloadService.cs, src/kiota/Rpc/IServer.cs, src/kiota/Rpc/Server.cs, tests/Kiota.Builder.IntegrationTests/ModelWithNoServer.yml, tests/Kiota.Builder.Tests/FakeLogger.cs, tests/Kiota.Builder.Tests/OpenApiDocumentDownloadServiceTests.cs, vscode/npm-package/lib/getKiotaTree.ts, vscode/npm-package/tests/integration/integrationGetKiotaTree.spec.ts, vscode/npm-package/types.ts
=> Add flag to be able to apply kiota validation rules on getKiotaTree

CHANGELOG.md, src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj
=> Chore: bump version for release of version 1.25.1

.azure-pipelines/ci-build.yml
Adds a fix for the 1.25.1 release to enable deployment
A step to build the package was required before building the extension
=> Fix: Add build step to release pipeline

src/kiota/Rpc/PathItem.cs, src/kiota/Rpc/SecurityRequirementMapper.cs, src/kiota/Rpc/SecuritySchemeMapper.cs, src/kiota/Rpc/ShowResult.cs, tests/Kiota.Builder.IntegrationTests/ModelWithMultipleSecurity.yaml, vscode/npm-package/tests/integration/integrationGetKiotaTree.spec.ts
=> Fix getKiotaTree security mapping in npm package #6417

CHANGELOG.md, src/Kiota.Builder/Extensions/OpenApiResponsesExtensions.cs, src/Kiota.Builder/KiotaBuilder.cs, tests/Kiota.Builder.Tests/Extensions/OpenApiResponsesExtensionsTests.cs
=> ignore default response when finding media types.

src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.IntegrationTests/PluginModelWithSecurity.json, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs, vscode/npm-package/tests/integration/integrationGeneratePlugin.spec.ts
=> Align suffix for auth reference id for TTK integration

src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs, vscode/npm-package/tests/integration/integrationGeneratePlugin.spec.ts
=> Fix: oauth implicit flow should generate none authentication

src/Kiota.Builder/Kiota.Builder.csproj, src/Kiota.Builder/Plugins/AdaptiveCardTemplate.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, src/Kiota.Builder/Resources/AdaptiveCardTemplate.json, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
=> Task: add adaptive card template

src/Kiota.Builder/OpenApiExtensions/OpenApiAiAdaptiveCardExtension.cs, src/kiota/Rpc/AdaptiveCardInfo.cs, src/kiota/Rpc/AdaptiveCardMapper.cs, tests/Kiota.Builder.IntegrationTests/ModelWithAdaptiveCardExtension.yaml, tests/Kiota.Builder.IntegrationTests/ModelWithRefIdExtension.yaml, tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiAiAdaptiveCardExtensionTests.cs, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
=> Task: Add new card properties

vscode/npm-package/install.ts, vscode/npm-package/tests/integration/integrationInstall.spec.ts
=> Fix execute permissions on linux and osx

vscode/microsoft-kiota/src/commands/deleteWorkspaceItem/deleteWorkspaceItemCommand.ts, vscode/microsoft-kiota/src/commands/generate/generateClientCommand.ts, vscode/microsoft-kiota/src/commands/openApidescription/searchOrOpenApiDescriptionCommand.ts, vscode/microsoft-kiota/src/commands/regenerate/regenerate.service.ts, vscode/microsoft-kiota/src/extension.ts, vscode/microsoft-kiota/src/handlers/uriHandler.ts, vscode/microsoft-kiota/src/test/suite/commands/generateClientCommand.test.ts
This PR fixes an issue with a previous dependabot update of @vscode/extension-telemetry package
=> fix issue with new version of extension-telemetry

src/Kiota.Builder/OpenApiExtensions/OpenApiAiAdaptiveCardExtension.cs, src/Kiota.Builder/Plugins/PluginsGenerationService.cs, tests/Kiota.Builder.IntegrationTests/ModelWithAdaptiveCardExtension.yaml, tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs, vscode/npm-package/tests/integration/integrationGeneratePlugin.spec.ts
=> Support for adaptive card content for typespec scenario

vscode/npm-package/CONTRIBUTING.md
This PR adds a basic contributing documentation for the Kiota npm package to get started with the project.
=> Contributing documentation for npm package

CHANGELOG.md, src/Kiota.Builder/OpenApiDocumentDownloadService.cs, src/Kiota.Builder/WorkspaceManagement/WorkspaceManagementService.cs
=> fix: issue with lock migration and stream management

tests/Kiota.Builder.IntegrationTests/Kiota.Builder.IntegrationTests.csproj, tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj, tests/Kiota.Tests/Kiota.Tests.csproj
=> chore: upgrades dotnet test sdk dependencies

src/Kiota.Builder/Kiota.Builder.csproj, src/kiota/kiota.csproj, tests/Kiota.Builder.IntegrationTests/Kiota.Builder.IntegrationTests.csproj, tests/Kiota.Builder.Tests/Kiota.Builder.Tests.csproj, tests/Kiota.Tests/Kiota.Tests.csproj
=> chore: upgrades dotnet dependencies
