microsoft/kiota

- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
fixes #70 a bug where empty class names would make the generation fail
> - fixes #70 a bug where empty class names would make the generation fail

- .github/workflows/create-release.yml
- .github/workflows/docker.yml
- CHANGELOG.md
- Dockerfile
- README.md
- adds a workflow to automate github releases on tags - updates docker workflow to support nightly and releases - adds a changelog file - adds a description to the docker file
- updates readme to include a link to the releases page
Fixes #98
This pull request adds a workflow to create GitHub releases on tags
1. Make your changes
1. (optional) Update the csproj to bump the version number
1. Update the changelog
1. `git tag vX.X.X` && `git push --tags`
This will [create a release](https://github.com/microsoft/kiota/releases)
This PR also updates the docker workflow to publish multiple tags (nigthly on main, latest + version on tag) [see here](https://github.com/microsoft/kiota/packages/740417/versions)
Note applicable
> adds automatic github release on tag

- .github/workflows/dotnet-tool.yml
- CHANGELOG.md
- README.md
- src/kiota/kiota.csproj
- adds packing information for dotnet tool
- adds workflow to publish the dotnet tool
- adds install instructions for the dotnet tool
- temporary disables branch filters for dotnet tool to try the workflow
- fixes workflow name
- fixes nupkg path for publishing
- adds missing package information for github packages
- Revert "- temporary disables branch filters for dotnet tool to try the workflow"
fixes #123
no generation changes
> adds dotnet tool packaging for kiota

- CHANGELOG.md
- abstractions/dotnet/src/KiotaAbstractions.csproj
- abstractions/dotnet/src/RequestInfo.cs
- abstractions/java/lib/build.gradle
- abstractions/java/lib/src/main/java/com/microsoft/kiota/RequestInfo.java
- abstractions/typescript/package-lock.json
- abstractions/typescript/package.json
- abstractions/typescript/src/requestInfo.ts
- core/dotnet/nuget.config
- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeClassDeclarationWriter.cs
- src/Kiota.Builder/Writers/Java/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeClassDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
- updates generation to remove the json assumption from request body
- updates abstration library to remove the json assumption
- updates changelog
- updates samples reference
- fixes a bu g where dotnet abstractions would not build because of missing keyword
- fixes a bug where collections of primitive values would not have the proper type
- updates samples reference
- fixes a bug where a comma would be missing in java gen
- fixes a bug in java gen where importing the same symbol as the current class would make result fail
- updates sample reference
fixes #136
https://github.com/microsoft/kiota-samples/pull/19
> removes json assumption for request body

- README.md
- kiota.sln
- src/Kiota.Builder/KiotaBuilder.cs
- src/kiota/KiotaHost.cs
- src/kiota/Program.cs
- tests/Kiota.Tests/Kiota.Tests.csproj
- tests/Kiota.Tests/KiotaHostTests.cs
- adds validation for language, loglevel, namespace and class name parameters
- adds shorthand for loglevel and description parameters
- adds validation for path parameters
fixes #127
> adds input parameters validation

- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
> fixes a bug where a null schema would make the generation process derail

- CHANGELOG.md
- README.md
- src/Kiota.Builder/GenerationConfiguration.cs
- src/kiota/KiotaHost.cs
> Change default client name GraphClient => ApiClient

- .vscode/tasks.json
for some reason vs code on macos looks at the main task definition instead of going straight to the linux one. Moving the main task definition under windows fixes that issue
> - updates vs tasks to bring macos compatibility

- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
fixes #218 for a second time because of a casing issue. No changes to our generation results in our samples
> fixes an issue where a property with the class name would prevent compilation in CSharp

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeParameter.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodeIndexerWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodePropertyWriter.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodePropertyWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeIndexerWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodePropertyWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodePropertyWriterTests.cs
- switches to constuctors for request builders in dotnet
- request builder constructors for java
- adds support for request builders constructors for typescript
- updates unit test for request builders constructors
fixes #301
This pull request adds constructors to request builders so they:
- Encapsulate properties that don't need to be exposed to consumers
- Validate what's passed (and lead consummers to pass the required information should they choose to instantiate request builers)
- Have a simpler code-gen story when it comes to indexers and navigation properties
https://github.com/microsoft/kiota-samples/pull/135
> adds constructors to request builders

- generator/docker.md
context: we've been automatically migrated to the new container image registry platform which doesn't require authenticating anymore. Updating the instructions.
> - updates docker instructions as we've been migrated to ghcr.io

- abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
- authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClient.csproj
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
Closes #279 
This PR edits the project files of the following projects so that the `Microsoft.DotNet.PackageValidation` package may perform package validation when `dotnet build` is ran. This therefore means there is no need to edit pipelines as they already leverage the use of calling `dotnet build`.
- Microsoft.Kiota.Abstractions
- Microsoft.Kiota.Authentication.Azure
- Microsoft.Kiota.Http.HttpClient
- Microsoft.Kiota.Serialization.Json
For now, the `PackageValidationBaselineVersion` directive has been commented out(disabled) and will be enabled once we go live with a stable version of the packages to enable package validation to prevent breaking changes.
Related info
- https://devblogs.microsoft.com/dotnet/package-validation/
> Adds support for package validation on dotnet build

- http/dotnet/httpclient/.editorconfig
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.sln
- http/dotnet/httpclient/README.md
- http/dotnet/httpclient/src/HttpClientBuilder.cs
- http/dotnet/httpclient/src/HttpCore.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClient.csproj
This PR is purely cosmetic and does not alter any functionality in the code. It involves the following changes :-
- Adds any missing XML documentation for public methods/properties
- Adds the `<GenerateDocumentationFile>true</GenerateDocumentationFile>` attribute to the csproj file so that compiler warnings may be generated in the event the first condition above is not met.
- Adds a `.editorconfig` to the solution to help with consistent code styling
- Whitespace changes to move opening curly braces to new lines.
Related to https://github.com/microsoft/kiota/issues/358
> Add doc comments for HttpClient project for dotnet

- .github/workflows/http-dotnet-httpclient.yml
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpClientBuilderTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpCoreTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Microsoft.Kiota.Http.HttpClient.Tests.csproj
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/TestHttpMessageHandler.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.sln
- http/dotnet/httpclient/README.md
- http/dotnet/httpclient/src/HttpClientBuilder.cs
- http/dotnet/httpclient/src/HttpCore.cs
This PR is part of the work covered in #358
- Adds a unit test project for the HttpClient project for dotnet
- Updates the build pipeline to generate code coverage artifact
- Cleans up a missing XML comment in the HttpCore class
> Add test project for HttpClient project for dotnet

- .github/workflows/authentication-dotnet-azure.yml
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/AzureIdentityAuthenticationProviderTests.cs
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/Microsoft.Kiota.Authentication.Azure.Tests.csproj
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.sln
- authentication/dotnet/azure/README.md
This PR is part of the work covered in #358
- Adds a unit test project for the Authentication project for dotnet
- Updates the build pipeline to generate code coverage artifact
> Adds test project for Authentication project for dotnet

- .github/workflows/serialization-dotnet-json.yml
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeFactoryTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterFactoryTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Microsoft.Kiota.Serialization.Json.Tests.csproj
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.sln
- serialization/dotnet/json/README.md
- serialization/dotnet/json/src/JsonParseNode.cs
- serialization/dotnet/json/src/JsonSerializationWriter.cs
- serialization/java/json/lib/src/main/java/com/microsoft/kiota/serialization/JsonSerializationWriter.java
This PR is part of the work covered in #358. 
- Adds a unit test project for the Serialization project for dotnet
- Updates the build pipeline to generate code coverage artifact
It also fixes the following bugs with the `JsonSerializationWriter` where
- `null` properties in an object would be repeated in final serialized payload
- `IParsable` objects would fail in serialization due to the code trying to reflect properties of `AdditionalData` rather than using the object's serialization methods
> Adds test project for Serialization project

- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/CompressionHandlerTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RedirectHandlerTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RetryHandlerTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/MockCompressedContent.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/MockRedirectHandler.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Mocks/TestHttpMessageHandler.cs
- http/dotnet/httpclient/src/Extensions/HttpRequestMessageExtensions.cs
- http/dotnet/httpclient/src/HttpClientBuilder.cs
- http/dotnet/httpclient/src/HttpCore.cs
- http/dotnet/httpclient/src/Middleware/CompressionHandler.cs
- http/dotnet/httpclient/src/Middleware/Options/RedirectHandlerOption.cs
- http/dotnet/httpclient/src/Middleware/Options/RetryHandlerOption.cs
- http/dotnet/httpclient/src/Middleware/RedirectHandler.cs
- http/dotnet/httpclient/src/Middleware/RetryHandler.cs
- http/dotnet/httpclient/src/Properties/AssemblyInfo.cs
This PR covers part of the work outlined in https://github.com/microsoft/kiota/issues/360
It involves the addition of the following middlewares to the httpClient library.
-  redirect handler
-  compression handler
-  retry handler
> Add redirect,retry and compression handlers to HttpClient library for dotnet

- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpClientBuilderTests.cs
- http/dotnet/httpclient/src/HttpClientBuilder.cs
- http/dotnet/httpclient/src/HttpCore.cs
- http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/HttpCore.java
- http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpClientBuilder.java
This PR setups the ability to configure the default options of the default httpClient by adding the ability to pass in an instance `HttpMessageHandler` to be the final handler in the http pipeline.
This will give the users the ability to pass in a handler to configure the proxy or cookie authentication. 
Example using proxy
```cs
var proxy = new WebProxy("http://localhost:8888", false);
var finalHandler = HttpClientBuilder.GetDefaultHttpMessageHandler(proxy); // this returns a handler with the appropiate defaults 
var httpClient = HttpClientBuilder.Create(finalHandler );
```
This PR also
- removes the `authenticationProvider` parameter from the `HttpClientBuilder.Create()` and `HttpClientBuilder.CreateDefaultHandlers()`method as this is not being used in the pipeline. (Ref …
> Setup final handler for default httpClient

- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/ChaosHandlerTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/TelemetryHandlerTests.cs
- http/dotnet/httpclient/src/Middleware/ChaosHandler.cs
- http/dotnet/httpclient/src/Middleware/Options/ChaosHandlerOption.cs
- http/dotnet/httpclient/src/Middleware/Options/TelemetryHandlerOption.cs
- http/dotnet/httpclient/src/Middleware/TelemetryHandler.cs
This PR covers part of the work outlined in https://github.com/microsoft/kiota/issues/360
- Adds a Telemetry Handler that takes in as an option a function to configure requests to enrich it with telemetry information.
This will ideally be used by the core library by passing in the relevant configurator to sent telemetry information
- Adds a Chaos Handler to enable users to simulate error responses from API backends
- Adds tests to validate the items above.
> Add Chaos and Telemetry Handlers

- CHANGELOG.md
- src/Kiota.Builder/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes #622 a bug where root URL would not be parsed from the document

- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/QueryParametersBaseTests.cs
- abstractions/dotnet/src/QueryParametersBase.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/HttpCoreTests.cs
- http/dotnet/httpclient/src/HttpCore.cs
This PR closes #625.
It essentially fixes the reading of the QueryParameters Dictionary in the `RequestInformation` instance to cater for the various object types that could exist rather that simply calling `object.ToString()` method.
Tests have also been added to validate this.
> Fix for query parameter building in dotnet

- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClient.Tests/Middleware/RetryHandlerTests.cs
- http/dotnet/httpclient/src/Middleware/RetryHandler.cs
This PR makes an update to the retry handler to respect a possible date coming back in the Retry-After header.
In the event a date is returned, the handler will calculate the seconds to wait and wait until the time to send the request. In the event for some reason the date received is a time in the past, the retry handler will default to the exponential backoff logic.
Part of https://github.com/microsoft/kiota/issues/596 for .Net
> [Retry Handler] Respect retry-after: <date> in dotnet

- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
This PR closes #646
It adds an extra parameter to enable the addition of an exclusion list to disable the replacement of reserved names in certain codeElements.
This may come in handy if we know for example that a CodeElement will be capitalized in a case sensitive language and can be taken advantage of in other languages in the refiner stages as well
> Filter CodeElement type during replacement of reserved names

- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
This PR updates the CSharpRefiner to exclude the `CodeNamespace` and `CodeMethod` types when replacing names for reseved words to clean up the unneccessary `@` character appended to namespace names and type names appearing in source as they are already capitalized in the case sensitive language
Therefore, a namespace like 
`namespace ApiSdk.Applications.Item.CreatedOnBehalfOf.@Ref`
changes to 
`namespace ApiSdk.Applications.Item.CreatedOnBehalfOf.Ref`
Note: this change does not affect the compilation of the current code when using the full v1.0 description.
Related to https://github.com/microsoft/kiota/pull/657
> Exclude namespace and type declarations in reserved words replacement for dotnet

- abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
This PR extends support for the abstractions project to netstandard2.1
Other libs are updated via #826 to verify the builds first before merging.
> Update dotnet abstractions to netstandard

- CHANGELOG.md
- authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
- http/dotnet/httpclient/src/Extensions/HttpRequestMessageExtensions.cs
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- http/dotnet/httpclient/src/Middleware/CompressionHandler.cs
- http/dotnet/httpclient/src/Middleware/RedirectHandler.cs
- http/dotnet/httpclient/src/Middleware/RetryHandler.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEnum.cs
- serialization/dotnet/json/src/JsonSerializationWriter.cs
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
This PR updates the serialization, authentication and http client libraries to support netstandard
The PR involves relevant refactoring and adding tests to cover the changes and should be merged in after #825
> Update serialization, authentication and http libs to netstandard

- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- http/dotnet/httpclient/src/Middleware/CompressionHandler.cs
- http/dotnet/httpclient/src/Middleware/RedirectHandler.cs
- http/dotnet/httpclient/src/Middleware/RetryHandler.cs
Moving to netstandard2.1 results to the possibility that the `Content` property in a `HttpResponseMessage` can be null. 
This PR resolves this to prevent any issues brought about by using a runtime that isn't `net5.0`
> Fix for possible null content in a HttpResponseMessage

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/3
Related https://github.com/microsoft/OpenAPI.NET.OData/issues/122
No diff for the sample
> - fixes a bug where at signs in path would derail generation

- CHANGELOG.md
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
This PR closes #849 
It ensures headers are all passed to the final `HttpRequestMessage` by first trying to set them to the `HttpRequestMessage` and setting them to the content header if this first operation is not allowed. 
Tests have been added to reflect/validate this change.
> Fixes a bug where HttpContent headers failed to be added to the request in dotnet.

- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
This PR updates the `HttpClientRequestAdapter` interface in the dotnet http library to consume a CancellationToken parameter to be forwarded to the client to allow the cancelling of requests. 
This allows it to conform to the new `IRequestAdapter` interface in #874 and should be merged in after it.
Part of #868
> [Http] Add CancellationToken parameter in send methods in dotnet

- src/Kiota.Builder/CodeDOM/CodeParameter.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
This PR updates the generation of the SDK to pass in a cancellation token to the newly updated send methods created via #875.
Samples generation can be seen at https://github.com/microsoft/kiota-samples/pull/416
Closes #868
> [Generation] Add CancellationToken parameter in send methods in dotnet

- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Serialization/ParseNodeFactoryRegistryTests.cs
- abstractions/dotnet/src/IRequestAdapter.cs
- abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- src/Kiota.Builder/CodeDOM/CodeParameter.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
This PR updates the `IRequestAdapter` interface in the dotnet abstractions library to consume a `CancellationToken` parameter to be forwarded to the client to allow the cancelling of requests
Part of #868
> [Abstractions] Add CancellationToken parameter in send methods in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- Fixes #909 a bug in Go where reserved keywords for properties would be wrongly replaced
- fixes #900 a bug in Go where setters would be missing nil checks
https://github.com/microsoft/kiota-samples/pull/426
> Go reserved keywords fix and nil check fix

- src/Kiota.Builder/Refiners/GoRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
related to #910
no diff for the samples but that's because of the source description
related to https://github.com/microsoftgraph/msgraph-beta-sdk-go/pull/25
realted to https://github.com/microsoftgraph/msgraph-sdk-go/pull/39
> fixes a bug where reserved keyword replacement in go would miss some cases

- http/go/nethttp/middleware.go
- http/go/nethttp/pipeline.go
- http/go/nethttp/pipeline_test.go
- http/go/nethttp/redirect_handler.go
- http/go/nethttp/redirect_handler_test.go
- http/go/nethttp/retry_handler.go
- http/go/nethttp/retry_handler_test.go
When making an API call that goes down the
http/go/nethttp/pipeline.go Next()->middleware.Intercept()->Next() loop,
the pipeline.middlewareIndex variable keeps track to make sure the next
Intercept() call is made in the chain.
After all of them have done their work and the results are being
returned to the original API caller, the middlewareIndex is left at
non-zero, so subsequent calls down the pipeline.go path will fail to
make all the middleware.Intercept() calls as middlewareIndex is not less
than len(middlewares).
Add a defer so that the index gets reset to zero when exiting the
function call chain so that sequential passes down the pipeline chain
can behave like the very first call.
> reset middleware pipeline counter on exit

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeProperty.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeClassDeclarationWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- Fixes a bug where Java generation would fail because of empty usings
- Fixes a bug where Java and Go escaped model properties would not serialize properly
related https://github.com/microsoftgraph/msgraph-sdk-go/issues/46
Languages:
- Java : fixed.
- CSharp: not impacted as already using the serialization name and not using accessors.
- Go: fixed.
- Ruby: not fixed, other issues that need to be addressed (uses the field instead of the accessor in serialization/deserialization methods).
- TypeScript: not impacted as already using the serialization name and using a prefixed named for fields.
https://github.com/microsoft/kiota-samples/pull/433
> Fixes a bug where Java and Go escaped model properties would not serialize properly

- .github/workflows/authentication-dotnet-azure.yml
- .github/workflows/http-dotnet-httpclient.yml
- .github/workflows/serialization-dotnet-json.yml
- scripts/updateNugetCredentials.ps1
Reduces amount of code needed by the pipeline (PowerShell script `scripts/updateNugetCredentials.ps1` isn't needed anymore)
> Use dotnet cli to update nuget sources

- CHANGELOG.md
- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/QueryParametersBaseTests.cs
- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs
- abstractions/dotnet/src/Method.cs
- abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
- abstractions/dotnet/src/RequestInformation.cs
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/AzureIdentityAuthenticationProviderTests.cs
- authentication/dotnet/azure/src/Microsoft.Kiota.Authentication.Azure.csproj
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/Extensions/HttpRequestMessageExtensionsTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/Middleware/TelemetryHandlerTests.cs
- http/dotnet/httpclient/Microsoft.Kiota.Http.HttpClientLibrary.Tests/RequestAdapterTests.cs
- http/dotnet/httpclient/src/Extensions/HttpRequestMessageExtensions.cs
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
This PR closes #940 
Samples generation available at https://github.com/microsoft/kiota-samples/pull/442
Changes include
- rename the enum to Method
- update abstractions and http libs
- update the usings added by the CSharp refiner
- update the code method writer to use the new name
- update tests accordingly
TODO
> Rename HttpMethod in dotnet

- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
- serialization/dotnet/json/src/JsonParseNode.cs
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
This PR fixes a couple of issue with regards to serialization in the dotnet serialization library.
Changes include.
- Changes `JsonParseNode.GetDateTimeOffset` to not call `JsonElement.GetDateTimeOffset` directly as `JsonElement.GetDateTimeOffset` is super strict and fails on variant dateTimeOffsets. Ref [here](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support).
- Allows `JsonValueKind.Null` json types to be processed on deserialization to at least allow unknown null properties to be added to the additionalData.
> Serialization fixes in dotnet

- http/go/nethttp/pipeline.go
- http/go/nethttp/pipeline_test.go
this pull request adds a GetDefaultTransport function to allow consumers to get the transport as it is configured for the kiota client (with default things like timeouts, and other configurations). This method clones the default transport provided by the Go runtime.
It also remove the inheritance of the custom transport from transport to avoid having two references (middleware), and provides a methods to configure the client with a third party transport should the consumer need to customize the transport used by the client.
> - adds support for providing a custom transport under the middleware transport in go

- .github/workflows/http-php-guzzle.yml
- http/php/guzzle/.editorconfig
- http/php/guzzle/.gitattributes
- http/php/guzzle/.gitignore
- http/php/guzzle/README.md
- http/php/guzzle/composer.json
- http/php/guzzle/phpstan.neon
- http/php/guzzle/phpunit.xml
- http/php/guzzle/src/Middleware/KiotaMiddleware.php
- http/php/guzzle/src/Middleware/Options/RetryOption.php
- http/php/guzzle/src/Middleware/RetryHandler.php
- http/php/guzzle/tests/Middleware/RetryHandlerTest.php
- Initialises PHP's HTTP Core package
- Implements a default RetryHandler that plugs into Guzzle's middleware pipeline
Pending for PR to be ready:
Addresses #596 
Part of #364
> Add PHP RetryHandler

- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
- serialization/dotnet/json/src/JsonParseNode.cs
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
This PR fixes an issue created by changes in #997.
#997 Removed the filter that prevented json elements of kind `JsonValueKind.Null` from being processed during deserialization to enable null elements to be placed in the additional data. 
This fix had the side effect of creating paths where we could call functions like `GetDouble`, `GetDateTimeOffset` etc when the element kind is JsonValueKind.Null if the element has a matching field deserializer. This leads to the throwing of an InvalidOperation exception as opposed to just letting the value be null.
This PR fixes this side effect by adding the filter back but only when we have a match of the element key in the field deserializers so that we can still have the elements being added to the additionalData when there is no match.
> Fix deserialization of null values in dotnet.

- CHANGELOG.md
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
- serialization/dotnet/json/src/JsonParseNode.cs
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
This PR 
- Fixes the `GetEnumValue` to return null when the enum value is empty as the return type is nullable yet an enum is not.
- Replaces the use of `Enum.Parse` with `Enum.TryParse` in order to be able to return a null default value rather than throwing an ArgumentException when an unknown Enum member is parsed. This is important as an API could be updated with a new Enum member and the user would experience breaking (exception throwing) code till he updates the library with a version that has the new Enum member included.
> Fix Argument Exception on unknown Enum value

- http/php/guzzle/composer.json
- http/php/guzzle/src/Middleware/CompressionHandler.php
- http/php/guzzle/src/Middleware/KiotaMiddleware.php
- http/php/guzzle/src/Middleware/Options/CompressionOption.php
- http/php/guzzle/tests/Middleware/CompressionHandlerTest.php
This implementation:
- allows the customer to provide callbacks to allow support for other algorithms e.g. `br` which has no built-in PHP implementation or well supported package on Packagist. Using it would require a customer to install a platform dependency alongside their PHP setup
- provides GZIP and DEFLATE implementations
- supports GZIP as the default
- allows chaining of multiple compression algorithms
part of #364, #598
> PHP - Compression Handler

- http/php/guzzle/src/Middleware/ChaosHandler.php
- http/php/guzzle/src/Middleware/KiotaMiddleware.php
- http/php/guzzle/src/Middleware/Options/ChaosOption.php
- http/php/guzzle/src/Middleware/Options/TelemetryOption.php
- http/php/guzzle/src/Middleware/RetryHandler.php
- http/php/guzzle/src/Middleware/TelemetryHandler.php
- http/php/guzzle/tests/Middleware/ChaosHandlerTest.php
- http/php/guzzle/tests/Middleware/CompressionHandlerTest.php
- http/php/guzzle/tests/Middleware/TelemetryHandlerTest.php
Generic Telemetry & Chaos Handler implementations
Guzzle's built in [MockHandler](https://docs.guzzlephp.org/en/stable/testing.html#mock-handler) handles "Manual mode" scenarios defined by [Chaos Handler design spec](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/ChaosHandler.md). The PHP Chaos Handler will only handle "random mode" scenarios.
part of #364
> PHP - Telemetry & Chaos Handlers

- abstractions/dotnet/src/Date.cs
- abstractions/dotnet/src/Microsoft.Kiota.Abstractions.csproj
- abstractions/dotnet/src/Time.cs
- abstractions/dotnet/src/serialization/IParseNode.cs
- abstractions/dotnet/src/serialization/ISerializationWriter.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonParseNodeTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/JsonSerializationWriterTests.cs
- serialization/dotnet/json/Microsoft.Kiota.Serialization.Json.Tests/Mocks/TestEntity.cs
- serialization/dotnet/json/src/JsonParseNode.cs
- serialization/dotnet/json/src/JsonSerializationWriter.cs
- serialization/dotnet/json/src/Microsoft.Kiota.Serialization.Json.csproj
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
This PR is part of #1004 
It covers dotnet changes needed to add support for date-only, time-only and duration in Kiota.
Changes involve 
- Adding the `Date` and `Time` types as the types from system are only available in dotnet 6. 
- Duration instances are represented with the `TimeSpan` type.
- Adding relevant serialization methods to the abstractions and serialization packages.
- Tests updated/added to cover the scenarios.
Sample generation of this using the full v1 description can be previewed [here](https://github.com/andrueastman/KiotaSdk/commit/476d19c2ee582be1cdb4797c1ecf9825c7667afa).
> [Dotnet] adds support for date-only, time-only and duration in Kiota

- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
- abstractions/dotnet/src/authentication/AnonymousAuthenticationProvider.cs
- abstractions/dotnet/src/authentication/BaseBearerTokenAuthenticationProvider.cs
- abstractions/dotnet/src/authentication/IAccessTokenProvider.cs
- abstractions/dotnet/src/authentication/IAuthenticationProvider.cs
- abstractions/go/authentication/access_token_provider.go
- abstractions/go/authentication/base_bearer_token_authentication_provider.go
- abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AccessTokenProvider.java
- abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/BaseBearerTokenAuthenticationProvider.java
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/AzureIdentityAuthenticationProviderTests.cs
- authentication/dotnet/azure/src/AzureIdentityAccessTokenProvider.cs
- authentication/dotnet/azure/src/AzureIdentityAuthenticationProvider.cs
- authentication/go/azure/azure_identity_access_token_provider.go
- authentication/go/azure/azure_identity_authentication_provider.go
- authentication/java/azure/lib/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAccessTokenProvider.java
- authentication/java/azure/lib/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAuthenticationProvider.java
- docs/extending/authentication.md
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
completion of #1039
CC @Ndiritu @SilasKenneth when you move on to implementing azure authentication provider for PHP, and to update your abstractions as well.
> splits authentication and access token interfaces for go, java, dotnet and docs

- CHANGELOG.md
- abstractions/typescript/package-lock.json
- abstractions/typescript/package.json
- abstractions/typescript/src/requestInformation.ts
- http/typescript/fetch/package-lock.json
- http/typescript/fetch/package.json
- http/typescript/fetch/src/fetchRequestAdapter.ts
fixes #773 
1. TS fails to compile when a node URL is set to a browser URL type. This is a problem with TS. 
2. Setting URL to string as suggested by @darrelmiller. This simplifies the problem to manage the URL object in TS isomorphically.
> TS - URL to string

- CHANGELOG.md
- abstractions/dotnet/Microsoft.Kiota.Abstractions.Tests/Authentication/AuthenticationTests.cs
- abstractions/dotnet/src/authentication/AllowedHostsValidator.cs
- abstractions/dotnet/src/authentication/BaseBearerTokenAuthenticationProvider.cs
- abstractions/dotnet/src/authentication/IAccessTokenProvider.cs
- abstractions/go/authentication/access_token_provider.go
- abstractions/go/authentication/allowed_hosts_validator.go
- abstractions/go/authentication/base_bearer_token_authentication_provider.go
- abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AccessTokenProvider.java
- abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/AllowedHostsValidator.java
- abstractions/java/lib/src/main/java/com/microsoft/kiota/authentication/BaseBearerTokenAuthenticationProvider.java
- abstractions/typescript/src/authentication/accessTokenProvider.ts
- abstractions/typescript/src/authentication/allowedHostsValidator.ts
- abstractions/typescript/src/authentication/baseBearerTokenAuthenticationProvider.ts
- abstractions/typescript/src/authentication/index.ts
- abstractions/typescript/src/authentication/validateProtocol.ts
- authentication/dotnet/azure/Microsoft.Kiota.Authentication.Azure.Tests/AzureIdentityAuthenticationProviderTests.cs
- authentication/dotnet/azure/src/AzureIdentityAccessTokenProvider.cs
- authentication/dotnet/azure/src/AzureIdentityAuthenticationProvider.cs
- authentication/go/azure/azure_identity_access_token_provider.go
- authentication/go/azure/azure_identity_access_token_provider_test.go
- authentication/go/azure/azure_identity_authentication_provider.go
- authentication/java/azure/lib/.classpath
- authentication/java/azure/lib/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAccessTokenProvider.java
- authentication/java/azure/lib/src/main/java/com/microsoft/kiota/authentication/AzureIdentityAuthenticationProvider.java
- authentication/typescript/azure/src/azureIdentityAccessTokenProvider.ts
- authentication/typescript/azure/src/azureIdentityAuthenticationProvider.ts
- authentication/typescript/azure/test/azureIdentityAuthenticationTest.d.ts
- docs/extending/authentication.md
> adds host and scheme validation for access token providers

- abstractions/go/authentication/allowed_hosts_validator.go
- abstractions/go/authentication/allowed_hosts_validator_test.go
- authentication/go/azure/azure_identity_access_token_provider_test.go
- http/dotnet/httpclient/src/HttpClientRequestAdapter.cs
- http/dotnet/httpclient/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj
- http/go/nethttp/nethttp_request_adapter.go
- http/java/okhttp/lib/build.gradle
- http/java/okhttp/lib/src/main/java/com/microsoft/kiota/http/OkHttpRequestAdapter.java
- http/typescript/fetch/package-lock.json
- http/typescript/fetch/package.json
- http/typescript/fetch/src/fetchRequestAdapter.ts
- fixes a bug where go host validator would not be using the right method for hostname
- fixes a bug where request adapters would attempt to auth the request before setting the base url
- bumps versions for http libraries
no generation diff
no changelog entry since we just merged #1051
CC @Ndiritu for PHP implementation of http provider which might be impacted by this.
> fixes a bug where host and scheme validation would fail because of sequence of calls

- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
the type of headers in request information is `Record<string, string>` but it's `Record<string, string> | undefined` for the fluent api parameter which caused the transpiler to complain, this adds a undefined check before assigning.
> - fixes an issue where typescript headers would return compile errors

- abstractions/typescript/src/authentication/validateProtocol.ts
because of the way the condition was structured when running on a node environment the runtime tried to access the window object, which doesn't exist/
> - fixes an error where validate protocol would read window on node

- src/Kiota.Builder/KiotaBuilder.cs
This PR closes #1198 
Changes include
1. Evaluate the `targetNamespace` in the event an array has a reference schema (similar to how objects are handled). 
This fixes the duplication of types models in other namespaces and now will be placed in the namespace as expected from the schema. (E.g we would see `Message` model in the default models namespace and in a function/action namespace and this would type collisions if someone imported both)
2. Eliminate the explicit setting of the `checkInAllNameSpaces` to true when calling `AddModelDeclarationIfDoesntExit` as this produces flaky generation results. 
This has now been limited to scenarios when the schema in use does not have a reference (essentially when the schema is inline?). This is because the namespace resolution seems solid and the …
> Fix for type collisions for types referenced from OData actions

- cli/commons/src/Microsoft.Kiota.Cli.Commons/IO/IOutputFormatter.cs
- cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
In the CLI, there's a limit of 16 options or arguments in the SetHandler action. Adding any additional options requires custom types and binders. To simplify the generation, the console argument that's added to each handler action can be removed for now.
See https://github.com/dotnet/command-line-api/issues/1537
> Remove unused Console parameter

- CHANGELOG.md
- cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/Binding/CollectionBindingTests.cs
- cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/Binding/TypeBindingTests.cs
- cli/commons/src/Microsoft.Kiota.Cli.Commons.Tests/Microsoft.Kiota.Cli.Commons.Tests.csproj
- cli/commons/src/Microsoft.Kiota.Cli.Commons/Binding/CollectionBinding.cs
- cli/commons/src/Microsoft.Kiota.Cli.Commons/Binding/TypeBinding.cs
- cli/commons/src/Microsoft.Kiota.Cli.Commons/Microsoft.Kiota.Cli.Commons.csproj
- src/Kiota.Builder/Refiners/ShellRefiner.cs
- src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
New generated code will look like:
```csharp
command.SetHandler(async (object[] parameters) => {
var userId = (string) parameters[0];
var top = (int?) parameters[1];
var skip = (int?) parameters[2];
...
var cancellationToken = (CancellationToken) parameters[10];
...
}, new CollectionBinding(userIdOption, topOption, skipOption...new TypeBinding(typeof(CancellationToken))));
```
> Update command handler to allow handling more than 16 options

- CHANGELOG.md
- src/Kiota.Builder/PathSegmenters/JavaPathSegementer.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
By convention, Java namespaces are lower-cased. Also, directory structure follows the namespace, and is case-sensitive. This fixes enforces lower case for namespaces and directory names.
Fixes #1267
> Fix for Java directory and namespace casing

- CHANGELOG.md
- serialization/typescript/json/src/jsonParseNode.ts
Introducing fix for error:
`encountered an unknown type during deserialization string`
> TS- Bugfix in json parseNode checking for type string

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
This PR fixes an edge case where there would be missing discriminator functions for model types created from union type wrappers.
As the union type wrappers are created in the refiner stages, these models would miss out on getting the relevant functions resulting to unresolved references.
Generation for the same has been tested with the full v1/beta description and can be checked here.
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=69106&view=logs&j=09be00da-8404-5a6e-d496-3b97eba1ba4f
Generation changes can be previewed at 
V1 - https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1268
Beta - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/408
> Fix missing discriminator functions union type wrappers

- CHANGELOG.md
- src/Kiota.Builder/CodeRenderer.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/kiota/KiotaHost.cs
- tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #1269
- passes the cancellation token all the way from the system.command line host to async APIs to avoid getting task cancelled exceptions when users press ctrl + c
- formats all the logging to use templates instead of doing string interpolation so logging APIs can do sampling and metrics
- adds a global try catch/log to log a proper error message instead of throwing an exception to the user.
@MaggieKimani1 you might want to replicate this onto hidi.
> better error display

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/ProprietableBlock.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/Go/CodeProprietableBlockDeclarationWriter.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
This PR closes #1354 and closes #1356
In summary, changes include :- 
- Ensure property names are Camel Cased when added to the code DOM to eliminate the possibility of `-` characters to cause compile time issues.
- Add a default response return type of type `string` for content type `text/plain`
- Fix for `NullReferenceException` [CodeProprietableBlockDeclarationWriter.cs](https://github.com/microsoft/kiota/pull/1355/files#diff-23fe0448659d8a316d18d89ca908098bed5b2ec82c9139c35b2ad6cca4ad23e5) when the namespace is null in Go
- Refactored the `GetExistingDeclaration` method to first search for the declaration in the target namespace before searching the root model namespace to avoid incorrect type resolution.
- `ProprietableBlockDeclaration` to use a `ConcurrentDictionary` for holding the …
> Generation fixes in Dotnet and Go

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeBlock.cs
- src/Kiota.Builder/CodeDOM/CodeClass.cs
- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/CodeDOM/CodeNamespace.cs
- src/Kiota.Builder/CodeDOM/ProprietableBlock.cs
- src/Kiota.Builder/CodeElementOrderComparerWithExternalMethods.cs
- src/Kiota.Builder/CodeParameterOrderComparer.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeBlockTests.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeMethodTests.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeNamespaceTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
- Fixed indeterministic parameters ordering
- Fixed indeterministic error mappings ordering
- Fixed indeterministic discriminator mapping ordering
- Fixed race condition when removing child items leading to erratic code generation results
- Replaced models namespaces flattening by circular properties trimming in Go
- Fixed a bug where inherited interfaces would be missing imports in Go
- Fixed a bug where inherited interfaces would be missing imports for the parent
no generation diff for samples
> - fixes a bug where implements generation would not be deterministic

- CHANGELOG.md
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CSharpReservedNamesProvider.cs
- src/Kiota.Builder/Refiners/CSharpReservedTypesProvider.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
This PR closes #1437 
Changes include: - 
- Adds support for escaping only types by taking advantage of the existing `ReplaceReservedNames` function
- Adds support for escaping strings used in XML comments to reduce likelihood of warning in generates SDKs
- Fix unnecessary of escaping Enum members in dotnet as they will be capitalized
- Fixed unnecessary use of fully qualified type names in Dotnet as the new  function `DoesTypeExistsInTargetAncestorNamespace` would also match types in the same namespace.
- Fixed CSharp and Shell tests that had set up orphaned instances of `CodeClass` which led to test failures.
Successful generation in dotnet can be verified at the link below
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=71393&view=results
> Fix ambiguous types in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes a bug where line returns in descriptions could break the generated code

- .vscode/launch.json
- CHANGELOG.md
- Dockerfile
- docs/using.md
- src/kiota/KiotaHost.cs
- src/kiota/kiota.csproj
This bundles a couple of tweaks and improvements to the CLI:
- Changed the order of the parameters as they are listed in the CLI help. In particular, `--openapi` is the first parameter.
- Removed the default value of `--openapi` and made it a required parameter instead. It's very unlikely that a file named `openapi.yml` exists. By making it a required parameter, users will get a better error message when they don't pass `--openapi` and the file does not exist.
- Added more descriptive argument help names. E.g. instead of `--output <output>`, `--output <path>` is shown in the CLI help.
- Changed parameter alias `-co` to `--co` in order to be consistent with the other aliases `--ll` and `--ds`.
- Added a program description `OpenAPI-based HTTP Client SDK code generator` which is shown in …
> Revise command-line interface

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
Closes #1576 
This would block generation of SDKs using the latest openApi document from metadata repository for Microsoft graph.
Changes include:
- Fixes a bug where null reference exception would be thrown when trying to lookup type inheritance on discriminators.
- Fixes incorrectly generated send method if the path return type is an Enum
- Eliminates the searching of models across all namespaces. This should hopefully result in better performance of the generator when generating CodeDom and eliminates the possibility of incorrect lookup of models in the incorrect namespace. Since we generate model namespaces in a consistent fashion, we can correctly obtain the type since we will know beforehand where the type would be.
Generation run can viewed here …
> Fix for null reference exception and incorrect send methods for enums in dotnet 

- authentication/php/phpleague/src/PhpLeagueAccessTokenProvider.php
- authentication/php/phpleague/tests/PhpLeagueAccessTokenProviderTest.php
Passing multiple scopes would fail due to wrong concatenation of scopes with a `,` instead of `[space]`
closes https://github.com/microsoftgraph/msgraph-sdk-php-core/issues/61
> PHP - Fix failing Auth with multiple scopes

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
This PR closes #1586 
In the event we initialize the `SerializationName` property for the type `CodeParameterKind.Path` we default to the name so as to avoid situations of empty key values in the generated path parameter dictionary in the respective request builder.
> Fixes a bug with empty key values for path parameters

- CHANGELOG.md
- docs/using.md
- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- src/kiota/KiotaHost.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiOperationExtensionsTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #134
no generation diff with our metadata
> aligns request body and response schema election

- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This PR closes #1554 
The PR updates the discriminator mapping to be consistent with property lookup to also look for discriminator mappings in the last `AllOf` schema that is an object in the description.
Tests have also been updated to cover this scenario.
> Fix for missing discriminator mappings and models in generated code

- serialization/java/text/lib/build.gradle
Version 1.0.10 didn't build the package correctly, so Gradle can't load it from the private package feed. Per Vincent, bumping version so a new build can be generated.
> Bump version of com.microsoft.kiota.serialization:kiota-serialization-text

- serialization/java/json/lib/build.gradle
Version 1.0.11 didn't build the package correctly, so Gradle can't load it from the private package feed. Per Vincent, bumping version so a new build can be generated. Bumping to 1.0.17 because the metadata in the private feed has 1.0.16 as the latest version.
> Bump version of kiota-serialization-json

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
Static analysis in Graph service libraries fails due to PHPDoc types in Request Config classes not being explicit enough.
Sample diff:
https://github.com/microsoft/kiota-samples/pull/807/files#diff-adb5363858815f105dbf0ff26b1e2443afa69693a28c2c4602cda1685083d676R10
> Update PHPDoc types in request config classes

- docs/get-started/index.md
Fix the `Using the Kiota tool` link on the `Get started` page.
> Docs: Fix Using link on Get started page

- CHANGELOG.md
- src/Kiota.Builder/Exceptions/InvalidSchemaException.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/Exceptions/InvalidSchemaExceptionTests.cs
fixes #1718
The generator (in release builds) will now return the following error
> crit: Kiota.Builder.KiotaBuilder[0] error generating the SDK: One or more errors occurred. (Error creating property ProviderIds for model BaseItemDto in API path \GameGenres, the schema is invalid.)
which is much more actionable than the previous error message
> crit: Kiota.Builder.KiotaBuilder[0] error generating the SDK: One or more errors occurred. (un handled case, might be object type or array type)
> - adds a more explicit message for invalid schema

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
regression from #1530, no changes to our samples
> fixes a bug where collections types would generate invalid return types in CSharp

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - Fixes a bug where a nullable entry in anyOf schemas would create unnecessary composed types.

- CHANGELOG.md
- docs/using.md
- src/Kiota.Builder/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/kiota/KiotaCommandHandler.cs
- src/kiota/KiotaHost.cs
Resolves #1573
- new command line arg: `--additional-data [true|false]`  (or `-ad [true|false]`). Default is `true` (which is the current status quo).
Here's an example which does NOT add the additional data to any generated models:
```
--openapi https://petstore.swagger.io/v2/swagger.json --additional-data false --language csharp -o PetshopClient -c ApiClient --log-level information --clean-output true
```
> ☄ New command line arg: additional-data

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
This PR fixes the dateTime formats used in the pathParameters in Go to default to ISO 8601. As the dateTimes are converted to strings before being placed in the pathParameters collection as seen in https://github.com/microsoft/kiota-abstractions-go/pull/24, the changes are made to the generator.
Generation changes can be previewed on this commit https://github.com/microsoftgraph/msgraph-sdk-go/commit/1f844053bbc1afe7008f2bd4ff23323b3253e042
> Use ISO 8601 date formats for dateTime in Go

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/ShellRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
This PR closes #1799
It resolves compile issues after the introduction of the `Microsoft.Graph.IdentityGovernance` namespace to the beta metadata.
As the namespace introduces a `task` navigation property, it results to conflict between the generated namespace name and generated Types. 
Changes include: -
- Fixes an issue where if namespaces are renamed, the corresponding using statements referencing the namespaces were not renamed
- Adds the `ReplaceReservedNamespaceTypeNames` function to allow for namespaces to replaced with a different format than models as a namespace `Microsoft.Graph.IdentitityGovernance.TaskObject` conflict with trying to reference a type called `TaskObject` as the compiler would not know whether to reference the type or the Namespace. 
Generation run - …
> [Dotnet] Fix for imports/usings reserved names replacement

- src/Kiota.Builder/Refiners/JavaRefiner.cs
AddDiscriminatorMappingsUsingsToParentClasses has a parameter, 'AddUsings', which was previously set to false. This caused issues when mapping large quantities of entities in the Entity model class of the V1 and Beta SDK's, more specifically those within the sub-namespaces in the models package. By changing this condition we have added the appropriate import statements so that our generated SDK's will compile.
> Switch AddUsings condition to True for Java Generation

- CHANGELOG.md
- src/Kiota.Builder/CodeParameterOrderComparer.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/CodeProprietableBlockDeclarationWriter.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Refactor to Pass a Context object to all executor methods in GO. Resolves : https://github.com/microsoftgraph/msgraph-sdk-go/issues/176
- This PR also removes method overloads for in GO sdk generation and only retains the primary HTTP executor method in the builder.
Example in Kiota-Sample OutPut  https://github.com/microsoft/kiota-samples/pull/950/
Output
```go
func (m *ServiceHealthIssueItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *ServiceHealthIssueItemRequestBuilderDeleteRequestConfiguration)(error) {
requestInfo, err := m.CreateDeleteRequestInformationWithRequestConfiguration(requestConfiguration);
if err != nil {
return err
}
errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
"4XX": …
```
> Adds context to go code writer

- docs/get-started/ruby.md
The auth package hyperlink is outdated, as it led to the previous auth folder. 
Also, the formatting on one of the blocks looked fine on GitHub, but weird on the website, so I tried to change the formatting a little, so it looks more normal on the website.
> Small Update to the Auth Package Hyperlink

- CHANGELOG.md
- src/Kiota.Builder/BaseCodeParameterOrderComparer.cs
- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/GoCodeParameterOrderComparer.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeParameterOrderComparerTests.cs
This PR closes #1822 
It fixes a bug where the parameter orders was changed placing the CancellationToken before the RequestConfiguration.
In summary, changes include:
- Renames `CodeParameterOrderComparer` to `BaseCodeParameterOrderComparer` to create a derived `GoCodeParameterOrderComparer` to allow Go to have custom order.
- Cleans up the `PythonCodeParameterOrderComparer` to also derived from the new `BaseCodeParameterOrderComparer`
- Adds test to validate the refactoring.
> Fix for parameter orders in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Do not lowercase first letter of property name for serialization and deserialization.
Reference issue [#1830](https://github.com/microsoft/kiota/issues/1830)
> Use property names of definition without modifying first character

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This PR fixes a regression at https://github.com/microsoft/kiota/blob/31c07999b03055071664d38f75aca60b81a6e068/src/Kiota.Builder/KiotaBuilder.cs#L1074
In the event an`AllOf` collection has 2 items where the first item matches the `allOfEvaluatorForMappings` criteria but the second/last does not, the first item is the schema passed to the recursive call leading to potential corruption of the codeDom(as the derived class/schema is ignored/left out).
This PR therefore adds a check to verify the last item is indeed the one being matched so that the other branches maybe used to correctly evaluate the scenario described above.
This is because it would be appropriate to either use the Schema Reference of the parent schema containing the `AllOf` collection if present or simply return an empty …
> Fixes incorrect schema selection when calling `GetDiscriminatorMappings`

- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This PR closes #1845 
It fixes a bug where a property that is a collection of an Enum would be incorrectly evaluated to the `string` type in the CodeDom. 
This led to some missing models (as the enum would potentially not be referenced) as well as models having the `List<string>` leading to loss of the strongly typed enum.
In summary the changes include: -
- Update the `CreateCollectionModelDeclaration` to check if the schema contains an `Enum` to allow the `CreateModelDeclarations` method to do its job.
- Add tests to validate the scenarios
Generation changes can be viewed at the links below.
- https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/commit/9ef8f0c4de1fb5a932350a0c381472e64a7f9d60
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/a1be18b674111c36d39047d6c9005 …
> Fix for Enum collections types described as string collections 

- CHANGELOG.md
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Utilizes generic helper methods introduced in https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/126
Reduces code generated for methods that can use utility  generic methods 
Sample PR with the generated code https://github.com/microsoft/kiota-samples/pull/1045
> Generate go de-serializers with generic helpers

- docs/index.md
The intro page has been re-written to change the focus from helping API providers create SDKs to helping API consumers have a consistent experience when calling different HTTP APIs.
Our hypothesis is that 60% of developers don't use SDKs because they don't want to have to keep learning new SDKs for every API they touch.  To solve that problem we either convince every API provider to use Kiota to generate their SDKs, or we convince API consumers to generate their own API clients.  The later is a significantly easier way to deliver value to customers.
The net side effect of consumers using Kiota to call APIs, is it potentially eliminates the need for API providers to ship SDKs. It's a win-win.
> Updated intro page to have a consumer focus

- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/KiotaSearcher.cs
- src/Kiota.Builder/Refiners/CSharpReservedNamesProvider.cs
- src/Kiota.Builder/Refiners/CSharpReservedTypesProvider.cs
- src/Kiota.Builder/SearchProviders/MSGraph/MsGraphSearchProvider.cs
- src/Kiota.Builder/SearchProviders/OpenApiSpec/OpenApiSpecSeachProvider.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Extensions/StringExtensionsTests.cs
This PR contains a bunch of minor performance and allocation improvements, such as specifying the known capacity in a `HashSet`'s constructor.
However it also contains a rewrite of the `ToSnakeCase` method, which reduces allocations by up to 14,5x and increases performance by up to 7,25x. I also added three unit tests, one of which does not pass in the current implementation.
> Performance improvements

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
This PR closes #1858 
Depends on 
- https://github.com/microsoft/kiota-abstractions-dotnet/pull/41
- https://github.com/microsoft/kiota-http-dotnet/pull/44
Changes include : 
- Update dotnet refiner to call `RemoveHandlerFromRequestBuilder` to remove responseHandler parameter
- Updates dotnet writer to not write the parameter to align to new `IRequestAdapter` interface.
> Moves ResponseHandler parameter in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
This PR is a follow up to #1901 
It fixes an edge case where a type that is similar to a file extension exists in the reference input file that would cause generation to fail. Example is `microsoft.graph.json`.
This PR updates the `GetClassName` function to apply the extension exclusions if we have more than one segment in the name.
> Follow up to #1901

- src/Kiota.Builder/Caching/DocumentCachingProvider.cs
- src/Kiota.Builder/Extensions/StringExtensions.cs
This PR prevents a possible StackOverflow exception by limiting the amount of memory allocated on the stack and falling back onto an array creation in the case of a string exceeding a certain length.
> Fix possible StackOverflow exception

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
> - fixes an issue where CSharp defensive programing would use string.IsNullOrEmpty for collections parameters

- .vscode/launch.json
- docs/using.md
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Lock/ILockManagementService.cs
- src/Kiota.Builder/Lock/KiotaLock.cs
- src/Kiota.Builder/Lock/KiotaLockComparer.cs
- src/Kiota.Builder/Lock/LockManagementService.cs
- src/Kiota.Web/Kiota.Web.csproj
- src/Kiota.Web/Pages/Generate.razor
- src/Kiota.Web/Pages/Generate.razor.css
- src/Kiota.Web/Pages/Update.fr.resx
- src/Kiota.Web/Pages/Update.razor
- src/Kiota.Web/Pages/Update.resx
- src/Kiota.Web/Shared/MainLayout.razor.css
- src/Kiota.Web/Shared/NavMenu.razor
- src/Kiota.Web/Shared/NavMenu.razor.css
- src/Kiota.Web/Shared/NavMenu.resx
- src/kiota/Handlers/BaseKiotaCommandHandler.cs
- src/kiota/Handlers/KiotaGenerationCommandHandler.cs
- src/kiota/Handlers/KiotaUpdateCommandHandler.cs
- src/kiota/KiotaHost.cs
- tests/Kiota.Builder.Tests/Configuration/GenerationConfigurationTests.cs
- tests/Kiota.Builder.Tests/Lock/KiotaLockTests.cs
- tests/Kiota.Builder.Tests/Lock/LockManagementServiceTests.cs
fixes #105
```json
{
"descriptionHash": "3F59399C45001D3E1D8D074403A9DAE966F993F54945B6D0E6F8413EE6D3EA56F9C419C2640D85418C567A9931D591B0B5B1FDA2778BE140B33A7305B83C1416",
"descriptionLocation": "https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/openApiDocs/v1.0/Mail.yml",
"lockFileVersion": "1.0.0",
"kiotaVersion": "0.6.0.0",
"clientClassName": "ApiClient",
"clientNamespaceName": "Graphdotnetv4",
"language": "CSharp",
"usesBackingStore": false,
"includeAdditionalData": true,
"serializers": [
"Microsoft.Kiota.Serialization.Json.JsonSerializationWriterFactory",
"Microsoft.Kiota.Serialization.Text.TextSerializationWriterFactory"
],
"deserializers": [
"Microsoft.Kiota.Serialization.Json.JsonParseNodeFactory",
"Microsoft.Kiota.Serialization.Text.TextParseNodeFactory" …
```
> - draft implementation of lock file

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
This PR closes https://github.com/microsoft/kiota/issues/1945
It fixes the placement of parameter comments in dotnet to be outside the summary tag to avoid generated warnings.
Samples have also been updated via https://github.com/microsoft/kiota-samples/pull/1173
> Fix parameter comment placement in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
- Validates support for Parsable collections in the request body
- Adds support for scalar values and collections of scalar values in request body
- Adds/Refactors tests for PHP method writers
closes https://github.com/microsoft/kiota/issues/1933
TODO:
> PHP - Add support for scalar types in request bodies

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Writers/LanguageWriter.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/PhpConventionService.cs
- src/Kiota.Builder/Writers/Php/PhpWriter.cs
- tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
This PR:
- Adds backing store logic to the `PHPRefiner` & writers
- Ensures stream property and additional data property getters return nullable types when backing store is enabled. Backing store can return null when a property hasn't changed since initialisation.
- Changes generated `serialize()` logic to use property getters
- Prevents adding setters for backing store properties
- Adds tests
Sample Generated Diffs (with backing store enabled)
https://github.com/microsoftgraph/msgraph-sdk-php/pull/1069
https://github.com/microsoftgraph/msgraph-beta-sdk-php/pull/114/
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/979
> PHP - Backing Store support

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodePropertyWriterTests.cs
> - fixes a bug where readonly properties would fail to deserialize for TypeScript.

- CHANGELOG.md
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
This is needed to take into consideration collections as return type, without propagating it the generated code won't compile.
> [java] Use the method signature type in the exception

- CHANGELOG.md
- abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/serialization/parse_node_factory_registry.rb
- abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/serialization/serialization_writer_factory_registry.rb
- abstractions/ruby/microsoft_kiota_abstractions/lib/microsoft_kiota_abstractions/version.rb
- abstractions/ruby/microsoft_kiota_abstractions/spec/parse_node_factory_mock.rb
- abstractions/ruby/microsoft_kiota_abstractions/spec/parse_node_factory_registry_spec.rb
- abstractions/ruby/microsoft_kiota_abstractions/spec/serialization_writer_factory_mock.rb
- abstractions/ruby/microsoft_kiota_abstractions/spec/serialization_writer_factory_registry_spec.rb
> - adds support for vendor specific serialization in Ruby

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Ruby/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeMethodWriterTests.cs
This PR closes https://github.com/microsoft/kiota/issues/2091
Changes include - 
- Ensure `CleanupSymbolName` is called for default values for Enums
- Skips adding the property name if the default value is being assigned to a composed type as the right type can be tricky to infer.
> Fixes default values for Enum with invalid characters

- src/Kiota.Builder/Refiners/CSharpRefiner.cs
Follow up to #2123
As `IDictionary.TryAdd` is only available in NetStandard 2.1 and above, this PR adds the `Microsoft.Kiota.Abstractions.Extensions` import to the ApiClient class to allow for successful builds in older clients.
> Follow up to set baseurl

- docs/configuration/index.md
- docs/extending/index.md
- src/kiota/Handlers/BaseKiotaCommandHandler.cs
- src/kiota/Handlers/KiotaGitHubDeviceLoginCommandHanlder.cs
- src/kiota/Handlers/KiotaInfoCommandHandler.cs
Currently, the output color is invisible while using a white terminal:
I'm proposing adding 2 options:
- swap the output color -> useful on terminals with light background
- disable completely the colors -> useful for parsing the output from other/external tools
> Add options to mangle the output colors of the CLI

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
- [PHP] Support for Multi-Value Headers.
- Add changelog entry.
Abstraction changes
- https://github.com/microsoft/kiota-abstractions-php/pull/26
Generation changes.
- https://github.com/microsoft/kiota-samples/pull/1529
> Multi-Value headers support for PHP Generation

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
This PR fixes a bug where an extra nullable marker was added when method returned a primitive.
> Fixes NRT bug when return type is primitive

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Found the bug using Kiota on this spec file:
https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/main/kafka-admin/.openapi/kafka-admin-rest.yaml
Don't take this as strong advice as I know that's a personal bias, but, to stay on the safe side, I always use full identifiers in the generated code.
Using imports, the code looks nicer, but, it becomes a matter of time before someone experiences a conflict with the domain model.
> Use fully qualified identifiers for java.util.function.Consumer

- docs/get-started/dotnet.md
I stumbled upon Kiota recently and I absolutely love this. I started experimenting with the tool over the weekend and I couldn't get it build by following the [Build SDK's for .NET guide](https://microsoft.github.io/kiota/get-started/dotnet)
All that was missing for me was adding a package reference to `Microsoft.Kiota.Serialization.Form`. Hence, this pull request 😄 
I can verify that the code that this tool generates builds on the following versions of .NET
- .NET Core 7.0 and 6.0
- .NET Standard 2.0
- .NET Framework 4.5.2, 4.6.2, 4.7.2, 4.8, and 4.8.1
I can see why it's best to recommend to use .NET 7.0, as its states in the [Build SDK's for .NET guide](https://microsoft.github.io/kiota/get-started/dotnet) since that is the current and recommended version of .NET but I can't really see …
> Missing Microsoft.Kiota.Serialization.Form from dependencies section in "Build SDKs for .NET"

- CHANGELOG.md
- src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
> Add related links to CLI documentation

- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/Ruby/CodeClassDeclarationWriter.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This PR closes #2234 
Changes include :-
- Use the `GetNavigationPropertyName` property to generate class names to ensure RequestBuilder classes are disambiguated using the namespace. 
- Updates tests
- Updates a couple of scenarios with nullable ref types
> Fixes conflicting request builders

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
This PR is a follow up to https://github.com/microsoft/kiota/pull/2202
It updates the `ReplacePropertyNames` method to avoid property name replacement if it will result in a duplicate property name as seen in the searchHit model where the property `summary` and the property `_summary` would conflict if replacement is done.
```xml
<ComplexType Name="searchHit">
<Property Name="contentSource" Type="Edm.String"/>
<Property Name="hitId" Type="Edm.String"/>
<Property Name="isCollapsed" Type="Edm.Boolean"/>
<Property Name="rank" Type="Edm.Int32"/>
<Property Name="resultTemplateId" Type="Edm.String"/>
<Property Name="summary" Type="Edm.String"/>
<Property Name="_id" Type="Edm.String"/>
<Property Name="_score" Type="Edm.Int32"/>
<Property Name="_summary" Type="Edm.String"/>
<NavigationProperty …
```
> Fixes conflicting properties generation

- src/Kiota.Web/wwwroot/appsettings.json
- src/kiota/appsettings.json
Fixes #2265 - removes the `--prerelease` option from the `DependencyInstallCommand`
> Fixes error in generated dependency installations for .NET code.

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpExceptionsReservedNamesProvider.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
- Exception fields replacements.
- Add CHANGELOG entry.
> PHP - prevent exception field/methods from being used

- .github/CODEOWNERS
This PR contains changes to add koros to the codowner list
> add koros to the github codeowners file

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpExceptionsReservedNamesProvider.cs
part of https://github.com/microsoft/kiota/issues/2243
> PHP - Add `getResponseStatusCode` to PHP exceptions reserved names provider.

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
fixes https://github.com/microsoftgraph/msgraph-sdk-php/issues/952
Constructors will provide an autocompletion experience for PHP 8 developers that reduces the confusion when figuring out which query parameter namespace to import from.
It allows us to initialise the object inline while leveraging PHP 8's [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments)
```php
$messages = $graphServiceClient->usersById(USER_ID)->messages()->get(new MessagesRequestBuilderGetRequestConfiguration(
queryParameters: new MessagesRequestBuilderGetQueryParameters(
select: [],
top: 10
)
));
```
Adds request config constructors:
Adds query param constructors:
Adds query parameter factory methods in the request configuration classes:
generation diff: …
> PHP - Add constructor to query parameter and request configuration classes 

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Fixes a bug introduced by https://github.com/microsoft/kiota/pull/2280 where changing the method return type was not happening since it was being performed before getters are added to the class from the properties.
This PR makes the property type nullable which translates to the getter return type also being nullable.
Updated samples https://github.com/microsoft/kiota-samples/pull/1608
> PHP - Make getAdditionalData return type nullable

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This PR fixes a bug where request builder would be inconsistently generated due to the code below adding the requestBuilder suffix by calling `GetNavigationPropertyName`, 
https://github.com/microsoft/kiota/blob/ff77c899ac3e6ebdebe288b4a18a98ada242140e/src/Kiota.Builder/KiotaBuilder.cs#L487
This causes inconsistency as the indexer appends the suffix to the result of the  `GetNavigationPropertyName` without passing the suffix parameter causing the generation of an indexer called `PostPathRequestBuilder` and a type called `PostItemRequestBuilder`. 
This PR therefore aligns the type name generation to avoid compile issues detected due to this scenario.
> Fixes inconsistent request builder generation

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #2278
depends on https://github.com/microsoft/OpenAPI.NET/pull/1168
> adds support for relative server URL

- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
Fixes generation of FieldDeserializer with GUID types.
related microsoftgraph/msgraph-sdk-go#412
> GO: Remove import symbol from GetCollectionOfPrimitiveValues type param

- CHANGELOG.md
- it/config.json
- it/java/test.java
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
This should finally completely fix #2372
Depends on #2411 for the suppression removals.
> Java - Normalize CodeIndexer return types and errorMappings' types

- .github/workflows/dotnet.yml
- CHANGELOG.md
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
The URI template uses a lower-cased "baseurl" variable while our ApiClient constructor would set a camel-cased `baseUrl` path parameter property causing URL template expansion to fail.
This error wasn't previously discovered since when making requests via the fluent methods the RequestAdapter [sets the correct path parameter key](https://github.com/microsoft/kiota-http-guzzle-php/blob/dev/src/GuzzleRequestAdapter.php#L326) before a request is sent.
This bug was caught when making batch requests where individual RequestInformation objects from the request builders are unpacked into [BatchRequestItem](https://github.com/microsoftgraph/msgraph-sdk-php-core/blob/dev/src/Requests/BatchRequestItem.php#L88) and URI template expansion would fail.
closes …
> PHP - Fix base URL path parameter casing

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
Related to failed build at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=110434&view=results
Currently `GetReferenceIdFromOriginalSchema` function would lookup reference ids from AllOf definitions only one level up. 
In the event that a lookup was more than once level up across different namespaces, this would cause failed lookups resulting to model duplication due in the two namespaces causing build errors.
This PR updates the `GetReferenceIdFromOriginalSchema` function to call the `GetSchemaReferenceIds` function which will find referenceIds recursively through AllOfs OneOfs and AnyOfs. 
Generation run at 
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=110634&view=logs&j=09be00da-8404-5a6e-d496-3b9 …
> Fix for failed lookups by `GetReferenceIdFromOriginalSchema` in multilevel AllOfs

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Related to https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=111491&view=logs&j=fbf82ed0-029a-5388-186b-43225c9ecb54&t=5acdd042-8784-5c45-5c5c-4f54fbf44121
Imported enum with same name as class causes compilation failure due to ambiguous reference.
This PR updates the disamguation code to also include Enums in the lookup and adds test to validate.
> Disambiguates imported Enum with same name imported Class in dotnet

- CHANGELOG.md
- it/config.json
- it/generate-code.ps1
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoReservedNamesProvider.cs
Fix #2373 
Plus a little improvement for running it tests scripts locally.
> Normalize property names ignoring casing

- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/SwiftRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
> - changes with by by for indexers replacements

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes an issue where multiple indexers at the same level would end-up producing invalid uri templates at runtime
> depends on https://github.com/microsoft/OpenAPI.NET/pull/1206
> - fixes an issue where multiple indexers at the same level would end-up producing invalid uri templates at runtime

- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
This PR:
- After cloning properties from parent class, ensures the underlying cloned setter/getter also points to the newly cloned property
- Adds the getter/setter contained within the cloned property to the child class before methods are copied from parent to child. If we don't, the next steps add getters & setters that still point to the accessed property of the parent class since [we don't clone the accessed property](https://github.com/microsoft/kiota/blob/main/src/Kiota.Builder/CodeDOM/CodeMethod.cs#L272).
- For languages where getter/setter method names have a similar name to their properties (no prefix), [adding the getters/setters fails](https://github.com/microsoft/kiota/blob/philip/php/fix-generation/src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs#L910) because an element …
> Error class parent fixes

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1833#discussion_r1170827612
This PR fixes a bug where the backing store property would sometimes be repeated in inherited classes. 
This is caused by a race condition when a base class with multiple derived instances would be added to the code dom. As the base class would be immediately added to the namespace, one of the derived instances being generated at the same time would find the class when searching for the parent model but the class would not have its serialization properties set yet causing the check below to return different results. 
https://github.com/microsoft/kiota/blob/8b4d0035e4b262ff391294799710f46b2181da03/src/Kiota.Builder/KiotaBuilder.cs#L1836
This PR therefore ensures the call to …
> Fix inconsistent backing store property generation

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
The refiner method to inline parent classes copies properties, methods, usings but leaves `Implements` uncopied leading to methods that are supposed to be added when a class implements a given interface without implementing the interface.
Testing Document.
https://github.com/microsoft/kiota/blob/main/tests/Kiota.Builder.IntegrationTests/InheritingErrors.yaml
> Add parent implements to inlined classes.

- it/config.json
Removes suppression for python inheriting errors integration test.
fixes #2492
> Remove python suppression for inheriting errors

- CHANGELOG.md
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Dollar signs denote variable names when used within double-quoted strings in PHP.
Presence of `$count`, `$ref`, `$value` etc in our URL templates causes errors. 
This PR uses single-quoted strings instead.
closes https://github.com/microsoftgraph/msgraph-sdk-php/issues/1217
diff: https://github.com/microsoft/kiota-samples/pull/2197
> PHP - Write url template with single quoted strings

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Web/wwwroot/appsettings.json
- src/kiota/appsettings.json
- src/kiota/kiota.csproj
This PR creates the 1.2.0 release by : 
- bumping versions for 1.2.0 release
- updates kiota dependencies list
- updates the changelog. 
TODO
> Release 1.2.0

- CHANGELOG.md
- src/Kiota.Builder/PathSegmenters/GoPathSegmenter.cs
Some Unix file system consider the trailing white space as part of the filename e.g documented [here](https://doc.owncloud.com/server/next/admin_manual/troubleshooting/path_filename_length.html). This leads to some builds failing with exactly 255 characters in the filenames. This PR reduces the max filename from 255 to 254 to allow instances when the terminal commands add an extra whitespace character to the filename to pass in such container. 
Partially address https://github.com/microsoftgraph/msgraph-beta-sdk-go/issues/260
> Fix go shortened filename

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
Closes https://github.com/microsoft/kiota/issues/2693
Fixes a bug where error response would try to generate the `CreateFromDiscriminator` function for primitive response.
> Fix for invalid errorMappings in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Refiners/ShellRefiner.cs
- src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
Request builders with parameters were erroneously excluded from the generated commands.
Before:
After:
> Fix issue with request builders with parameters being excluded

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
Duplicate query parameter names would be added to the URL template of a request builder in cases where the OpenAPI spec contained the same query parameter names under different operations for the same path.
closes https://github.com/microsoft/kiota/issues/2725
> Select unique query parameter names to add to url template

- CHANGELOG.md
- src/Kiota.Builder/Extensions/StringExtensions.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Closes https://github.com/microsoft/kiota/issues/2360
This PR updates the `CleanupSymbolName` function to return non-empty string when the input symbol only contains special characters. This in turn fixes issues where property names and enum members would fail to be generated to result in compilation errors in dotnet.
> Fixes setting default enum values if the symbol has been sanitized

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/2656
Lookup of schema names is not consistent when the schema has to be flattened. This causes infinite recursion in self referenced schemas that are defined as a single `allOf` without extra properties and therefore generates new models rather than detecting the same model is referenced.
> Fixes stackoverflow exception with self referencing schemas

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Add nill safety check for go collection casting. Check if value is nill before attempting to cast collection. 
current example
```go
for i, v := range m.GetToRecipients() {
cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
}
```
Adds nil check 
```go
for i, v := range m.GetToRecipients() {
if v != nil {
cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
}
}
```
Fixes https://github.com/microsoft/kiota-serialization-json-go/issues/91
Fixes https://github.com/microsoftgraph/msgraph-sdk-go/issues/506
> Prevent type casting nil values in Go collections

- src/Kiota.Builder/Writers/Shell/ShellCodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Shell/ShellCodeMethodWriterTests.cs
IParseNode's `parseNode.GetCollectionOfObjectValues` returns IEnumerable<T> while `To(Put|Post)RequestInformation` accepts List<T>. This PR fixes the compilation error that arises from trying to pass an IEnumerable to a List parameter
> Fix an issue with collection models failing type checking

- tests/Kiota.Builder.Tests/Caching/DocumentCachingProviderTests.cs
httpbin's reliability has been poor over the last month making our tests flaky. This replaces our reliance on the service by mocks
>  - replaces http bin flaky tests by mocks

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
When a reserved keyword is used in a place where it will put in a package name, the keyword is escaped like: new -> newEscaped. However, the package names are converted to lower case prior to this conversion, resulting in package names with an upper case character. This is not idiomatic Java and also causes compilation issues, because the package directory is created in lower case. The conversion to lower case must be done after escaping keywords.
This PR adds a testcase for the issue and moves the `LowerCaseNamespaceNames` to after escaping.
> Convert Java package names to lower case after escaping

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- tests/Kiota.Builder.IntegrationTests/GenerateSample.cs
- tests/Kiota.Builder.IntegrationTests/GeneratesQueryMappers.yaml
- tests/Kiota.Builder.IntegrationTests/Kiota.Builder.IntegrationTests.csproj
- tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/RubyLanguageRefinerTests.cs
Fix #2824 for Ruby and Python.
> Python|Ruby - Fix query parameter mapper generation

- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
Removes parenthesis from datetime serialization method names which would result in generated code `writer.write_datetime_value()("start", self.start)`
> Bugfix datetime serialization method names

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeBlock.cs
- src/Kiota.Builder/CodeDOM/CodeClass.cs
- src/Kiota.Builder/CodeDOM/IBlock.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
In some cases multiple properties from the API spec can end with the same name in the generated code. The most likely cause is the removal of special symbols from the name. These properties can then cause conflicts and result in incorrectly generated code.
This change builds a new name for those properties, and also keeps track these renamed properties in subtypes.
This PR is not yet entirely finished. It still needs some test coverage, mostly related to subtypes, but I decided to already submit it to get some feedback.
> Resolve unique names for properties

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Go does not support method overloading parameters with eventual similar pascal names e.g `additionalData` and `additional_data`  or  `propertyA` and `property_a` eventually coliding.
This change introduces a flag to prevent applying name refiner case when properties with eventual similar method names.
Resolves https://github.com/microsoft/kiota/issues/2719
> Fix go method name conflict

- CHANGELOG.md
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
Calls `sendPrimitiveAsync` on the request adapter with the enum class name.
depends on https://github.com/microsoft/kiota-http-guzzle-php/pull/69
closes https://github.com/microsoftgraph/msgraph-beta-sdk-php/issues/182
> Fix PHP request executor methods returning enums

- CHANGELOG.md
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Web/wwwroot/appsettings.json
- src/kiota/KiotaConfigurationExtensions.cs
- src/kiota/appsettings.json
This causes quite severe corruption of the CodeModel. Many threads concurrently start creating the same models and start adding properties. The result is undefined for larger models and will be different on every run.
This probably fixes (or at least improves the situation for) #2442.
I ran into this trying to build an SDK with the fix for the renaming of properties, which sometimes worked and sometimes didn't work.
> Adds the ability to configure MDOP

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Refiners/ShellRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/PhpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
`CodeEnumOption` was recently changed to derive from `CodeElement` and therefore lead to changing(double processing) of the type in the `ReplaceReservedNames` function in the `CommonLanguageRefiner`.
This Pr streamlines the handling of the `CodeEnumOption` type to be handled like other `CodeElement` instances and adds tests to validate.
> Fixes renaming of enum options in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Logging/FileLogLogger.cs
The StreamWriter does not seem to be threadsafe. On my system I get a lot of crashes like metioned in #2878. This lock fixes the issues on my system. I'm not sure though if this the correct solution for this problem.
> Lock the logger when writing the _logStream

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #2880 
If the schema defines a 206 status code with a model, the request now returns the defined type rather than a byte stream. This can be useful if Content-Range is used with a unit other than bytes.
> Consider 206 as a success code

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
These were often missing in the generated code. AddModelClass only looked in schema.Discription and not in the list of AllOf.
> Add type descriptions for inherited types

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiReferenceExtensions.cs
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiReferenceExtensionsTests.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Types are sometimes created with an upper case type name and sometimes with a lower case type name. This has no functional effect on the resulting code, because the writers will do this, but the converted name can end up in the comment. The comment should follow the spec and should be stable as much as possible.
This pull request fixes spurious changes like in `models/group.go` in this PR https://github.com/microsoftgraph/msgraph-sdk-go/pull/523/files .
> Do not convert first char to upper on type names during code model construction

- .azure-pipelines/ci-build.yml
it's been 3 releases that the GitHub release fails with "Validation Failed".
This error comes from the GitHub REST API and is caused by the fact that our tag/title had a trailing space (see example payload).
```json
{
"tag_name": "v1.4.0 ",
"target_commitish": "d94aa4133423c69a1ff34e6a10a139e41b519e1d",
"name": "v1.4.0 ",
"body": "## Added\\n\\n- Added support ...",
"draft": false,
"prerelease": false
}
```
This PR addresses the issue.
> - fixes an issue where the github release would fail to be created

- it/typescript/package-lock.json
- it/typescript/package.json
Reverts microsoft/kiota#2902
kiota-typescript relies on node-fetch 2.X for the time being (different modules approaches we'll eventually have to solve)
> Revert "Bump node-fetch from 2.6.12 to 3.3.1 in /it/typescript"

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
Ref: [@microsoft/kiota-typescript#752](https://github.com/microsoft/kiota-typescript/pull/752)
> fix: updated `getEnumValues` method name to `getCollectionOfEnumValues`

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CSharpReservedClassNamesProvider.cs
- this fixes an issue, where generated class and namespace names would collide with the HTTP Method enum in Microsoft.Kiota.Abstractions
Closes #2917
> fix: add 'method' to CSharpReservedClassNamesProvider

- src/Kiota.Builder/Refiners/CSharpReservedClassNamesProvider.cs
- src/Kiota.Builder/Refiners/CSharpReservedTypesProvider.cs
Follow up to https://github.com/microsoft/kiota/pull/2939
Moves the string to CSharpReservedTypesProvider to avoid renaming of property names and only types and namespaces.
> Moves "method" to CSharpReservedTypesProvider

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Closes https://github.com/microsoft/kiota/issues/2069
Related to https://github.com/microsoft/kiota-java/pull/487
> Updates generator to use aggregate Duration and Period type in java

- it/config.json
- Removes legacy suppression linked to an unrelated PHP issue
- Adds new tracking issues for suppresions:
https://github.com/microsoft/kiota/issues/2954
https://github.com/microsoft/kiota/issues/2955
https://github.com/microsoft/kiota/issues/2956
https://github.com/microsoft/kiota/issues/2957
> Update developers.pipedrive.com integration test suppressions

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeUsing.cs
- src/Kiota.Builder/Refiners/AdditionalUsingEvaluator.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/TypeScript/CodeUsingWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeUsingWriterTests.cs
> Use ```import type``` for the typescript abstraction library code where relevant

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/Refiners/CliRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- src/kiota/kiota.csproj
> - fixes extraneous indexer for CLI

- intellij/src/main/java/services/GenerateClientHandler.java
- intellij/src/main/java/services/KiotaGenerationLanguage.java
- intellij/src/main/java/toolWindow/MyToolWindow.java
Updated the code with a functional UI that allows user to enter a YAML file path, output directory path, pick a language for generation (only java is functional at this time) enter clientclassname, and clientclassnamespace and generate client classes. 
Enter the YAML file without quotations.
> Added Intellij client classes generation functionality

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Fixes #3149 
Also refactors method documentation.
When a method returns void there is no need for a nullable/NonNull return annotation. This in particular will affect setter methods and constructors. 
From this: 
``` Java 
/**
* Instantiates a new UserItemRequestBuilder and sets the default values.
* @param rawUrl The raw URL to use for the request builder.
* @param requestAdapter The request adapter to use to execute the requests.
* @return a void
*/
@jakarta.annotation.Nullable
public UserItemRequestBuilder(@jakarta.annotation.Nonnull final String rawUrl, @jakarta.annotation.Nonnull final RequestAdapter requestAdapter) {
super(requestAdapter, "{+baseurl}/users/{user%2Did}{?%24select,%24expand}", rawUrl);
}
/**
* Sets the userType property value
* @param value Value to set for the …
```
> Java remove uri exceptions

- CHANGELOG.md
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
> Request executer method call java

- CHANGELOG.md
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Resolves https://github.com/microsoft/kiota/issues/3176
1. Converts UUID indexers to string when adding it to parameters dictionary. Resolves go compilation error.
2. Avoid unnecessary importation of strconv in import statements when using uuid params for indexer methods
> Fix uuid for indexer params

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
This PR fixes https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2084
After changes made in https://github.com/microsoft/kiota/pull/3107 involved the `CodeType` sharing the name with the `TypeDefinition` property to limit unnecessary string copies. This however led to indeterministic renaming of model types as renaming a `TypeDefinition` instance through the parameter type or discriminator mapping would lead to indeterministic results depending on which was processed first and sometimes fail to check for conflicts after renaming.
An example include renaming `microsoft.graph.directory` to `microsoft.graph.directoryObject` (which already exists rather than resolving the renaming conflict) when the `TypeDefinition` when encountered through the discriminator mapping of the base …
> Fixes intermittent issues in model renaming. 

- .github/workflows/integration-tests.yml
- .gitignore
- CHANGELOG.md
- it/compare-generation.ps1
- it/config.json
- it/do-clean.ps1
- it/exec-cmd.ps1
- it/generate-code.ps1
- it/get-additional-arguments.ps1
- it/get-is-suppressed.ps1
- scripts/get-release-notes.ps1
- scripts/get-version-from-csproj.ps1
- scripts/update-version-suffix-for-source-generator.ps1
- scripts/update-versions.ps1
- src/Kiota.Builder/CodeDOM/CodeClass.cs
- src/Kiota.Builder/CodeDOM/CodeIndexer.cs
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/StructuralPropertiesResevedNameProvider.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
This PR adds a job to compare the results of the two subsequent generations performed with Kiota
> Verify idempotency

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/OpenApiExtensions/OpenApiReservedParameterExtension.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
- tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiReservedParameterExtensionTests.cs
> - adds support for reserved path parameters

- CHANGELOG.md
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeEnumWriterTests.cs
Resolves https://github.com/microsoftgraph/msgraph-sdk-go/issues/517
Adds support for serialization of csv values for Go enums by adding a value mask that can support multiple Go values 
```go
func (i ConditionalAccessGuestOrExternalUserTypes) String() string {
var data []string
for p := ConditionalAccessGuestOrExternalUserTypes(1); p <= UNKNOWNFUTUREVALUE_CONDITIONALACCESSGUESTOREXTERNALUSERTYPES; p <<= 1 {
if i&p == p {
data = append(data, []string{"none", "internalGuest", "b2bCollaborationGuest", "b2bCollaborationMember", "b2bDirectConnectUser", "otherExternalUser", "serviceProvider", "unknownFutureValue"}[p])
}
}
return strings.Join(data, ",")
}
func ParseConditionalAccessGuestOrExternalUserTypes(v string) (any, error) {
// detect a command in the string and return enum as mask
var …
```
> Adds support for serialization of csv values for Go enums

- CHANGELOG.md
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/TypeScript/CodeUsingWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeUsingWriterTests.cs
fixes: https://github.com/microsoft/kiota/issues/3232
aggregate imports that have the same source e.g.:
```typescript
import { foo } from 'foobar';
import type { bar } from 'foobar';
```
becomes:
```typescript
import { foo, type bar } from 'foobar';
```
> aggregate imports

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodePropertyWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3260
Typescript writers are creating multidimensional collections for flagged enums that are collections. This fixes the issues by handling them as collections of enums. 
Sample generation of PR at https://github.com/microsoftgraph/msgraph-sdk-typescript/pull/361
> Fixes bitwise enum serialization in typescript.

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeMethod.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/ProprietableBlockExtensions.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - maps 4xx and 5xx to default when absent

- it/compare-generation.ps1
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/CliRefiner.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Refiners/SwiftRefiner.cs
- src/Kiota.Builder/Writers/Java/CodeClassDeclarationWriter.cs
- src/Kiota.Builder/Writers/Java/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodePropertyWriter.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
Sharing to receive early feedback on the direction (cc. @baywet).
I started with Java(instead of Python where we experienced more issues) as I felt more comfortable with it, but I believe that this effort should be extended to all of the languages.
You can check the results by running:
- on the `main` branch: `dotnet publish ./src/kiota/kiota.csproj -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ./publish`
- on this PR branch I'm testing with commands like: `(cd src/kiota && dotnet build) && ./it/compare-generation.ps1 -descriptionUrl "oas::petstore" -language java`
- use more complex specs by testing against the rest ...
> [Java] Move (most of) the name mangling logic to the Refiner

- CHANGELOG.md
- it/compare-generation.ps1
- it/config.json
- it/generate-code.ps1
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Lock/KiotaLock.cs
- src/Kiota.Builder/Lock/KiotaLockComparer.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/kiota/Handlers/KiotaGenerationCommandHandler.cs
- src/kiota/KiotaHost.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes an issue where inline response types would collide

- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #2745
This PR adds 2 tests for the cases described in #2745 .
The first test defines a schema with an `allOf` with a single subschema in the base type. This should be treated as equivalent to not using `allOf` at all. Currently, this breaks the code generation for inheritance entirely.
The second test defines a type with an `allOf` with the properties split into 2 parts. These should be merged in the generated type, but at the moment only the second property is added.
> Add testcases for allOf cases

- CHANGELOG.md
- it/config.json
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodePropertyWriter.cs
- src/Kiota.Builder/Writers/Php/PhpConventionService.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
This PR:
- Writes fully qualified name for duplicated symbols in request executor
- Updates integration test suppressions
> PHP - Fix import errors for types with similar names but different namespaces in request builders

- CHANGELOG.md
> - adds a changelog entry for PHP tracing

- .github/workflows/issue-labels-projects.yml
fixes #1395
@ddyett auth is going to be challenging on this one:
- microsoft graph requires additional secrets, I could have created my own app, but I don't have permissions on the org to install it, so I figured we could reuse the app you've already created. Could you [create a new pair of secrets](https://github.com/microsoft/kiota/settings/secrets/actions/new) for GRAPHBOT_APP_PEM and GRAPHBOT_APP_ID with the values you're already using please?
- microsoft would require a similar setup, but we won't have the permission to install the app, I suggest we move the generator project under the microsoft graph org as only our team is contributing internally so far. Thoughts?
I looked into [using workflow permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-f …
> - udpates issues automation to target new projects

- it/config.json
> - removes suppression for go integration tests

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
Fixes the failing integration test in https://github.com/microsoft/kiota/pull/3477 since PHP uses a [factory method](https://github.com/microsoft/kiota-samples/blob/main/msgraph-mail/php/src/Users/Item/Messages/MessagesRequestBuilderGetRequestConfiguration.php#L42) in request config classes that initialises the relevant query parameter object to improve the developer experience from importing multiple classes.
> Add imports for method parameters that are query parameters

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
> - adds support for enum types in query parameters

- CHANGELOG.md
- src/kiota/Handlers/KiotaInfoCommandHandler.cs
- src/kiota/KiotaHost.cs
This should ease the integrations and enable them to better automate processes.
> Json output for the `kiota info` command

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
fix of how inheritance is implemented for serialization in dotnet
> - fixes serialization/deserialization for inheritance in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Lock/LockManagementService.cs
- tests/Kiota.Builder.Tests/Lock/LockManagementServiceTests.cs
> - lock file now contains the relative path to the description in case of local path

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Writers/CSharp/CSharpWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/LanguageWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
> - fixes missing query parameters in CSharp

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PhpRefiner.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeClassDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeMethodWriterTests.cs
This commit also includes:
- Removing the try catch in the request executor and instead just allow
the exception to be thrown.
- Refactor the type resolution logic in the PHPConventionService.
> [FIX] Include the type which a promise resolves to.

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Php/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Ruby/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
> - fixes missing content type parameter bug

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes a bug where the namespace segment name might contain special characters

- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
We want to be able to refer to the BackingStore property in getters and setters as the following: 
```
public Type getSomeType(){
this.backingStore.get("someType");
}
```
This would be invalid in some cases when a child class extends a parent class that houses the BackingStore property, i.e. any model class which extends the Entity class. 
This is due to the fact that the functionality in the method ```AddGetterAndSetterMethods``` sets the properties accessModifier to Private by default. In an initial attempt to remove this implicit behavior [I removed the getter and setters for the BackingStore property](https://github.com/microsoft/kiota/pull/3737/commits/a97092c21edee99da6493ecd21e5f4b6bc883c4a) and simply made the property public, however the Interface IBackedModel requires that a …
> Backing Store is a Protected Property

- CHANGELOG.md
- it/java/basic/pom.xml
- it/java/pom.xml
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
Those are the changes to align with:
https://github.com/microsoft/kiota-java/pull/843
> Free Java form enum reflection

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
This PR is a follow up to https://github.com/microsoft/kiota/pull/3798/files and fixes failing CI at https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/766
If fixes a bug after the refactor of the `ReplaceReservedNames` function to not replace reserved property type names which was still catered into the `ReplaceReservedModelTypes` function.
Tests added to validate.
> Fixed a bug with reserved property names in dotnet

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3830
Passes "requestContent" param by val instead of by ref.
> Pass go request content by val not ref

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- src/Kiota.Builder/Writers/Go/StringExtensions.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3679
Resolves a bug affecting genration of collection primitives in Go request executors. ReturnTypes were passed as a combination of the PointerSymbols, collection and package reference e.g `[]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.DateOnly`, the fix resolves extraction of the data type by only considering the collection symbol and the actual data type
> Fixes generation of scalar collection primitives in Go

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3436
checks the Enum serialization name in Enum options before defaulting to the example name
> Fix enum name evaluation in go contructors

- .github/workflows/load-tests.yml
- .github/workflows/regex-repro.yml
- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeBlock.cs
- src/Kiota.Builder/CodeDOM/ICodeElement.cs
- src/Kiota.Builder/Configuration/StructuredMimeTypesCollection.cs
- src/Kiota.Builder/Constants.cs
- src/Kiota.Builder/EqualityComparers/OpenApiServerComparer.cs
- src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/RubyRefiner.cs
- src/Kiota.Builder/Writers/CLI/CliCodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- src/Kiota.Builder/Writers/Php/CodeEnumWriter.cs
- src/kiota/KiotaHost.cs
- src/kiota/Rpc/Server.cs
> - refactoring: all regexes use a generate attribute

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
Fixes #3829 
Producing incompatible is not null check.
> Fix incompatible null check for net standard

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes enums projection

- .github/workflows/integration-tests.yml
- CHANGELOG.md
- it/ruby/Gemfile
- src/Kiota.Builder/Refiners/GoRefiner.cs
- tests/Kiota.Builder.IntegrationTests/ToDoApi.yaml
Fixes #3920 
It's the "quick and dirty" fix, we need a deeper review to properly remove the name mangling from the Writers ...
> [Go] Detect and fix model names with clashing constructor

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/SearchProviders/APIsGuru/APIsGuruSearchProvider.cs
- src/kiota/kiota.csproj
- tests/Kiota.Builder.Tests/KiotaSearcherTests.cs
patch to avoid relying on the apis.guru domain name because of its expiration https://github.com/APIs-guru/openapi-directory/issues/1219
> - directly downloads descriptions from github instead of apis.guru

- it/compare-generation.ps1
- it/config.json
- it/generate-code.ps1
- it/get-additional-arguments.ps1
- it/typescript/src/app/app.ts
This PR fixes https://github.com/microsoft/kiota/issues/4028
Changes include :
- Ensures the status code of a task is read and validated when executing the integration tests to prevent false positives. 
- Adds exclude pattern for tests on `https://developers.pipedrive.com/docs/api/v1/openapi.yaml`  due to ambiguous paths causing tests failure.
- Ensures exclude pattern parameters used in integration tests are also used in idempotency tests to ensure they build as well.
- Updates typescript `app.ts` imports to prevent build error after changes in https://github.com/microsoft/kiota/pull/3938 changed the client from a class to interface.
> Fixes integration tests on `https://developers.pipedrive.com/docs/api/v1/openapi.yaml`

- src/Kiota.Builder/Caching/DocumentCachingProvider.cs
- src/Kiota.Builder/Kiota.Builder.csproj
Disclaimer: I am the author of the new library.
Public benchmarks running on GitHub show AsyncNonKeyedLocker to be considerably more performant; in tests NeoSmart.AsyncLock took 9.71x the time and allocated 7.42x the memory.
https://github.com/MarkCiliaVincenti/AsyncNonKeyedLockBenchmarks/actions/runs/7526873065/job/20485876144
> Switched to a more performant locking library

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeParameter.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
> - fixes missing return type bug in TS

- CHANGELOG.md
- src/Kiota.Builder/PathSegmenters/CSharpPathSegmenter.cs
- tests/Kiota.Builder.Tests/PathSegmenters/CSharpPathSegmenterTests.cs
- tests/Kiota.Builder.Tests/PathSegmenters/JavaPathSegmenterTests.cs
- tests/Kiota.Builder.Tests/PathSegmenters/PythonPathSegmenterTests.cs
- tests/Kiota.Builder.Tests/PathSegmenters/TypeScriptPathSegmenterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3854
In summary, changes include
- Prevents the namespace folder name from getting too long
- Normalized paths if they are longer than windows MAX_PATH similar to Go
> Fixes generated paths folders from get too long 

- CHANGELOG.md
- vscode/microsoft-kiota/package-lock.json
- vscode/microsoft-kiota/package.json
- vscode/microsoft-kiota/src/openApiTreeProvider.ts
Fixes #3998.
When filtering, it shows all children nodes, but the filtering target is collapsed.
Visibility works really well IMO, but there is some problem with collapsing nodes - it works overall, but not straight away. 🤷 I'm confused. :(
> VS Code extension: show children nodes when filtering

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/kiota/KiotaHost.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - adds support for none key for serializer arguments

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
> - projects required query parameters as required in the template

- specs/cli/client-add.md
- specs/cli/client-edit.md
- specs/cli/config-init.md
Updated the location of the kiota-config.json file in the init scenario and how / where we store cached descriptions.
> Update location of kiota-config and cached descriptions

- CHANGELOG.md
- src/Kiota.Builder/Caching/DocumentCachingProvider.cs
follow up to #4046 CC @MarkCiliaVincenti
> - fixes a deadlock when evicting cached descriptions

- CHANGELOG.md
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Writers/Go/CodeEnumWriter.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeEnumWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/3936
Fixes https://github.com/microsoftgraph/msgraph-beta-sdk-go/issues/366
Resolves issue with left shift algorithm used in String() operation to assign a value to a multi value enum
Example output
```go
// Supported platform types.
type DeviceManagementConfigurationPlatforms int
// enum values for multi values are base 2
const (
// Default. No platform type specified.
NONE_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 1
// Settings for Android platform.
ANDROID_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 2
// Settings for iOS platform.
IOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 4
// Settings for MacOS platform.
MACOS_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 8
// Windows 10 X.
WINDOWS10X_DEVICEMANAGEMENTCONFIGURATIONPLATFORMS = 16
// Settings for …
```
> Fix Wrong mantis for bitwise/flaggable enums in G

- CHANGELOG.md
- src/Kiota.Builder/Refiners/GoRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Fixes https://github.com/microsoft/kiota/issues/2877
Enum options and enum names should not be escaped in Go
N.B. This is a breaking change
> Enums should not be escaped in Go

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodeIndexerWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
Some cref tags are not closed when doc comments are generated generating warnings in the code. See example logs [here](https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=135049&view=logs&j=0c914960-8b50-5299-c9aa-dd3c9595168e&t=3b0ef9b7-0b0d-5874-6c1c-de7c5a8ae365)
In summary this PR centralizes the generation of type string for generation for documentation to 
- remove nullable markers for primitives
- ensure closing tag is present
Samples validated at https://github.com/microsoft/kiota-samples/pull/5049
> Fixes unclosed documentation tags in dotnet 

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- src/Kiota.Builder/Writers/Python/PythonConventionService.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Java/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
Closes https://github.com/microsoft/kiota/issues/4186
Fixes deprecation descriptions missing type information if a template is passed with type parameters. 
Sample generation present at https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/7208d0626aaf6a9dc323533505f1967d7fd613a0
> Fixes deprecation information comments

- it/java/query-params/src/test/java/BasicAPITest.java
I noticed the failure in #4197 and could reproduce it locally, it doesn't seem like a regression, just a different encoding leading to a different result.
> Fix a Java Mock Server test result

- .github/workflows/build-vscode-extension.yml
we're seeing more and more of those issues creep up. This is because the workflow is currently  querying the API anonymously which has low throttling limits. https://github.com/microsoft/kiota/actions/runs/8019333735/job/21906993966#step:4:7
> - passes the token to the release step so it doesn't get throttled

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeConstantWriterTests.cs
Fixes:https://github.com/microsoft/kiota-typescript/issues/992
> remove async suffix for request adapter methods

- it/config.json
Suppresses intergration tests for 
- Ruby - GeneratesUritemplateHints.yaml - Tracked via https://github.com/microsoft/kiota/issues/4262
- All languages - apisguru::github.com:api.github.com - Tracked by https://github.com/microsoft/kiota/issues/4241
> Cleanup integration tests

- src/kiota/appsettings.json
Added the `exact` switch when suggesting dependency installs for npm under the TypeScript mode.
PR as suggested in: https://github.com/microsoft/kiota-typescript/issues/1075
> Suggest save-exact for npm dependencies

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeClassDeclarationWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeIndexerWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Fixes the C# code generation to follow the usual style of putting braces on new lines.
Fixes #4347
> Put braces on new line in CSharp generator

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
> - fixes a bug where TypeScript generation would consider boolean argument as empty when false

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeClass.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes a bug where models properties named "additionalData" or "backingstore" would be ignored

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeConstantWriterTests.cs
Fixes: https://github.com/microsoft/kiota-typescript/issues/1042
fixes #4199
> add support for enums or collection of enums as root payload

- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
Follow up to https://github.com/microsoft/kiota/pull/4348
Request builder properties have unnecessary indentations in declarations. See https://github.com/microsoft/kiota-samples/pull/5331/commits/03fc927ada16cdc8a649cdbd57691abf46ea3d62 for example diff.
This PR enables the writer to skip the indent for better formating. 
Sample generation at https://github.com/microsoft/kiota-samples/pull/5331
> [Dotnet] Fixes unnecessary indent in request builder properties.

- src/Kiota.Builder/OpenApiExtensions/OpenApiLogoExtension.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- src/kiota/KiotaPluginCommands.cs
Fixes https://github.com/microsoft/kiota/issues/4417
Related to https://github.com/microsoft/kiota/pull/4477
> Remove defaults for plugin types

- specs/cli/plugin-add.md
- specs/cli/plugin-edit.md
- specs/cli/plugin-remove.md
This PR is meant to update the current plugin spec:
- Remove the default value for `--type`. `--type` should be a required parameter.
- When choosing `openai`, the generated plugin should be named `open-ai-plugins.json`
> Updating plugin spec

- specs/cli/plugin-add.md
- specs/cli/plugin-edit.md
- specs/cli/plugin-remove.md
Updating the resulting plugin name to openai-plugins.json wheen choosing --type openai
> Fixing typo from open-ai-plugins.json to openai-plugins.json

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodeClassDeclarationWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/CommonLanguageConventionService.cs
- src/Kiota.Builder/Writers/Go/GoConventionService.cs
- src/Kiota.Builder/Writers/ILanguageConventionService.cs
- src/Kiota.Builder/Writers/Java/JavaConventionService.cs
- src/Kiota.Builder/Writers/Php/PhpConventionService.cs
- src/Kiota.Builder/Writers/Python/PythonConventionService.cs
- src/Kiota.Builder/Writers/Ruby/RubyConventionService.cs
- src/Kiota.Builder/Writers/Swift/SwiftConventionService.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
> Suppress CS1591 when generating CSharp code and documentation is not available

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodePropertyWriterTests.cs
> Do not generate CS8603 warnings when enabling backing store

- .vscode/launch.json
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/PluginType.cs
- src/Kiota.Builder/Plugins/AuthComparer.cs
- src/Kiota.Builder/Plugins/OpenAPiRuntimeComparer.cs
- src/Kiota.Builder/Plugins/OpenApiRuntimeSpecComparer.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- src/kiota/Handlers/Plugin/AddHandler.cs
- src/kiota/kiota.csproj
- tests/Kiota.Builder.Tests/Plugins/OpenAPIRuntimeComparerTests.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Fixes https://github.com/microsoft/kiota/issues/4491
Fixes https://github.com/microsoft/kiota/issues/4447
Changes include
- Adds the `microsoft` type as that is what is being generated at the moment. 
- Fixes breaking changes from latest update from manifest lib
- Fixes naming of generated manifests to apply to convention of `{plugin-name}-{pluginType}.json`
> Manifest library updates

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
> - fixes casing issue in deserialization of response content in TypeScript

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiUrlTreeNodeExtensionsTests.cs
Fixes https://github.com/microsoft/kiota/issues/4448
`CleanupParametersFromPath` removes prefixes causing request builder collisions in scenario such as `metadata{path}` and `{path}` segments end up being mapped to the same request builder rather two separate ones.
This PR therefore improves the cleanup logic to include the prefix in scenarios where the prefix is not a parameter name(`=` is present) to improve the disambiguation and unlock generation of the description at https://teamcity.jetbrains.com/guestAuth/app/rest/swagger.json
> Fixes request builder disambiguation

- .azure-pipelines/ci-build.yml
Reverts microsoft/kiota#4510
The marketplace service has a bug where it can't verify service principals for publishing yet. They are working on that while we use a PAT for the time being.
> Revert "- migrates to AAD tokens from PATs for extension publishing due to ADO requirements"

- CHANGELOG.md
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/PathSegmenters/GoPathSegmenter.cs
- tests/Kiota.Builder.Tests/PathSegmenters/GoPathSegmenterTests.cs
fixes #4407
Escape all special suffixes in go file names
> Escape all special suffixes in go file names

- CHANGELOG.md
- src/kiota/Handlers/BaseKiotaCommandHandler.cs
- src/kiota/Handlers/Plugin/GenerateHandler.cs
- src/kiota/KiotaConfigurationExtensions.cs
fixes #4556 
This adds support for the environment variable `KIOTA_OFFLINE_ENABLED`. If set to `true`, checking for updates before each command will be skipped.
Related PR for docs: https://github.com/MicrosoftDocs/openapi-docs/pull/68
> Add environment variable to disable updates check

- CHANGELOG.md
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
> - fixes manifest serialization

- CHANGELOG.md
- src/kiota/Program.cs
- tests/Kiota.Builder.Tests/Logging/FileLoggerTests.cs
> - fixes empty log file issue

- CHANGELOG.md
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- src/Kiota.Builder/WorkspaceManagement/BaseApiConsumerConfiguration.cs
- src/Kiota.Builder/WorkspaceManagement/WorkspaceManagementService.cs
- tests/Kiota.Builder.Tests/Configuration/GenerationConfigurationTests.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
>  - fixes workspace absolute path for relative descriptions

- .github/ISSUE_TEMPLATE/01-kiota-bug.yml
- .github/ISSUE_TEMPLATE/02-kiota-feature-request.yml
- .github/ISSUE_TEMPLATE/03-blank-issue.md
- .github/ISSUE_TEMPLATE/config.yml
Relates to https://github.com/microsoft/kiota/issues/4432
> chore: Add issue forms to Kiota

- .github/ISSUE_TEMPLATE/01-kiota-bug.yml
- .github/ISSUE_TEMPLATE/02-kiota-feature-request.yml
- .github/workflows/project-auto-add.yml
- Only adds the issue or PR if the actor is not dependabot.
- Also filters for provided language in bug or feature request issue form and use this to populate the Language field on the project
- No need to set status to triage as the project workflow specified [here](https://github.com/orgs/microsoft/projects/220/workflows) will add status `ToDo` to all newly opened items.
> chore: Add github action to add new PR or Issue to project kiota

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/kiota/Handlers/BaseKiotaCommandHandler.cs
- src/kiota/Handlers/Client/AddHandler.cs
- src/kiota/Handlers/Client/EditHandler.cs
- src/kiota/Handlers/Client/GenerateHandler.cs
- src/kiota/Handlers/KiotaGenerateCommandHandler.cs
- src/kiota/Handlers/KiotaUpdateCommandHandler.cs
- src/kiota/Handlers/Plugin/AddHandler.cs
- src/kiota/Handlers/Plugin/EditHandler.cs
> - adds display url to the CLI experience

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Validation/MissingDiscriminator.cs
- src/Kiota.Builder/Validation/UrlFormEncodedComplex.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
fixes #4325
fixes #4346
fixes #4074
fixes https://github.com/microsoft/kiota/issues/4428
> - fixes a bug where multiple allOf entries type would not get merged if they were part of a discriminator

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeInterface.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- tests/Kiota.Builder.Tests/CodeDOM/CodeClassTests.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeInterfaceDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeClassDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeConstantWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeInterfaceDeclarationWriterTests .cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodePropertyWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeUsingWriterTests.cs
This PR fixes https://github.com/microsoft/kiota/issues/4382
In summary, changes include
- Makes the `OriginalClass` property in `CodeInterface` required as ideally this is a Dom element created from another class not originally in the builder. So this is always expected to populated.
- Updates the typescript refiner to no longer rely on the `TemporaryInterfaceNameSuffix` to generate interfaces by appending and then truncating the suffix later on. This is now done directly using the name from the `OriginalClass`(which is required and always present) to guarantee similar names between the class and the final interface.
> Fixes name collisions in TS refiner between models and interfaces.

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> - fixes invalid inheritance cases

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
fixes #4615
CLI Generator is unable to handle parameters such as `DateTime`, `Date`, etc.  More precisely, the parameters having `type="string"` and `format="datetime"`, `"date"` etc.
Screenshots: 
Tests:
Kiota Update:
Build of Sample project:
Change in the builder Class:
> CLI Generation to handle  parameter of type 'string' but different format

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/4191
Update the parameter for `GetSchemaName` to be calculated based on whether the schema is meaningful (if it isn't let's try to find the name as it could be flattened schema that's referenced) so that we avoid duplicate models in the same namespace. 
Validated with graph V1 at https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/3a7dcfdff19c15aa788241fbe1949a6f6439a654 (essentially no diff present)
> Fixes duplicated models in single allOf scenarios 

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
Fixes https://github.com/microsoft/kiota/issues/4692
Fixes missing `UntypedNode.CreateFromDiscriminatorValue` parameter in method writer.
> Fixes missing `CreateFromDiscriminatorValue` parameter in dotnet.

- scripts/execute-vscode-sideload.ps1
- vscode/microsoft-kiota/debugging.md
Adding the script to help with automating all steps to sideload the extension.
Tested on Windows and WSL.
> Adding the automatic sideloading script

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
fixes #4707
Working SS:
Build of sample project
Option Type - string[]:
`var testStringArrayParameterOption = new Option<string[]>("--test-string-array-parameter", description: "Usage: newParameter=@newParameter") {
Arity = ArgumentArity.ZeroOrMore
};`
Parameter Type:
`[QueryParameter("testStringArrayParameter")]
public string[]? TestStringArrayParameter { get; set; }`
Tests Passing:
> refs #4707 bug fix to handle string array querry parameters.

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/4715
It updates the `ReplaceAllIndexesWithWildcard` to cater for scenarios where the indexer is the end of the path without a trailing slash. 
Normally, this hasn't been seen as an issue as the indexer usually matches the openApi description. However, in some scenarios such as the VS code extension, the paths displayed maybe cleaned up due to the inder deduplication logic and thus the functionality becomes more important.
> Fixes indexer cleanup for glob matching.

- CHANGELOG.md
- src/kiota/Handlers/BaseKiotaCommandHandler.cs
- src/kiota/KiotaHost.cs
Never override an explicit `--log-level` option, even in DEBUG builds but default to the `Debug` log level for DEBUG builds and keep the `Warning` default for RELEASE builds.
> Do not force LogLevel.Debug for DEBUG builds

- vscode/microsoft-kiota/src/steps.ts
Adds option to select "Search" or "Browse" an API path when adding an API description
> Feature: Enhances the API Description selection

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiOperationExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fix #4734 
This PR covers an issue when multipart/form-data is present.
Added an additional method IsMultipartTopMimeType next to IsMultipartFormDataSchema.
This method checks for:
- Presence of "multipart/form-data" in the current RequestBody Content
- If "multipart/form-data" is the only RequestBody Content Type
- If "multipart/form-data" is first in structuredMimeTypes
> Fix missing models when multipart is present in document.

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/4761
> Fixes a bug where warnings about discriminator not being inherited were generated

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
Related to https://github.com/microsoftgraph/msgraph-sdk-java/pull/2032 and https://github.com/microsoftgraph/msgraph-beta-sdk-java/pull/969
When backingstore is enabled, the properties are removed from the CodeDom by the java refiner. This PR updates the usingEvaluator to use the getter and setters which are always present.
> Fixes missing imports in java generation for `UntypedNode`

- .github/workflows/project-auto-add.yml
Fixes https://github.com/microsoft/kiota/issues/4626
> Sync Language label on project with language label on the issue

- CHANGELOG.md
- it/csharp/dotnet.csproj
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Writers/CSharp/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeMethodWriterTests.cs
> Remove LINQ from generated code

- CHANGELOG.md
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Updates the slicing of the openApi file to ensure the response description is not empty to prevent validation from TTK as it doesn't accept empty description properties.
> Ensure response description is not empty in response for openApi file generated during plugin generation

- CHANGELOG.md
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- src/Kiota.Builder/WorkspaceManagement/WorkspaceManagementService.cs
- src/kiota/KiotaPluginCommands.cs
> feat: plugins generation no longer emits parameters

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSettingsExtensions.cs
- src/Kiota.Builder/OpenApiDocumentDownloadService.cs
- tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiAiReasoningInstructionsExtensionTests.cs
- tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiAiRespondingInstructionsExtensionTests.cs
- tests/Kiota.Builder.Tests/OpenApiExtensions/OpenApiDescriptionForModelExtensionTests.cs
> fix: only loads OpenAPI plugins extensions when generating plugins

- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/openApiTreeProvider.ts
Fixes #4853 
if the Open API tree has changes and a user wishes to open a new description, the override message will appear else, no message appears even after regeneration
Steps to test: 
1. Load extension
2. Open an API Description
3. Select paths and generate a client/plugin/manifest
4. When the tree reloads, try to open an API description file again
5. Observe no message
6. Now select/unselect a node or some nodes, then try to open an API description file 
7. Observe the message appears
> Fix: "Override" message only displays if there's a change on the tree

- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/kiotaInterop.ts
Fixes #4870 
This PR updates the generation and re-generation functions to accept an array of plugin types.
**Steps to test**
1. Load extension
2. Open an API description and select endpoints
3. Generate a plugin
4. Open workspace.json and edit the plugin type, save, then click re-generate on the file.
5. Observe fix
> Fix: Update plugin type on to accept multiple values

- CHANGELOG.md
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
Fixes https://github.com/microsoft/kiota/issues/4925
> Adds missing TS imports

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/CSharpLanguageRefinerTests.cs
Fixes https://github.com/microsoft/kiota/issues/4893
In summary, this PR
- Updates the `ReplaceReservedExceptionPropertyNames` method to also rename the error class if it is the same name as a reserved class to avoid collision with class name and property name.
- Updates the `AddPrimaryErrorMessage` to rename existing matching properties if they already exist in the error model to avoid information/property loss (otherwise we will fail to add the override and lead to invalid generation)
- Add tests to validate the scenarios.
Essentially, in a scenario where a `ErrorMessageOverride` property kind named `message` is added,
- if the error model class is also called `message`, the model class will be renamed to avoid class and property name collision.
- if a property with the same name …
> Fix `ErrorMessageOverride` collision with classname

- CHANGELOG.md
- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/Extensions/StringExtensions.cs
- src/Kiota.Builder/Lock/LockManagementService.cs
- src/Kiota.Builder/WorkspaceManagement/BaseApiConsumerConfiguration.cs
- src/Kiota.Builder/WorkspaceManagement/WorkspaceManagementService.cs
- tests/Kiota.Builder.Tests/Lock/LockManagementServiceTests.cs
This seems to be the most straightforward way of solving the issue where Windows paths fail on Linux machines, unless there are some systems which don't use the forward slash as a path separator?
Resolves #4228
> Normalize local DescriptionLocation to use / as directory separator

- CHANGELOG.md
- src/Kiota.Builder/Plugins/Models/AppManifestModel.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
> fix: do not erase the declarative copilot entries if any

- tests/Kiota.Builder.Tests/Writers/CSharp/CodeClassDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeEnumWriterTests.cs
follow up to #4907
More context: https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=155225&view=logs&j=7871e8ac-1348-5c5a-3691-0fa1e72e8e2e&t=d966bf08-649a-57f5-fb3f-a56ed96c454c
This is blocking preview releases
> ci: fixes preview generated code unit test failure introduced by #4907

- vscode/microsoft-kiota/src/steps.ts
Fixes #4990 
When a user clicks on search, they can search an API description or paste a URL or a path to a local API description
> Fix: Add paste path functionality

- vscode/microsoft-kiota/package.json
- vscode/microsoft-kiota/package.nls.json
- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/util.ts
- vscode/microsoft-kiota/src/workspaceTreeProvider.ts
Fixes #4855 
Please note that VSCode does not provide direct APIs to programmatically collapse or expand the entire tree view
> Fix: Workspace file display

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
> fix: missing properties in python when no additional properties

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
Added a new function to include `ts-ignore` comment to method shape/prototype.
Currently, generated TypeScript client code contains methods with unused arguments that are never referenced in the body.
This causes TypeScript typecheck to fail in projects where `tsconfig.json` compiler option `noUnusedLocals: true` is set.
Example: Vitejs template [tsconfig.json](https://github.com/vitejs/vite/blob/main/packages/create-vite/template-react-ts/tsconfig.json#L19)
p.s.: not sure what to test here.
> Ignore method arguments typechecking in typescript

- CHANGELOG.md
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
Closes https://github.com/microsoftgraph/msgraph-sdk-python/issues/795
Note that
`if not column` is falsy even if colum exists and is zero, using i`f column is None` will check that column is null in a better way in this case:
The generated code behavior is now adjusted from
```python
if not body:
raise TypeError("body cannot be null.")
request_info = self.to_patch_request_information(
body, request_configuration
)
```
To
```python
if body is None:
raise TypeError("body cannot be null.")
request_info = self.to_patch_request_information(
body, request_configuration
)
```
And the same applies in all areas including drive items
> remove falsy check for nulls in method parameters

- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
> fix; missing null declaration for ts serialization

- CHANGELOG.md
- src/Kiota.Builder/Refiners/JavaReservedNamesProvider.cs
> fix: missing map in java reserved names

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/Plugins/AuthComparer.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
this upgrades the plugins dependency.
it also removes the openAI plugin generation since now the service only requires the sliced description.
We might want to review the CLI UX and the extension UX at a later phase since now we could ask one fewer question.
CC @sebastienlevert
> chore: upgrade dependencies feat: removes openai plugin generation

- CHANGELOG.md
- src/Kiota.Builder/Writers/CSharp/CSharpConventionService.cs
- src/Kiota.Builder/Writers/CSharp/CodeBlockEndWriter.cs
- src/Kiota.Builder/Writers/CSharp/CodeClassDeclarationWriter.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeClassDeclarationWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/CSharp/CodeClassEndWriterTests.cs
Hi,
when the source document contains a model that is not deprecated but contains a deprecated property, the compiler is unhappy with CS0618. This PR simply disables CS0618 in generated code
> Source generated models should not scream on CS0618

- vscode/microsoft-kiota/src/extension.ts
Closes #5094 
- Sets the regeneration behavior of `cleanOutput` to false to allow the plugin to be regerated in the same folder without overwriting
> Task: regenerate without overwrite

- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/openApiTreeProvider.ts
Adds a default plugin name from the Open API description
Closes #5110 
After generation
Name editable
After generation with new name
> Task: default plugin name

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/ContentTypeMappingTests.cs
Fixes #5208. 
If a response contains `application/octet-stream` as a response type, the Kiota-generated response type should be a binary one. 
An concrete example of when this may happen: an API is migrating from hosting their own assets to returning redirects to a blob storage service, and they may return either a 302 Found and redirect to a URL that contains the asset, or the binary asset directly. For a standard consumer with redirects enabled, the end result is the same. For Kiota, generation needs to know to return binary content types. Currently Kiota will not do so and instead return void types.
> If any response contains octet-stream, make response binary

- CHANGELOG.md
- src/Kiota.Builder/CodeDOM/CodeParameter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
> fix: missing ts path parameters

- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/test/suite/extension.test.ts
- vscode/microsoft-kiota/src/util.ts
Partial fix for #5206
To test:
1. Follow steps specified in [debugging.md](https://github.com/microsoft/kiota/blob/main/vscode/microsoft-kiota/debugging.md#running-in-debug-mode)
2. On pressing F5 to open a new vscode debug window, run these next commands in that debug window
3. Create|open an md file e.g "test.md" in/from your preferred location and create a commandUri that enables you to pass requisite parameters. See sample attached. 
[test.md](https://github.com/user-attachments/files/16787882/test.md)
4. ctrl + click on the command uri to execute the command which is similar to doing 
```
vscode.commands.executeCommand(
'kiota.openApiExplorer.searchOrOpenApiDescription',
[
{
"kind":"Plugin|Client",
"type":"ApiPlugin|ApiManifest|OpenAI", //Only useful when kind is plugin
"language": …
```
> Feat: Ext/task5206/command based ttk integration in vs code extension

- vscode/microsoft-kiota/src/extension.ts
Sends the plugin manifest to TTK if source of generation is TTK.
- Follow steps specified in https://github.com/microsoft/kiota/blob/main/vscode/microsoft-kiota/debugging.md#running-in-debug-mode
- On pressing F5 to open a new vscode debug window, press the key combination ctrl + shift + p to open the command pallete.
- Select the Debug: Open Link command which will provide an input box to paste your url. e.g. "vscode://ms-graph.kiota/OpenDescription?descriptionUrl%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2Fgithub%2Frest-api-description%2Fmain%2Fdescriptions%2Fghes-3.0%2Fghes-3.0.json&kind=Plugin&type=ApiPlugin&name=GitHubClientPlugin&source=ttk"
- Follow the prompts to open the link in vscode debug window.
- When tree loads in the side panel, select the nodes you want to include in your …
> Feat: hand over generated plugin manifest

- src/kiota/kiota.csproj
kiota is not directly vulnerable because we were not using the problematic dependencies. This is simply to fix the altert we're getting
> fix: adds direct dependency on STJ to avoid transitively resolving the wrong version

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CSharpRefiner.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- src/Kiota.Builder/Refiners/JavaRefiner.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/JavaLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
> fix: missing untyped node imports

- src/Kiota.Generated/KiotaGenerated.csproj
context https://github.com/Homebrew/homebrew-core/pull/183622
> fix: uses a version range for analyzer cSharp so kiota is not tied to a specific version of the SDK

- CHANGELOG.md
- src/Kiota.Builder/Writers/Python/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodeMethodWriterTests.cs
Fixes https://github.com/microsoftgraph/msgraph-sdk-python/issues/165
> remove stringify from constructor properties

- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/steps.ts
Closes #5385 
When in deep link and with ttk, the kiota working directory changes to the temp folder ensuring that generation of new plugins is not blocked
> Fix: create new plugin same oad

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/5433
> fix: item path escaping regression

- vscode/microsoft-kiota/CHANGELOG.md
- vscode/microsoft-kiota/README.md
- Also fixes changelog release version and date as release delayed with a day owing to build timeout.
> Fix Readme image sources by using raw url as opposed to blob url

- .vscode/tasks.json
When you launch the debugger in vscode, following error is thrown
```bash
Executing task: C:\Program Files\Git\cmd\git.exe checkout **/kiota-lock.json 
error: pathspec '**/kiota-lock.json' did not match any file(s) known to git
*  The terminal process "C:\Program Files\Git\cmd\git.exe 'checkout', '**/kiota-lock.json'" terminated with exit code: 1.
```
The proposed changes fixes this by removing the dependency for the build task on the task ["checkout:sample:locks"] in the .vscode/tasks.json file.
> Fix kiota vscode settings dependency for task build

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Refiners/TypeScriptLanguageRefinerTests.cs
Closes https://github.com/microsoft/kiota/issues/5404
When trying to find the factory method in the `TypeScriptConventionService.cs` file, the method was looking for the factory method in the from the namespace. In the event that a namespace is a child of the namespace has a factory method with the same name, this may find the incorrect method(that's why it was aliased).
As the target model will be in the same file as its factory method, the PR narrows the search to work from the file searching from the namespace will be too broad.
> WIP: Fixes incorrect type name and factory method name generation in aliased scenario

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/5462
Fixes https://github.com/microsoft/kiota/issues/4831
Fixes the mapping of types in request builders with subsequent paths with the same name to not select themselves.
> Fixes incorrect type mapping

- vscode/microsoft-kiota/src/commands/editPathsCommand.ts
- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/utilities/progress.ts
- Moves the edit Paths command implementation from extensions.ts to it's own file
- Moves the close Description implementation from extensions.ts to its' own file
Closes #5516
> Task: create edit paths command

- CHANGELOG.md
- it/typescript/package.json
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/5504
According to the spec at https://spec.openapis.org/oas/v3.0.3.html#special-considerations-for-multipart-content,
In the event that we do not have encodings present, multipart provides defaults as below, 
- If the property is a primitive, or an array of primitive values, the default Content-Type is text/plain
- If the property is complex, or an array of complex values, the default Content-Type is application/json
- If the property is a type: string with format: binary or format: base64 (aka a file object), the default Content-Type is application/octet-stream
This pr updates the evaluation of the model type to take this into consideration based of the passed configuration in the structured mime types.
> fixed defaults for multipart requests

- src/Kiota.Builder/Plugins/AuthComparer.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
This PR fixes issues with the plugin runtime generation for scenario where multiple security schemes are defined in the document, but each is used in a different operation. In this case, only the 1st security scheme would be used which is not what we want.
Another minor change is that the error message displayed when more than one security requirement is provided has been updated to show a less generic message.
> Improve generated plugin auth definition

- CHANGELOG.md
- it/config.json
- src/Kiota.Builder/CodeDOM/CodeNamespace.cs
- src/Kiota.Builder/Refiners/GoRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Resolves https://github.com/microsoft/kiota/issues/2834
Fixes cyclic dependencies by flattening models affected by cyclic depndecies i.e when a cyclic depedency is detected the affected packages will be flattened and migrated to the rot models package.
For example 
models -> submodule1 -> submodule2 -> submodule3 -> submodule2
will be flattened by migrating everything under submodule2 to the root models package
Testing:
1. Enabled suppressed integrated tests 
2. Added unit tests
> Fix Cyclic Dependencies in Go

- vscode/microsoft-kiota/src/extension.ts
A follow up to #5541 
Closes #5527
When a user generates a client and the openapi tree view is still on the description that's been used to generate the client, hitting the regenerate button after adding / removing a path fails.
the `clientOrPluginObject` is populated by `editPaths`. So in this scenario where the user doesn't open the workspace to trigger an edit and merely just continues editing after generation, the `clientOrPluginObject` is empty but the configuration object is populated.
> Fix: regenerate button after immediate generation

- global.json
The version number currently used doesn't match with an actual SDK version. It should be `8.0.xxx`. I've updated it to use the latest SDK version.
> Fix SDK version in global.json file

- src/Kiota.Generated/KiotaGenerated.csproj
seeing some build failure as:
```
==> dotnet publish src/kiota/kiota.csproj --configuration Release --framework net8.0 --output /opt/homebrew/Cellar/kiota/1.19.0/libexec --runtime osx-arm64 --no-self-contained -p:TargetFramework=net8.0 -p:PublishSingleFile=true -p:Version=1.19.0
Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.108
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate, run 'dotnet dev-certs https --trust'
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to …
```
> fix: pin Microsoft.CodeAnalysis.CSharp to 4.8.0.0 to fix compiler mismatch

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
Related to https://github.com/microsoft/OpenAPI.NET.OData/pull/589
Latest changes in the conversion library add the `type` property to the schema of the `ReferenceNumeric` type used in odata primitives.
This causes incompatibility with the `IsODataPrimitiveType` which only expects one schema to have the type of `string`.
This PR updates the implementation so that the new scenario is captured and older documents with the older format are not broken by this change.
> fixes incompatibility with new odata primitive format.

- CHANGELOG.md
- src/kiota/Handlers/KiotaGenerateCommandHandler.cs
- src/kiota/Handlers/KiotaUpdateCommandHandler.cs
Fixes https://github.com/microsoft/kiota/issues/5576
> Display clean output hint when generating CSharp client only when --clean-output is missing

- vscode/microsoft-kiota/src/commands/closeDescriptionCommand.ts
- vscode/microsoft-kiota/src/commands/selectLockCommand.ts
- vscode/microsoft-kiota/src/commands/statusCommand.ts
- vscode/microsoft-kiota/src/extension.ts
- vscode/microsoft-kiota/src/handlers/uriHandler.ts
> Task: create various commands

- CHANGELOG.md
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Closes https://github.com/microsoft/kiota/issues/5611
Generation run at https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=167346&view=results
Sample diff at https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/kiota/v1.0/pipelinebuild/167322..kiota/v1.0/pipelinebuild/167346
> fix: fixes missing mapping for the `int16` type

- CHANGELOG.md
- src/Kiota.Builder/Writers/Go/CodeMethodWriter.cs
- tests/Kiota.Builder.Tests/Writers/Go/CodeMethodWriterTests.cs
Fixes: https://github.com/microsoft/kiota/issues/4844
When generating Go based SDKs from GitHub's OpenAPI [definitions](https://github.com/github/rest-api-description/tree/main/descriptions/api.github.com) we noticed that the `GetFieldDeserializers` function was empty for any operations using discriminators and `OneOf`
It turns out that the issue is in WriteDeserializerBodyForUnionModel or at least why the method body is not getting generated.
So the LINQ statement for Go is:
```
var otherPropGetters = parentClass
.GetPropertiesOfKind(CodePropertyKind.Custom)
.Where(static x => !x.ExistsInBaseType && x.Getter != null)
.Where(static x => x.Type is CodeType propertyType && !propertyType.IsCollection && propertyType.TypeDefinition is CodeClass)
.OrderBy(static x => x, …
```
> Fixes the union deserializer code generation in Go

- global.json
related https://github.com/Homebrew/homebrew-core/pull/193771
follow up to https://github.com/microsoft/kiota/pull/5535
CC @captainsafia
> fix: sets a version compatible with linux installations

- CHANGELOG.md
- src/Kiota.Builder/Refiners/CommonLanguageRefiner.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
Fixes https://github.com/microsoft/kiota/issues/4178
Fixes https://github.com/microsoft/kiota/issues/4478
In the event that a union type was converted to a wrapper type, the CommonLanguage refiner would not check if the type was already present in the namespace. It therefore went ahead to add the same properties over and over whenever `ConvertComposedTypeToWrapper` is called.
> Fix superfluous fields when converting composed types to wrapper types.

- src/Kiota.Builder/SearchProviders/OpenApiSpec/OpenApiSpecSeachProvider.cs
Intergration tests failing due to description samples moved in https://github.com/OAI/OpenAPI-Specification/pull/4166
Updates the code to point to the new url.
> fix intergration tests

- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
Supplement to MR: [microsoft/kiota-typescript#1475](https://github.com/microsoft/kiota-typescript/pull/1475)
Fixes [microsoft/kiota#4508](https://github.com/microsoft/kiota/issues/4508)
Using a custom Guid type to get rid of unnecessary package (and partly broken) guid-typescript.
> fix: getting rid of unnecessary guid-typescript dependency

- .azure-pipelines/ci-build.yml
- CHANGELOG.md
- scripts/enable-shims-for-packaging.ps1
Fixes https://github.com/microsoft/kiota/issues/5650
According to the docs at https://github.com/dotnet/sdk/blob/main/documentation/general/signing-global-tool-packages.md,
a shim is created in target machine by dotnet in scenarios where the `PackAsToolShimRuntimeIdentifiers` tag is not defined in the csproj. This ends up showing as an unsigned binary as it is created at the time of installation.
This PR adds as script to dynamically add the attribute so that the shim is created during `dotnet build` in the release pipeline so that it signed together with the artifacts. 
This has been validated by installing the tool locally as well as inspecting the artifacts in this pipeline run. 
https://dev.azure.com/microsoftgraph/Graph%20Developer%20Experiences/_build/results?buildId=169565&view=resu …
> Fix unsigned kiota.exe file when installed as dotnet tool.

- src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
Hello!
After my PR [microsoft/kiota#5734](https://github.com/microsoft/kiota/pull/5734) I realized that there is no need for the createGuidFromDiscriminatorValue function (which causes an error in the generated client), since Guid is now an alias to string. So I made it so that Guid is parsed as its alias primitive.
> fix: Guid is an alias to primitive type string

- .github/workflows/integration-tests.yml
- it/config.json
- it/python/discriminator/test_serdeser.py
- tests/Kiota.Builder.IntegrationTests/DiscriminatorSample.yaml
Fixes https://github.com/microsoft/kiota/issues/4433
> validate #4435

- CHANGELOG.md
- it/config.json
- src/Kiota.Builder/CodeDOM/CodeComposedTypeBase.cs
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/TypeScript/CodeFileDeclarationWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeMethodWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
Fix serialization and deserialization of composed types in TS 
fixes https://github.com/microsoft/kiota/issues/5353
Changes made to fix the serializer will include writing an undefined value for the string and and the collection of string
```ts
export function serializeSuccess(writer: SerializationWriter, success: Partial<string[] | string> | undefined | null = {}) : void {
if(success){
switch (true) {
case typeof success === "string":
writer.writeStringValue(undefined, success as string);
break;
case Array.isArray(success) && (success).every(item => typeof item === 'string') :
writer.writeCollectionOfObjectValues<string>(undefined, success as string []);
break;
}
}
}
```
changes made to fix thd deserializer. since `undefined` is not an acceptable key in a record, the serializers will …
> Fix serialization and deserialization of composed types in TS

- CHANGELOG.md
- it/config.json
- src/Kiota.Builder/Writers/Php/CodeEnumWriter.cs
- src/Kiota.Builder/Writers/Php/PhpConventionService.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodeEnumWriterTests.cs
- tests/Kiota.Builder.Tests/Writers/Php/CodePropertyWriterTests.cs
Fixes #5635
Property descriptions containing ``/*/*`` causes malformed document in generated Php classes with properties and descriptions.
> Fixes invalid code in Php caused by `/*/*`` in property description

- CHANGELOG.md
- it/config.json
- src/Kiota.Builder/Refiners/TypeScriptRefiner.cs
- src/Kiota.Builder/Writers/TypeScript/CodeConstantWriter.cs
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
Fixes refiners fail to get the serialization function - 
fixes https://github.com/microsoft/kiota/issues/5634
> Fix function writer

- .azure-pipelines/ci-build.yml
- .vscode/settings.json
related https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2751
> security: applies pipeline type requirements

- CHANGELOG.md
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
> fix /plugins description

- vscode/microsoft-kiota/src/modules/steps/index.ts
Kiota UI will quit if a user clicks the mouse in other places when creating a project. This is not expected and has been fixed.
> Fix: Click away dismisses steps

- src/Kiota.Builder/Refiners/GoRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/GoLanguageRefinerTests.cs
Removes unused `strconv` import added when an [`ISODuration`](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/beta/pipelinebuild/174332/security/53a6f3d0c994ce74f28543a3a744def875f53f0ba598927f378769b9738f6200.go#L44) type is parsed and updates types to ignore before importing `strconv`
Unblocks weekly generation build [failure](https://github.com/microsoftgraph/msgraph-beta-sdk-go/actions/runs/12373060629/job/34583008620?pr=488) where `strconv` is imported but not used in [request builder](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/beta/pipelinebuild/174332/security/53a6f3d0c994ce74f28543a3a744def875f53f0ba598927f378769b9738f6200.go)
> fix: Unused strconv import in Go request builder

- CHANGELOG.md
- src/Kiota.Builder/Extensions/IListExtensions.cs
- src/Kiota.Builder/Extensions/OpenApiSchemaExtensions.cs
- src/Kiota.Builder/KiotaBuilder.cs
- tests/Kiota.Builder.Tests/Extensions/OpenApiSchemaExtensionsTests.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
This adds these scenarios as specific cases in `KiotaBuilder.CreateModelDeclarations`. Not sure if this is the best place to handle this but at least this fixes the issue where the properties & possible inheritance were completely missing while not breaking anything existing.
Fixes #5921
> fix: anyOf/oneOf missing properties for intersection/inheritance

- CHANGELOG.md
- src/Kiota.Builder/Kiota.Builder.csproj
- src/kiota/kiota.csproj
- vscode/microsoft-kiota/CHANGELOG.md
- vscode/microsoft-kiota/src/commands/generate/generateClientCommand.ts
Closes #5978 
The RPC server function to create plugins has a set number of arguments. Passing undefined for 'optional' arguments is interpreted as not having passed required arguments.
The changes included in this pull request update the `GenerateClientCommand` class in the `generateClientCommand.ts` file to use `null` instead of `undefined` for the `optional` argument.
> Fix: Plugin generation

- vscode/microsoft-kiota/src/commands/generate/generation-util.ts
Fixes #5988 
The workspace file update after generation wasn't being captured by this function hence an undefined `clientNamespaceName` property down the line causing the error. 
This change enables the extension to read the workspace JSON file directly from the file system each time the function is called, making it get the latest information.
> Fix: Remove post-generation error popup

- .github/policies/branch-protection.yml
> fix: disables signed commits as it blocks dependabot

- scripts/update-vscode-releases.ps1
```pwsh
./scripts/update-vscode-releases.ps1 -version "1.22.2" -filePath ./vscode/microsoft-kiota/package.json -online
```
now produces 1.22.100000003
instead of 1.22.2
> ci: fix vscode extension versioning script to support more than one patch version

- src/Kiota.Builder/Export/PublicAPIExportService.cs
fix: add Dart to the public API export
> fix: add Dart to the public API export

- vscode/microsoft-kiota/CHANGELOG.md
- vscode/microsoft-kiota/src/commands/generate/generateClientCommand.ts
- vscode/microsoft-kiota/src/commands/regenerate/regenerate.service.ts
- vscode/microsoft-kiota/src/commands/regenerate/regenerateButtonCommand.ts
- vscode/microsoft-kiota/src/commands/regenerate/regenerateCommand.ts
- vscode/microsoft-kiota/src/modules/steps/generateSteps.ts
- vscode/microsoft-kiota/src/utilities/generation.ts
- vscode/microsoft-kiota/src/utilities/regeneration.ts
> fix: add a subfolder to the default vscode output path

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/CodeFunctionWriter.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodeFunctionWriterTests.cs
Closes https://github.com/microsoft/kiota-typescript/issues/1276
Fixes serialization of collection of enums in typescript
> fix: collection of enums serialization in typescript

- CHANGELOG.md
- src/Kiota.Builder/Writers/TypeScript/TypeScriptConventionService.cs
- tests/Kiota.Builder.Tests/Writers/TypeScript/CodePropertyWriterTests.cs
Resolves https://github.com/microsoft/kiota/issues/6124
Binary data types in TypeScript are now correctly mapped to `ArrayBuffer` instead of `String`.
> Fix: serialization of binary types in Typescript

- src/Kiota.Builder/Kiota.Builder.csproj
- src/Kiota.Builder/OpenApiDocumentDownloadService.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- src/kiota/kiota.csproj
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
- tests/Kiota.Builder.Tests/Validation/DivergentResponseSchemaTests.cs
- tests/Kiota.Builder.Tests/Validation/GetWithBodyTests.cs
- tests/Kiota.Builder.Tests/Validation/InconsistentTypeFormatPairTests.cs
- tests/Kiota.Builder.Tests/Validation/KnownAndNotSupportedFormatsTests.cs
- tests/Kiota.Builder.Tests/Validation/MissingDiscriminatorTests.cs
- tests/Kiota.Builder.Tests/Validation/MultipleServerEntriesTests.cs
- tests/Kiota.Builder.Tests/Validation/NoContentWithBodyTests.cs
- tests/Kiota.Builder.Tests/Validation/NoServerEntryTests.cs
- tests/Kiota.Builder.Tests/Validation/UrlFormEncodedComplexTests.cs
depends on https://github.com/microsoft/OpenAPI.NET/pull/2235
> chore: update openapi.net dependency to resolve plugin generation error

- src/kiota/Program.cs
- vscode/microsoft-kiota/.vscode/launch.json
- vscode/microsoft-kiota/.vscode/settings.json
- vscode/microsoft-kiota/src/kiotaInterop/index.ts
The VSCode extension uses the standard output stream to read messages from the kiota RPC server. Adding the .NET generic host broke this contract as it registered a Logger with the Console provider that also writes to the standard output stream. This PR removes the console provider and leaves the standard output stream unused.
The long fix for this is to switch from using the standard streams and instead use named pipes for the RPC communication.
Closes #6234
> Fix issue with VSCode extension RPC connection

- .github/workflows/idempotency-tests.yml
- .github/workflows/integration-tests.yml
- it/compare-generation.ps1
- it/generate-code.ps1
- it/get-additional-arguments.ps1
This PR fixes intergration test failures in other PRs like https://github.com/microsoft/kiota/pull/6267
Essentially, changes from https://github.com/microsoft/kiota/pull/6171 would update the description url but configuration parameters like `exclude-path` available from it-config.json were not read properly due to the update of the descriptionUrl to a local path.
> chore: fix intergration test argument passing

- .github/workflows/load-tests.yml
- CHANGELOG.md
- it/typescript/package-lock.json
- it/typescript/package.json
- it/typescript/tsconfig.json
- src/Kiota.Builder/SearchProviders/OpenApiSpec/OpenApiSpecSeachProvider.cs
@ralfhandl you broke everything in https://github.com/OAI/OpenAPI-Specification/pull/4435 ;-)
> fix: pet store description source

- src/kiota/Rpc/PathItem.cs
- src/kiota/Rpc/Server.cs
- tests/Kiota.Builder.IntegrationTests/ModelWithoutBasicInfoInOneOperation.yaml
- vscode/npm-package/integration_tests/integrationGetKiotaTree.spec.ts
- vscode/npm-package/types.ts
Closes #6346 
Adds these fields for operations into getKiotaTree response:
- operationId
- summary
- description
> Add basic API info in response of getKiotaTree #6346

- .github/workflows/build-vscode-extension.yml
- vscode/npm-package/install.ts
Restructures the job matrix to separate testing and binary generation, updating the packaging process, and refining the test execution steps.
Changes to the workflow structure:
* Renamed the `build` job to `test_and_generate_binaries` and adjusted its dependencies and matrix configuration to focus on generating binaries for different architectures and operating systems. 
* Refined the artifact upload steps to align with the new matrix configuration and ensure correct paths and names for the generated binaries. 
* Moved the `build` job to run after `test_and_generate_binaries` and updated its matrix to handle the packaging of the VS Code extension and Npm package.
> Chore: test multiple architectures

- vscode/npm-package/config.ts
- vscode/npm-package/install.ts
- vscode/npm-package/tests/integration/integrationInstall.spec.ts
Allows overriding the package version downloaded and used by passing `binaryVersion` to the `setKiotaConfig` function
> Task: runtime version override

- vscode/npm-package/install.ts
- vscode/npm-package/package.json
- vscode/npm-package/tests/integration/integrationInstall.spec.ts
This PR uses an environment variable to copy the kiota zip file instead of downloading it for development purposes.
The environment variable is named SIDELOADING_KIOTA_BINARY_ZIP_PATH.
When this variable exists, the Kiota zip file is copied from that location instead of downloading it
> Sideloading env variable to copy kiota zip from

- vscode/npm-package/package.json
- vscode/npm-package/scripts/copy-files.js
- vscode/package-lock.json
Using `cpx` to copy the runtime files resulted in a new dependebot security alert. [Uncontrolled resource consumption in braces · Dependabot alert #67 · microsoft/kiota](https://github.com/microsoft/kiota/security/dependabot/67)
This uses the node file system scripts instead of `cpx` to copy the runtime files.
Now uses braces with the earliest fixed version which is 3.0.3.
├─┬ @microsoft/kiota@1.0.0 -> .\npm-package
│ └─┬ ts-loader@9.5.2
│   └─┬ micromatch@4.0.8
│     └── braces@3.0.3
└─┬ kiota@1.21.100000001 -> .\microsoft-kiota
└─┬ @vscode/test-cli@0.0.10
└─┬ chokidar@3.6.0
└── braces@3.0.3 deduped
> Chore: [Package] create copy files script 

- CHANGELOG.md
- src/Kiota.Builder/Refiners/DartRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/DartLanguageRefinerTests.cs
This fixes an issue in the Dart refiner, where property names are adjusted for code style, but their serialized name is also changed by accident.
<details>
<summary>Example spec</summary>
```yaml
openapi: 3.0.1
info:
title: Test
version: 0.0.1
paths:
/action:
post:
summary: Action
operationId: action
requestBody:
content:
application/json:
schema:
$ref: '#/components/schemas/ActionRequest'
responses:
'200':
description: Action Processed
content:
application/json:
type: object
additionalProperties: true
components:
schemas:
ActionRequest:
type: object
properties:
Token:
type: string
type:
type: string
```
</details>
In the example above, a body serialized by kiota would send it like:
```json
{"token":"foo","type":"bar"}
```
whereas the expected body is:
```json
{"Token":"foo","type":"bar"} …
```
> Dart: fix wrong property name casing for serialization

- src/Kiota.Builder/Configuration/GenerationConfiguration.cs
- src/Kiota.Builder/KiotaBuilder.cs
- src/Kiota.Builder/OpenApiDocumentDownloadService.cs
- src/Kiota.Builder/Plugins/PluginsGenerationService.cs
- tests/Kiota.Builder.Tests/Plugins/PluginsGenerationServiceTests.cs
Added support for generating and merging multiple API plugin manifests at once.
Fixes https://github.com/microsoft/kiota/issues/6140
> Support for generating and merging multiple API plugin manifests

- vscode/npm-package/tests/integration/integrationInstall.spec.ts
It skips to download tests for win-arm64 platform until a version is available.
> Skip download tests for win-arm64

- CHANGELOG.md
- src/Kiota.Builder/Extensions/OpenApiUrlTreeNodeExtensions.cs
- tests/Kiota.Builder.Tests/KiotaBuilderTests.cs
> fix: a bug where a trailing slash in the path item lead to missing query parameters

- CHANGELOG.md
- src/Kiota.Builder/Refiners/DartRefiner.cs
- tests/Kiota.Builder.Tests/Refiners/DartLanguageRefinerTests.cs
Fixes #6444.
This fixes an oversight I accidentially introduced in #6393.
I adjusted the serialization name so it is correctly preserved in its original casing, but I forgot to check if it was already explicitly set.
> fix: Don't overwrite serialization name if it is already set

- CHANGELOG.md
- src/Kiota.Builder/Refiners/PythonRefiner.cs
- src/Kiota.Builder/Writers/Python/CodePropertyWriter.cs
- tests/Kiota.Builder.Tests/Refiners/PythonLanguageRefinerTests.cs
- tests/Kiota.Builder.Tests/Writers/Python/CodePropertyWriterTests.cs
Fixes #6350
closes #6489
* Use the PythonRefiner to set the default value for non-nullable array types.
* Update the CodePropertyWriter to respect the default value if set.
* Add tests for the changes
> Python: Set a default value for non-nullable array fields

- .github/workflows/build-vscode-extension.yml
- .github/workflows/check-translations.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/codeql-required-workaround.yml
- .github/workflows/dotnet-required-workaround.yml
- .github/workflows/dotnet.yml
- .github/workflows/idempotency-tests.yml
- .github/workflows/integration-tests.yml
- .github/workflows/sonarcloud.yml
> enables merge groups so we don't have to manually rebase PRs all the time
